# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")


# COMMAND ----------
# DBTITLE 1, DAYS_0


df_0=spark.sql("""
    SELECT
        DAY_DT AS DAY_DT,
        BUSINESS_DAY_FLAG AS BUSINESS_DAY_FLAG,
        HOLIDAY_FLAG AS HOLIDAY_FLAG,
        DAY_OF_WK_NAME AS DAY_OF_WK_NAME,
        DAY_OF_WK_NAME_ABBR AS DAY_OF_WK_NAME_ABBR,
        DAY_OF_WK_NBR AS DAY_OF_WK_NBR,
        CAL_DAY_OF_MO_NBR AS CAL_DAY_OF_MO_NBR,
        CAL_DAY_OF_YR_NBR AS CAL_DAY_OF_YR_NBR,
        CAL_WK AS CAL_WK,
        CAL_WK_NBR AS CAL_WK_NBR,
        CAL_MO AS CAL_MO,
        CAL_MO_NBR AS CAL_MO_NBR,
        CAL_MO_NAME AS CAL_MO_NAME,
        CAL_MO_NAME_ABBR AS CAL_MO_NAME_ABBR,
        CAL_QTR AS CAL_QTR,
        CAL_QTR_NBR AS CAL_QTR_NBR,
        CAL_HALF AS CAL_HALF,
        CAL_YR AS CAL_YR,
        FISCAL_DAY_OF_MO_NBR AS FISCAL_DAY_OF_MO_NBR,
        FISCAL_DAY_OF_YR_NBR AS FISCAL_DAY_OF_YR_NBR,
        FISCAL_WK AS FISCAL_WK,
        FISCAL_WK_NBR AS FISCAL_WK_NBR,
        FISCAL_MO AS FISCAL_MO,
        FISCAL_MO_NBR AS FISCAL_MO_NBR,
        FISCAL_MO_NAME AS FISCAL_MO_NAME,
        FISCAL_MO_NAME_ABBR AS FISCAL_MO_NAME_ABBR,
        FISCAL_QTR AS FISCAL_QTR,
        FISCAL_QTR_NBR AS FISCAL_QTR_NBR,
        FISCAL_HALF AS FISCAL_HALF,
        FISCAL_YR AS FISCAL_YR,
        LYR_WEEK_DT AS LYR_WEEK_DT,
        LWK_WEEK_DT AS LWK_WEEK_DT,
        WEEK_DT AS WEEK_DT,
        EST_TIME_CONV_AMT AS EST_TIME_CONV_AMT,
        EST_TIME_CONV_HRS AS EST_TIME_CONV_HRS,
        ES0_TIME_CONV_AMT AS ES0_TIME_CONV_AMT,
        ES0_TIME_CONV_HRS AS ES0_TIME_CONV_HRS,
        CST_TIME_CONV_AMT AS CST_TIME_CONV_AMT,
        CST_TIME_CONV_HRS AS CST_TIME_CONV_HRS,
        CS0_TIME_CONV_AMT AS CS0_TIME_CONV_AMT,
        CS0_TIME_CONV_HRS AS CS0_TIME_CONV_HRS,
        MST_TIME_CONV_AMT AS MST_TIME_CONV_AMT,
        MST_TIME_CONV_HRS AS MST_TIME_CONV_HRS,
        MS0_TIME_CONV_AMT AS MS0_TIME_CONV_AMT,
        MS0_TIME_CONV_HRS AS MS0_TIME_CONV_HRS,
        PST_TIME_CONV_AMT AS PST_TIME_CONV_AMT,
        PST_TIME_CONV_HRS AS PST_TIME_CONV_HRS,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        DAYS""")

df_0.createOrReplaceTempView("DAYS_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_Days_1


df_1=spark.sql("""
    SELECT
        DayDt,
        BusinessDayFlag,
        HolidayFlag,
        DayOfWkName,
        DayOfWkNameAbbr,
        DayOfWkNbr,
        CalDayOfMoNbr,
        CalDayOfYrNbr,
        CalWk,
        CalWkNbr,
        CalMo,
        CalMoNbr,
        CalMoName,
        CalMoNameAbbr,
        CalQtr,
        CalQtrNbr,
        CalHalf,
        CalYr,
        FiscalDayOfMoNbr,
        FiscalDayOfYrNbr,
        FiscalWk,
        FiscalWkNbr,
        FiscalMo,
        FiscalMoNbr,
        FiscalMoName,
        FiscalMoNameAbbr,
        FiscalQtr,
        FiscalQtrNbr,
        FiscalHalf,
        FiscalYr,
        LyrWeekDt,
        LwkWeekDt,
        WeekDt,
        EstTimeConvAmt,
        EstTimeConvHrs,
        Es0TimeConvAmt,
        Es0TimeConvHrs,
        CstTimeConvAmt,
        CstTimeConvHrs,
        Cs0TimeConvAmt,
        Cs0TimeConvHrs,
        MstTimeConvAmt,
        MstTimeConvHrs,
        Ms0TimeConvAmt,
        Ms0TimeConvHrs,
        PstTimeConvAmt,
        PstTimeConvHrs 
    FROM
        Days 
    WHERE
        FiscalYr = DATEPART(YY, GETDATE()) + 2""")

df_1.createOrReplaceTempView("SQ_Shortcut_to_Days_1")

# COMMAND ----------
# DBTITLE 1, DAYS


spark.sql("""INSERT INTO DAYS SELECT DayDt AS DAY_DT,
BusinessDayFlag AS BUSINESS_DAY_FLAG,
HolidayFlag AS HOLIDAY_FLAG,
DayOfWkName AS DAY_OF_WK_NAME,
DayOfWkNameAbbr AS DAY_OF_WK_NAME_ABBR,
DayOfWkNbr AS DAY_OF_WK_NBR,
CalDayOfMoNbr AS CAL_DAY_OF_MO_NBR,
CalDayOfYrNbr AS CAL_DAY_OF_YR_NBR,
CalWk AS CAL_WK,
CalWkNbr AS CAL_WK_NBR,
CalMo AS CAL_MO,
CalMoNbr AS CAL_MO_NBR,
CalMoName AS CAL_MO_NAME,
CalMoNameAbbr AS CAL_MO_NAME_ABBR,
CalQtr AS CAL_QTR,
CalQtrNbr AS CAL_QTR_NBR,
CalHalf AS CAL_HALF,
CalYr AS CAL_YR,
FiscalDayOfMoNbr AS FISCAL_DAY_OF_MO_NBR,
FiscalDayOfYrNbr AS FISCAL_DAY_OF_YR_NBR,
FiscalWk AS FISCAL_WK,
FiscalWkNbr AS FISCAL_WK_NBR,
FiscalMo AS FISCAL_MO,
FiscalMoNbr AS FISCAL_MO_NBR,
FiscalMoName AS FISCAL_MO_NAME,
FiscalMoNameAbbr AS FISCAL_MO_NAME_ABBR,
FiscalQtr AS FISCAL_QTR,
FiscalQtrNbr AS FISCAL_QTR_NBR,
FiscalHalf AS FISCAL_HALF,
FiscalYr AS FISCAL_YR,
LyrWeekDt AS LYR_WEEK_DT,
LwkWeekDt AS LWK_WEEK_DT,
WeekDt AS WEEK_DT,
EstTimeConvAmt AS EST_TIME_CONV_AMT,
EstTimeConvHrs AS EST_TIME_CONV_HRS,
Es0TimeConvAmt AS ES0_TIME_CONV_AMT,
Es0TimeConvHrs AS ES0_TIME_CONV_HRS,
CstTimeConvAmt AS CST_TIME_CONV_AMT,
CstTimeConvHrs AS CST_TIME_CONV_HRS,
Cs0TimeConvAmt AS CS0_TIME_CONV_AMT,
Cs0TimeConvHrs AS CS0_TIME_CONV_HRS,
MstTimeConvAmt AS MST_TIME_CONV_AMT,
MstTimeConvHrs AS MST_TIME_CONV_HRS,
Ms0TimeConvAmt AS MS0_TIME_CONV_AMT,
Ms0TimeConvHrs AS MS0_TIME_CONV_HRS,
PstTimeConvAmt AS PST_TIME_CONV_AMT,
PstTimeConvHrs AS PST_TIME_CONV_HRS FROM SQ_Shortcut_to_Days_1""")

# COMMAND ----------
# DBTITLE 1, DAYS


spark.sql("""INSERT INTO DAYS SELECT DAY_DT AS DAY_DT,
BUSINESS_DAY_FLAG AS BUSINESS_DAY_FLAG,
HOLIDAY_FLAG AS HOLIDAY_FLAG,
DAY_OF_WK_NAME AS DAY_OF_WK_NAME,
DAY_OF_WK_NAME_ABBR AS DAY_OF_WK_NAME_ABBR,
DAY_OF_WK_NBR AS DAY_OF_WK_NBR,
CAL_DAY_OF_MO_NBR AS CAL_DAY_OF_MO_NBR,
CAL_DAY_OF_YR_NBR AS CAL_DAY_OF_YR_NBR,
CAL_WK AS CAL_WK,
CAL_WK_NBR AS CAL_WK_NBR,
CAL_MO AS CAL_MO,
CAL_MO_NBR AS CAL_MO_NBR,
CAL_MO_NAME AS CAL_MO_NAME,
CAL_MO_NAME_ABBR AS CAL_MO_NAME_ABBR,
CAL_QTR AS CAL_QTR,
CAL_QTR_NBR AS CAL_QTR_NBR,
CAL_HALF AS CAL_HALF,
CAL_YR AS CAL_YR,
FISCAL_DAY_OF_MO_NBR AS FISCAL_DAY_OF_MO_NBR,
FISCAL_DAY_OF_YR_NBR AS FISCAL_DAY_OF_YR_NBR,
FISCAL_WK AS FISCAL_WK,
FISCAL_WK_NBR AS FISCAL_WK_NBR,
FISCAL_MO AS FISCAL_MO,
FISCAL_MO_NBR AS FISCAL_MO_NBR,
FISCAL_MO_NAME AS FISCAL_MO_NAME,
FISCAL_MO_NAME_ABBR AS FISCAL_MO_NAME_ABBR,
FISCAL_QTR AS FISCAL_QTR,
FISCAL_QTR_NBR AS FISCAL_QTR_NBR,
FISCAL_HALF AS FISCAL_HALF,
FISCAL_YR AS FISCAL_YR,
LYR_WEEK_DT AS LYR_WEEK_DT,
LWK_WEEK_DT AS LWK_WEEK_DT,
WEEK_DT AS WEEK_DT,
EST_TIME_CONV_AMT AS EST_TIME_CONV_AMT,
EST_TIME_CONV_HRS AS EST_TIME_CONV_HRS,
ES0_TIME_CONV_AMT AS ES0_TIME_CONV_AMT,
ES0_TIME_CONV_HRS AS ES0_TIME_CONV_HRS,
CST_TIME_CONV_AMT AS CST_TIME_CONV_AMT,
CST_TIME_CONV_HRS AS CST_TIME_CONV_HRS,
CS0_TIME_CONV_AMT AS CS0_TIME_CONV_AMT,
CS0_TIME_CONV_HRS AS CS0_TIME_CONV_HRS,
MST_TIME_CONV_AMT AS MST_TIME_CONV_AMT,
MST_TIME_CONV_HRS AS MST_TIME_CONV_HRS,
MS0_TIME_CONV_AMT AS MS0_TIME_CONV_AMT,
MS0_TIME_CONV_HRS AS MS0_TIME_CONV_HRS,
PST_TIME_CONV_AMT AS PST_TIME_CONV_AMT,
PST_TIME_CONV_HRS AS PST_TIME_CONV_HRS FROM SQ_Shortcut_to_Days_1""")