# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")


# COMMAND ----------
# DBTITLE 1, NATIONAL_COST_PRE_0


df_0=spark.sql("""
    SELECT
        SKU_NBR AS SKU_NBR,
        VENDOR_ID AS VENDOR_ID,
        PURCH_ORG_CD AS PURCH_ORG_CD,
        COND_TYPE_CD AS COND_TYPE_CD,
        PURCH_INFO_CD AS PURCH_INFO_CD,
        COND_END_DT AS COND_END_DT,
        DELETE_IND AS DELETE_IND,
        COND_EFF_DT AS COND_EFF_DT,
        COND_RECORD_NBR AS COND_RECORD_NBR,
        COND_AMT AS COND_AMT,
        PROMOTION_CD AS PROMOTION_CD,
        COND_RT_UNIT AS COND_RT_UNIT,
        COND_PRICE_UNIT AS COND_PRICE_UNIT,
        COND_UNIT AS COND_UNIT,
        UNIT_NUMERATOR AS UNIT_NUMERATOR,
        UNIT_DENOMINATOR AS UNIT_DENOMINATOR,
        LOAD_DT AS LOAD_DT,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        NATIONAL_COST_PRE""")

df_0.createOrReplaceTempView("NATIONAL_COST_PRE_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_To_NATIONAL_COST_PRE_1


df_1=spark.sql("""
    SELECT
        NCP.SKU_NBR,
        NCP.VENDOR_ID,
        NCP.PURCH_ORG_CD,
        NCP.COND_TYPE_CD,
        NCP.PURCH_INFO_CD,
        NCP.COND_END_DT,
        NCP.DELETE_IND,
        NCP.COND_EFF_DT,
        NCP.COND_RECORD_NBR,
        NCP.COND_AMT,
        NCP.PROMOTION_CD,
        NCP.COND_RT_UNIT,
        NCP.COND_PRICE_UNIT,
        NCP.COND_UNIT,
        NCP.UNIT_NUMERATOR,
        NCP.UNIT_DENOMINATOR,
        NCP.LOAD_DT,
        CASE 
            WHEN NCD.SKU_NBR IS NULL THEN 0 
            ELSE 1 
        END AS UPDATE_FLAG 
    FROM
        NATIONAL_COST_PRE NCP 
    LEFT OUTER JOIN
        NATIONAL_COST_DAY NCD 
            ON NCP.SKU_NBR = NCD.SKU_NBR 
            AND NCP.VENDOR_ID = NCD.VENDOR_ID 
            AND NCP.PURCH_ORG_CD = NCD.PURCH_ORG_CD 
            AND NCP.COND_TYPE_CD = NCD.COND_TYPE_CD 
            AND NCP.PURCH_INFO_CD = NCD.PURCH_INFO_CD 
            AND NCP.COND_END_DT = NCD.COND_END_DT""")

df_1.createOrReplaceTempView("SQ_Shortcut_To_NATIONAL_COST_PRE_1")

# COMMAND ----------
# DBTITLE 1, UPD_Insert_Update_2


df_2=spark.sql("""
    SELECT
        SKU_NBR AS SKU_NBR,
        VENDOR_ID AS VENDOR_ID,
        PURCH_ORG_CD AS PURCH_ORG_CD,
        COND_TYPE_CD AS COND_TYPE_CD,
        PURCH_INFO_CD AS PURCH_INFO_CD,
        COND_END_DT AS COND_END_DT,
        DELETE_IND AS DELETE_IND,
        COND_EFF_DT AS COND_EFF_DT,
        COND_RECORD_NBR AS COND_RECORD_NBR,
        COND_AMT AS COND_AMT,
        PROMOTION_CD AS PROMOTION_CD,
        COND_RT_UNIT AS COND_RT_UNIT,
        COND_PRICE_UNIT AS COND_PRICE_UNIT,
        COND_UNIT AS COND_UNIT,
        UNIT_NUMERATOR AS UNIT_NUMERATOR,
        UNIT_DENOMINATOR AS UNIT_DENOMINATOR,
        LOAD_DT AS LOAD_DT,
        UPDATE_FLAG AS UPDATE_FLAG,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_To_NATIONAL_COST_PRE_1""")

df_2.createOrReplaceTempView("UPD_Insert_Update_2")

# COMMAND ----------
# DBTITLE 1, NATIONAL_COST_DAY


spark.sql("""INSERT INTO NATIONAL_COST_DAY SELECT SKU_NBR AS SKU_NBR,
VENDOR_ID AS VENDOR_ID,
PURCH_ORG_CD AS PURCH_ORG_CD,
COND_TYPE_CD AS COND_TYPE_CD,
PURCH_INFO_CD AS PURCH_INFO_CD,
COND_END_DT AS COND_END_DT,
DELETE_IND AS DELETE_IND,
COND_EFF_DT AS COND_EFF_DT,
COND_RECORD_NBR AS COND_RECORD_NBR,
COND_AMT AS COND_AMT,
PROMOTION_CD AS PROMOTION_CD,
COND_RT_UNIT AS COND_RT_UNIT,
COND_PRICE_UNIT AS COND_PRICE_UNIT,
COND_UNIT AS COND_UNIT,
UNIT_NUMERATOR AS UNIT_NUMERATOR,
UNIT_DENOMINATOR AS UNIT_DENOMINATOR,
LOAD_DT AS LOAD_DT FROM UPD_Insert_Update_2""")