# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")


# COMMAND ----------

# DBTITLE 1, SALES_RANKING_CODE_0

df_0=spark.sql("""
    SELECT
        RANKING_CD AS RANKING_CD,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL AS RANKING_LEVEL,
        RANKING_DESC AS RANKING_DESC,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        LOAD_TSTMP AS LOAD_TSTMP,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        SALES_RANKING_CODE""")

df_0.createOrReplaceTempView("SALES_RANKING_CODE_0")

# COMMAND ----------

# DBTITLE 1, SQ_Shortcut_to_SALES_RANKING_CODE_MERCH_1

df_1=spark.sql("""
    SELECT
        RANKING_CD_MERCH AS RANKING_CD_MERCH,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        LOAD_TSTMP AS LOAD_TSTMP,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SALES_RANKING_CODE_0""")

df_1.createOrReplaceTempView("SQ_Shortcut_to_SALES_RANKING_CODE_MERCH_1")

# COMMAND ----------

# DBTITLE 1, EXP_MERCH_LKUP_2

df_2=spark.sql("""
    SELECT
        1 AS DUMMY_JOIN,
        RANKING_CD_MERCH AS RANKING_CD_MERCH,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_to_SALES_RANKING_CODE_MERCH_1""")

df_2.createOrReplaceTempView("EXP_MERCH_LKUP_2")

# COMMAND ----------

# DBTITLE 1, SQ_Shortcut_to_SALES_RANKING_CODE_3

df_3=spark.sql("""
    SELECT
        RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        LOAD_TSTMP AS LOAD_TSTMP,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SALES_RANKING_CODE_0""")

df_3.createOrReplaceTempView("SQ_Shortcut_to_SALES_RANKING_CODE_3")

# COMMAND ----------

# DBTITLE 1, EXP_TOTAL_LKUP_4

df_4=spark.sql("""
    SELECT
        1 AS DUMMY_JOIN,
        RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_to_SALES_RANKING_CODE_3""")

df_4.createOrReplaceTempView("EXP_TOTAL_LKUP_4")

# COMMAND ----------

# DBTITLE 1, SQ_Shortcut_to_SALES_RANKING_CODE_HOTEL_5

df_5=spark.sql("""
    SELECT
        RANKING_CD_HOTEL AS RANKING_CD_HOTEL,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_HOTEL AS RANKING_LEVEL_HOTEL,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        LOAD_TSTMP AS LOAD_TSTMP,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SALES_RANKING_CODE_0""")

df_5.createOrReplaceTempView("SQ_Shortcut_to_SALES_RANKING_CODE_HOTEL_5")

# COMMAND ----------

# DBTITLE 1, EXP_HOTEL_LKUP_6

df_6=spark.sql("""
    SELECT
        1 AS DUMMY_JOIN,
        RANKING_CD_HOTEL AS RANKING_CD_HOTEL,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_HOTEL AS RANKING_LEVEL_HOTEL,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_to_SALES_RANKING_CODE_HOTEL_5""")

df_6.createOrReplaceTempView("EXP_HOTEL_LKUP_6")

# COMMAND ----------

# DBTITLE 1, SQ_Shortcut_to_SALES_RANKING_CODE_SALON_7

df_7=spark.sql("""
    SELECT
        RANKING_CD_SALON AS RANKING_CD_SALON,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_SALON AS RANKING_LEVEL_SALON,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        LOAD_TSTMP AS LOAD_TSTMP,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SALES_RANKING_CODE_0""")

df_7.createOrReplaceTempView("SQ_Shortcut_to_SALES_RANKING_CODE_SALON_7")

# COMMAND ----------

# DBTITLE 1, EXP_SALON_LKUP_8

df_8=spark.sql("""
    SELECT
        1 AS DUMMY_JOIN,
        RANKING_CD_SALON AS RANKING_CD_SALON,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_SALON AS RANKING_LEVEL_SALON,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_to_SALES_RANKING_CODE_SALON_7""")

df_8.createOrReplaceTempView("EXP_SALON_LKUP_8")

# COMMAND ----------

# DBTITLE 1, SQ_Shortcut_to_SALES_RANKING_CODE_CONSUM_9

df_9=spark.sql("""
    SELECT
        RANKING_CD_CONSUM AS RANKING_CD_CONSUM,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_CONSUM AS RANKING_LEVEL_CONSUM,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        LOAD_TSTMP AS LOAD_TSTMP,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SALES_RANKING_CODE_0""")

df_9.createOrReplaceTempView("SQ_Shortcut_to_SALES_RANKING_CODE_CONSUM_9")

# COMMAND ----------

# DBTITLE 1, EXP_CONSUM_LKUP_10

df_10=spark.sql("""
    SELECT
        1 AS DUMMY_JOIN,
        RANKING_CD_CONSUM AS RANKING_CD_CONSUM,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_CONSUM AS RANKING_LEVEL_CONSUM,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_to_SALES_RANKING_CODE_CONSUM_9""")

df_10.createOrReplaceTempView("EXP_CONSUM_LKUP_10")

# COMMAND ----------

# DBTITLE 1, SQ_Shortcut_to_SALES_RANKING_CODE_HGOODS_11

df_11=spark.sql("""
    SELECT
        RANKING_CD_HGOODS AS RANKING_CD_HGOODS,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_HGOODS AS RANKING_LEVEL_HGOODS,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        LOAD_TSTMP AS LOAD_TSTMP,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SALES_RANKING_CODE_0""")

df_11.createOrReplaceTempView("SQ_Shortcut_to_SALES_RANKING_CODE_HGOODS_11")

# COMMAND ----------

# DBTITLE 1, EXP_HGOODS_LKUP_12

df_12=spark.sql("""
    SELECT
        1 AS DUMMY_JOIN,
        RANKING_CD_HGOODS AS RANKING_CD_HGOODS,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_HGOODS AS RANKING_LEVEL_HGOODS,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_to_SALES_RANKING_CODE_HGOODS_11""")

df_12.createOrReplaceTempView("EXP_HGOODS_LKUP_12")

# COMMAND ----------

# DBTITLE 1, SQ_Shortcut_to_SALES_RANKING_CODE_SPECIALTY_13

df_13=spark.sql("""
    SELECT
        RANKING_CD AS RANKING_CD,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL AS RANKING_LEVEL,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        LOAD_TSTMP AS LOAD_TSTMP,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SALES_RANKING_CODE_0""")

df_13.createOrReplaceTempView("SQ_Shortcut_to_SALES_RANKING_CODE_SPECIALTY_13")

# COMMAND ----------

# DBTITLE 1, EXP_SPECIALTY_LKUP_14

df_14=spark.sql("""
    SELECT
        1 AS DUMMY_JOIN,
        RANKING_CD_SPECIALTY AS RANKING_CD_SPECIALTY,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_SPECIALTY AS RANKING_LEVEL_SPECIALTY,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_to_SALES_RANKING_CODE_SPECIALTY_13""")

df_14.createOrReplaceTempView("EXP_SPECIALTY_LKUP_14")

# COMMAND ----------

# DBTITLE 1, SQ_Shortcut_to_SALES_RANKING_CODE_SERVICES_15

df_15=spark.sql("""
    SELECT
        RANKING_CD_SERVICES AS RANKING_CD_SERVICES,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_SERVICES AS RANKING_LEVEL_SERVICES,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        LOAD_TSTMP AS LOAD_TSTMP,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SALES_RANKING_CODE_0""")

df_15.createOrReplaceTempView("SQ_Shortcut_to_SALES_RANKING_CODE_SERVICES_15")

# COMMAND ----------

# DBTITLE 1, EXP_SERVICES_LKUP_16

df_16=spark.sql("""
    SELECT
        1 AS DUMMY_JOIN,
        RANKING_CD_SERVICES AS RANKING_CD_SERVICES,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_SERVICES AS RANKING_LEVEL_SERVICES,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_to_SALES_RANKING_CODE_SERVICES_15""")

df_16.createOrReplaceTempView("EXP_SERVICES_LKUP_16")

# COMMAND ----------

# DBTITLE 1, SQ_Shortcut_to_SALES_RANKING_CODE_TRAINING_17

df_17=spark.sql("""
    SELECT
        RANKING_CD_TRAINING AS RANKING_CD_TRAINING,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_TRAINING AS RANKING_LEVEL_TRAINING,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        LOAD_TSTMP AS LOAD_TSTMP,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SALES_RANKING_CODE_0""")

df_17.createOrReplaceTempView("SQ_Shortcut_to_SALES_RANKING_CODE_TRAINING_17")

# COMMAND ----------

# DBTITLE 1, EXP_TRAINING_LKUP_18

df_18=spark.sql("""
    SELECT
        1 AS DUMMY_JOIN,
        RANKING_CD_TRAINING AS RANKING_CD_TRAINING,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_TRAINING AS RANKING_LEVEL_TRAINING,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_to_SALES_RANKING_CODE_TRAINING_17""")

df_18.createOrReplaceTempView("EXP_TRAINING_LKUP_18")

# COMMAND ----------

# DBTITLE 1, SALES_RANKING_RUNNING_SUM_PRE_19

df_19=spark.sql("""
    SELECT
        WEEK_DT AS WEEK_DT,
        LOCATION_ID AS LOCATION_ID,
        COMP_CURR_FLAG AS COMP_CURR_FLAG,
        SALES_CURR_FLAG AS SALES_CURR_FLAG,
        TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        SALES_RANKING_RUNNING_SUM_PRE""")

df_19.createOrReplaceTempView("SALES_RANKING_RUNNING_SUM_PRE_19")

# COMMAND ----------

# DBTITLE 1, SQ_Shortcut_to_SALES_RANKING_RUNNING_SUM_PRE_20

df_20=spark.sql("""
    SELECT
        WEEK_DT AS WEEK_DT,
        LOCATION_ID AS LOCATION_ID,
        COMP_CURR_FLAG AS COMP_CURR_FLAG,
        SALES_CURR_FLAG AS SALES_CURR_FLAG,
        TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SALES_RANKING_RUNNING_SUM_PRE_19""")

df_20.createOrReplaceTempView("SQ_Shortcut_to_SALES_RANKING_RUNNING_SUM_PRE_20")

# COMMAND ----------

# DBTITLE 1, EXP_PRE_DUMMY_21

df_21=spark.sql("""
    SELECT
        1 AS DUMMY_JOIN,
        WEEK_DT AS WEEK_DT,
        LOCATION_ID AS LOCATION_ID,
        COMP_CURR_FLAG AS COMP_CURR_FLAG,
        SALES_CURR_FLAG AS SALES_CURR_FLAG,
        TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_to_SALES_RANKING_RUNNING_SUM_PRE_20""")

df_21.createOrReplaceTempView("EXP_PRE_DUMMY_21")

# COMMAND ----------

# DBTITLE 1, JNR_TOTALS_LKUP_22

df_22=spark.sql("""
    SELECT
        DETAIL.DUMMY_JOIN AS DUMMY_JOIN,
        DETAIL.RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        DETAIL.RANKING_START_DT AS RANKING_START_DT,
        DETAIL.RANKING_END_DT AS RANKING_END_DT,
        DETAIL.RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        DETAIL.RANKING_START_PERCENT AS RANKING_START_PERCENT,
        DETAIL.RANKING_END_PERCENT AS RANKING_END_PERCENT,
        MASTER.DUMMY_JOIN AS DUMMY_JOIN1,
        MASTER.WEEK_DT AS WEEK_DT,
        MASTER.LOCATION_ID AS LOCATION_ID,
        MASTER.COMP_CURR_FLAG AS COMP_CURR_FLAG,
        MASTER.SALES_CURR_FLAG AS SALES_CURR_FLAG,
        MASTER.TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        MASTER.TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        MASTER.STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        MASTER.RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MASTER.MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MASTER.MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        MASTER.STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        MASTER.RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        MASTER.SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        MASTER.SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        MASTER.STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        MASTER.RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        MASTER.SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        MASTER.SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        MASTER.STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        MASTER.RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        MASTER.TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        MASTER.TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        MASTER.STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        MASTER.RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        MASTER.HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        MASTER.HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        MASTER.STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        MASTER.RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        MASTER.CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        MASTER.CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        MASTER.STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        MASTER.RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        MASTER.HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        MASTER.HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        MASTER.STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        MASTER.RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        MASTER.SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        MASTER.SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        MASTER.STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        MASTER.RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        EXP_PRE_DUMMY_21 MASTER 
    RIGHT JOIN
        EXP_TOTAL_LKUP_4 DETAIL 
            ON MASTER.DUMMY_JOIN = DETAIL.DUMMY_JOIN""")

df_22.createOrReplaceTempView("JNR_TOTALS_LKUP_22")

# COMMAND ----------

# DBTITLE 1, FIL_TOTALS_LKUP_23

df_23=spark.sql("""
    SELECT
        DUMMY_JOIN1 AS DUMMY_JOIN1,
        WEEK_DT AS WEEK_DT,
        LOCATION_ID AS LOCATION_ID,
        COMP_CURR_FLAG AS COMP_CURR_FLAG,
        SALES_CURR_FLAG AS SALES_CURR_FLAG,
        TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNR_TOTALS_LKUP_22 
    WHERE
        WEEK_DT >= RANKING_START_DT 
        AND WEEK_DT <= RANKING_END_DT 
        AND RUNNING_SUM_TOTAL_SALES_PCT > RANKING_START_PERCENT 
        AND RUNNING_SUM_TOTAL_SALES_PCT <= RANKING_END_PERCENT""")

df_23.createOrReplaceTempView("FIL_TOTALS_LKUP_23")

# COMMAND ----------

# DBTITLE 1, JNR_MERCH_LKUP_24

df_24=spark.sql("""
    SELECT
        MASTER.DUMMY_JOIN1 AS DUMMY_JOIN1,
        MASTER.WEEK_DT AS WEEK_DT,
        MASTER.LOCATION_ID AS LOCATION_ID,
        MASTER.COMP_CURR_FLAG AS COMP_CURR_FLAG,
        MASTER.SALES_CURR_FLAG AS SALES_CURR_FLAG,
        MASTER.TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        MASTER.TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        MASTER.STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        MASTER.RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MASTER.MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MASTER.MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        MASTER.STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        MASTER.RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        MASTER.SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        MASTER.SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        MASTER.STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        MASTER.RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        MASTER.SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        MASTER.SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        MASTER.STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        MASTER.RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        MASTER.TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        MASTER.TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        MASTER.STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        MASTER.RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        MASTER.HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        MASTER.HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        MASTER.STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        MASTER.RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        MASTER.CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        MASTER.CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        MASTER.STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        MASTER.RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        MASTER.HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        MASTER.HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        MASTER.STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        MASTER.RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        MASTER.SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        MASTER.SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        MASTER.STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        MASTER.RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        MASTER.RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        MASTER.RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        DETAIL.DUMMY_JOIN AS DUMMY_JOIN,
        DETAIL.RANKING_CD_MERCH AS RANKING_CD_MERCH,
        DETAIL.RANKING_START_DT AS RANKING_START_DT,
        DETAIL.RANKING_END_DT AS RANKING_END_DT,
        DETAIL.RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        DETAIL.RANKING_START_PERCENT AS RANKING_START_PERCENT,
        DETAIL.RANKING_END_PERCENT AS RANKING_END_PERCENT,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        FIL_TOTALS_LKUP_23 MASTER 
    RIGHT JOIN
        EXP_MERCH_LKUP_2 DETAIL 
            ON MASTER.DUMMY_JOIN1 = DETAIL.DUMMY_JOIN""")

df_24.createOrReplaceTempView("JNR_MERCH_LKUP_24")

# COMMAND ----------

# DBTITLE 1, FIL_MERCH_LKUP_25

df_25=spark.sql("""
    SELECT
        DUMMY_JOIN1 AS DUMMY_JOIN1,
        WEEK_DT AS WEEK_DT,
        LOCATION_ID AS LOCATION_ID,
        COMP_CURR_FLAG AS COMP_CURR_FLAG,
        SALES_CURR_FLAG AS SALES_CURR_FLAG,
        TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        RANKING_CD_MERCH AS RANKING_CD_MERCH,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNR_MERCH_LKUP_24 
    WHERE
        WEEK_DT >= RANKING_START_DT 
        AND WEEK_DT <= RANKING_END_DT 
        AND RUNNING_SUM_MERCH_SALES_PCT > RANKING_START_PERCENT 
        AND RUNNING_SUM_MERCH_SALES_PCT <= RANKING_END_PERCENT""")

df_25.createOrReplaceTempView("FIL_MERCH_LKUP_25")

# COMMAND ----------

# DBTITLE 1, JNR_SERVICES_LKUP_26

df_26=spark.sql("""
    SELECT
        MASTER.DUMMY_JOIN1 AS DUMMY_JOIN1,
        MASTER.WEEK_DT AS WEEK_DT,
        MASTER.LOCATION_ID AS LOCATION_ID,
        MASTER.COMP_CURR_FLAG AS COMP_CURR_FLAG,
        MASTER.SALES_CURR_FLAG AS SALES_CURR_FLAG,
        MASTER.TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        MASTER.TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        MASTER.STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        MASTER.RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MASTER.MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MASTER.MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        MASTER.STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        MASTER.RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        MASTER.SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        MASTER.SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        MASTER.STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        MASTER.RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        MASTER.SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        MASTER.SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        MASTER.STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        MASTER.RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        MASTER.TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        MASTER.TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        MASTER.STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        MASTER.RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        MASTER.HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        MASTER.HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        MASTER.STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        MASTER.RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        MASTER.CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        MASTER.CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        MASTER.STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        MASTER.RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        MASTER.HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        MASTER.HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        MASTER.STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        MASTER.RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        MASTER.SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        MASTER.SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        MASTER.STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        MASTER.RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        MASTER.RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        MASTER.RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        MASTER.RANKING_CD_MERCH AS RANKING_CD_MERCH,
        MASTER.RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        DETAIL.DUMMY_JOIN AS DUMMY_JOIN,
        DETAIL.RANKING_CD_SERVICES AS RANKING_CD_SERVICES,
        DETAIL.RANKING_START_DT AS RANKING_START_DT,
        DETAIL.RANKING_END_DT AS RANKING_END_DT,
        DETAIL.RANKING_LEVEL_SERVICES AS RANKING_LEVEL_SERVICES,
        DETAIL.RANKING_START_PERCENT AS RANKING_START_PERCENT,
        DETAIL.RANKING_END_PERCENT AS RANKING_END_PERCENT,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        FIL_MERCH_LKUP_25 MASTER 
    RIGHT JOIN
        EXP_SERVICES_LKUP_16 DETAIL 
            ON MASTER.DUMMY_JOIN1 = DETAIL.DUMMY_JOIN""")

df_26.createOrReplaceTempView("JNR_SERVICES_LKUP_26")

# COMMAND ----------

# DBTITLE 1, FIL_SERVICES_LKUP_27

df_27=spark.sql("""
    SELECT
        DUMMY_JOIN1 AS DUMMY_JOIN1,
        WEEK_DT AS WEEK_DT,
        LOCATION_ID AS LOCATION_ID,
        COMP_CURR_FLAG AS COMP_CURR_FLAG,
        SALES_CURR_FLAG AS SALES_CURR_FLAG,
        TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        RANKING_CD_SERVICES AS RANKING_CD_SERVICES,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_SERVICES AS RANKING_LEVEL_SERVICES,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        RANKING_CD_MERCH AS RANKING_CD_MERCH,
        RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNR_SERVICES_LKUP_26 
    WHERE
        WEEK_DT >= RANKING_START_DT 
        AND WEEK_DT <= RANKING_END_DT 
        AND RUNNING_SUM_SERVICES_SALES_PCT > RANKING_START_PERCENT 
        AND RUNNING_SUM_SERVICES_SALES_PCT <= RANKING_END_PERCENT""")

df_27.createOrReplaceTempView("FIL_SERVICES_LKUP_27")

# COMMAND ----------

# DBTITLE 1, JNR_SALON_LKUP_28

df_28=spark.sql("""
    SELECT
        MASTER.DUMMY_JOIN1 AS DUMMY_JOIN1,
        MASTER.WEEK_DT AS WEEK_DT,
        MASTER.LOCATION_ID AS LOCATION_ID,
        MASTER.COMP_CURR_FLAG AS COMP_CURR_FLAG,
        MASTER.SALES_CURR_FLAG AS SALES_CURR_FLAG,
        MASTER.TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        MASTER.TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        MASTER.STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        MASTER.RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MASTER.MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MASTER.MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        MASTER.STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        MASTER.RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        MASTER.SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        MASTER.SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        MASTER.STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        MASTER.RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        MASTER.SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        MASTER.SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        MASTER.STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        MASTER.RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        MASTER.TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        MASTER.TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        MASTER.STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        MASTER.RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        MASTER.HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        MASTER.HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        MASTER.STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        MASTER.RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        MASTER.CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        MASTER.CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        MASTER.STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        MASTER.RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        MASTER.HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        MASTER.HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        MASTER.STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        MASTER.RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        MASTER.SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        MASTER.SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        MASTER.STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        MASTER.RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        DETAIL.DUMMY_JOIN AS DUMMY_JOIN,
        DETAIL.RANKING_CD_SALON AS RANKING_CD_SALON,
        DETAIL.RANKING_START_DT AS RANKING_START_DT,
        DETAIL.RANKING_END_DT AS RANKING_END_DT,
        DETAIL.RANKING_LEVEL_SALON AS RANKING_LEVEL_SALON,
        DETAIL.RANKING_START_PERCENT AS RANKING_START_PERCENT,
        DETAIL.RANKING_END_PERCENT AS RANKING_END_PERCENT,
        MASTER.RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        MASTER.RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        MASTER.RANKING_CD_MERCH AS RANKING_CD_MERCH,
        MASTER.RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        MASTER.RANKING_CD_SERVICES AS RANKING_CD_SERVICES1,
        MASTER.RANKING_LEVEL_SERVICES AS RANKING_LEVEL_SERVICES1,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        FIL_SERVICES_LKUP_27 MASTER 
    RIGHT JOIN
        EXP_SALON_LKUP_8 DETAIL 
            ON MASTER.DUMMY_JOIN1 = DETAIL.DUMMY_JOIN""")

df_28.createOrReplaceTempView("JNR_SALON_LKUP_28")

# COMMAND ----------

# DBTITLE 1, FIL_SALON_LKUP_29

df_29=spark.sql("""
    SELECT
        DUMMY_JOIN1 AS DUMMY_JOIN1,
        WEEK_DT AS WEEK_DT,
        LOCATION_ID AS LOCATION_ID,
        COMP_CURR_FLAG AS COMP_CURR_FLAG,
        SALES_CURR_FLAG AS SALES_CURR_FLAG,
        TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        RANKING_CD_SALON AS RANKING_CD_SALON,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_SALON AS RANKING_LEVEL_SALON,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        RANKING_CD_MERCH AS RANKING_CD_MERCH,
        RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        RANKING_CD_SERVICES1 AS RANKING_CD_SERVICES1,
        RANKING_LEVEL_SERVICES1 AS RANKING_LEVEL_SERVICES1,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNR_SALON_LKUP_28 
    WHERE
        WEEK_DT >= RANKING_START_DT 
        AND WEEK_DT <= RANKING_END_DT 
        AND RUNNING_SUM_SALON_SALES_PCT > RANKING_START_PERCENT 
        AND RUNNING_SUM_SALON_SALES_PCT <= RANKING_END_PERCENT""")

df_29.createOrReplaceTempView("FIL_SALON_LKUP_29")

# COMMAND ----------

# DBTITLE 1, JNR_TRAINING_LKUP_30

df_30=spark.sql("""
    SELECT
        MASTER.DUMMY_JOIN1 AS DUMMY_JOIN1,
        MASTER.WEEK_DT AS WEEK_DT,
        MASTER.LOCATION_ID AS LOCATION_ID,
        MASTER.COMP_CURR_FLAG AS COMP_CURR_FLAG,
        MASTER.SALES_CURR_FLAG AS SALES_CURR_FLAG,
        MASTER.TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        MASTER.TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        MASTER.STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        MASTER.RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MASTER.MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MASTER.MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        MASTER.STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        MASTER.RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        MASTER.SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        MASTER.SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        MASTER.STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        MASTER.RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        MASTER.SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        MASTER.SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        MASTER.STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        MASTER.RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        MASTER.TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        MASTER.TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        MASTER.STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        MASTER.RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        MASTER.HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        MASTER.HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        MASTER.STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        MASTER.RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        MASTER.CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        MASTER.CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        MASTER.STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        MASTER.RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        MASTER.HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        MASTER.HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        MASTER.STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        MASTER.RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        MASTER.SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        MASTER.SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        MASTER.STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        MASTER.RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        DETAIL.DUMMY_JOIN AS DUMMY_JOIN,
        DETAIL.RANKING_CD_TRAINING AS RANKING_CD_TRAINING,
        DETAIL.RANKING_START_DT AS RANKING_START_DT,
        DETAIL.RANKING_END_DT AS RANKING_END_DT,
        DETAIL.RANKING_LEVEL_TRAINING AS RANKING_LEVEL_TRAINING,
        DETAIL.RANKING_START_PERCENT AS RANKING_START_PERCENT,
        DETAIL.RANKING_END_PERCENT AS RANKING_END_PERCENT,
        MASTER.RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        MASTER.RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        MASTER.RANKING_CD_MERCH AS RANKING_CD_MERCH,
        MASTER.RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        MASTER.RANKING_CD_SERVICES1 AS RANKING_CD_SERVICES1,
        MASTER.RANKING_LEVEL_SERVICES1 AS RANKING_LEVEL_SERVICES1,
        MASTER.RANKING_CD_SALON AS RANKING_CD_SALON,
        MASTER.RANKING_LEVEL_SALON AS RANKING_LEVEL_SALON,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        FIL_SALON_LKUP_29 MASTER 
    RIGHT JOIN
        EXP_TRAINING_LKUP_18 DETAIL 
            ON MASTER.DUMMY_JOIN1 = DETAIL.DUMMY_JOIN""")

df_30.createOrReplaceTempView("JNR_TRAINING_LKUP_30")

# COMMAND ----------

# DBTITLE 1, FIL_TRAINING_LKUP_31

df_31=spark.sql("""
    SELECT
        DUMMY_JOIN1 AS DUMMY_JOIN1,
        WEEK_DT AS WEEK_DT,
        LOCATION_ID AS LOCATION_ID,
        COMP_CURR_FLAG AS COMP_CURR_FLAG,
        SALES_CURR_FLAG AS SALES_CURR_FLAG,
        TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        RANKING_CD_TRAINING AS RANKING_CD_TRAINING,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_TRAINING AS RANKING_LEVEL_TRAINING,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        RANKING_CD_MERCH AS RANKING_CD_MERCH,
        RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        RANKING_CD_SERVICES1 AS RANKING_CD_SERVICES1,
        RANKING_LEVEL_SERVICES1 AS RANKING_LEVEL_SERVICES1,
        RANKING_CD_SALON AS RANKING_CD_SALON,
        RANKING_LEVEL_SALON1 AS RANKING_LEVEL_SALON1,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNR_TRAINING_LKUP_30 
    WHERE
        WEEK_DT >= RANKING_START_DT 
        AND WEEK_DT <= RANKING_END_DT 
        AND RUNNING_SUM_TRAINING_SALES_PCT > RANKING_START_PERCENT 
        AND RUNNING_SUM_TRAINING_SALES_PCT <= RANKING_END_PERCENT""")

df_31.createOrReplaceTempView("FIL_TRAINING_LKUP_31")

# COMMAND ----------

# DBTITLE 1, JNR_HOTEL_LKUP_32

df_32=spark.sql("""
    SELECT
        MASTER.DUMMY_JOIN1 AS DUMMY_JOIN1,
        MASTER.WEEK_DT AS WEEK_DT,
        MASTER.LOCATION_ID AS LOCATION_ID,
        MASTER.COMP_CURR_FLAG AS COMP_CURR_FLAG,
        MASTER.SALES_CURR_FLAG AS SALES_CURR_FLAG,
        MASTER.TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        MASTER.TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        MASTER.STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        MASTER.RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MASTER.MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MASTER.MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        MASTER.STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        MASTER.RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        MASTER.SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        MASTER.SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        MASTER.STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        MASTER.RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        MASTER.SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        MASTER.SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        MASTER.STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        MASTER.RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        MASTER.TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        MASTER.TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        MASTER.STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        MASTER.RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        MASTER.HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        MASTER.HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        MASTER.STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        MASTER.RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        MASTER.CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        MASTER.CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        MASTER.STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        MASTER.RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        MASTER.HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        MASTER.HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        MASTER.STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        MASTER.RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        MASTER.SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        MASTER.SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        MASTER.STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        MASTER.RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        DETAIL.DUMMY_JOIN AS DUMMY_JOIN,
        DETAIL.RANKING_CD_HOTEL AS RANKING_CD_HOTEL,
        DETAIL.RANKING_START_DT AS RANKING_START_DT,
        DETAIL.RANKING_END_DT AS RANKING_END_DT,
        DETAIL.RANKING_LEVEL_HOTEL AS RANKING_LEVEL_HOTEL,
        DETAIL.RANKING_START_PERCENT AS RANKING_START_PERCENT,
        DETAIL.RANKING_END_PERCENT AS RANKING_END_PERCENT,
        MASTER.RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        MASTER.RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        MASTER.RANKING_CD_MERCH AS RANKING_CD_MERCH,
        MASTER.RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        MASTER.RANKING_CD_SERVICES1 AS RANKING_CD_SERVICES1,
        MASTER.RANKING_LEVEL_SERVICES1 AS RANKING_LEVEL_SERVICES1,
        MASTER.RANKING_CD_SALON AS RANKING_CD_SALON,
        MASTER.RANKING_LEVEL_SALON1 AS RANKING_LEVEL_SALON,
        MASTER.RANKING_CD_TRAINING AS RANKING_CD_TRAINING,
        MASTER.RANKING_LEVEL_TRAINING AS RANKING_LEVEL_TRAINING,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        FIL_TRAINING_LKUP_31 MASTER 
    RIGHT JOIN
        EXP_HOTEL_LKUP_6 DETAIL 
            ON MASTER.DUMMY_JOIN1 = DETAIL.DUMMY_JOIN""")

df_32.createOrReplaceTempView("JNR_HOTEL_LKUP_32")

# COMMAND ----------

# DBTITLE 1, FIL_HOTEL_LKUP_33

df_33=spark.sql("""
    SELECT
        DUMMY_JOIN1 AS DUMMY_JOIN1,
        WEEK_DT AS WEEK_DT,
        LOCATION_ID AS LOCATION_ID,
        COMP_CURR_FLAG AS COMP_CURR_FLAG,
        SALES_CURR_FLAG AS SALES_CURR_FLAG,
        TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        RANKING_CD_HOTEL AS RANKING_CD_HOTEL,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_HOTEL AS RANKING_LEVEL_HOTEL,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        RANKING_CD_MERCH AS RANKING_CD_MERCH,
        RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        RANKING_CD_SERVICES1 AS RANKING_CD_SERVICES1,
        RANKING_LEVEL_SERVICES1 AS RANKING_LEVEL_SERVICES1,
        RANKING_CD_SALON AS RANKING_CD_SALON,
        RANKING_LEVEL_SALON1 AS RANKING_LEVEL_SALON1,
        RANKING_CD_TRAINING AS RANKING_CD_TRAINING,
        RANKING_LEVEL_TRAINING AS RANKING_LEVEL_TRAINING,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNR_HOTEL_LKUP_32 
    WHERE
        WEEK_DT >= RANKING_START_DT 
        AND WEEK_DT <= RANKING_END_DT 
        AND RUNNING_SUM_HOTEL_DDC_SALES_PCT > RANKING_START_PERCENT 
        AND RUNNING_SUM_HOTEL_DDC_SALES_PCT <= RANKING_END_PERCENT""")

df_33.createOrReplaceTempView("FIL_HOTEL_LKUP_33")

# COMMAND ----------

# DBTITLE 1, JNR_CONSUM_LKUP_34

df_34=spark.sql("""
    SELECT
        MASTER.DUMMY_JOIN1 AS DUMMY_JOIN1,
        MASTER.WEEK_DT AS WEEK_DT,
        MASTER.LOCATION_ID AS LOCATION_ID,
        MASTER.COMP_CURR_FLAG AS COMP_CURR_FLAG,
        MASTER.SALES_CURR_FLAG AS SALES_CURR_FLAG,
        MASTER.TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        MASTER.TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        MASTER.STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        MASTER.RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MASTER.MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MASTER.MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        MASTER.STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        MASTER.RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        MASTER.SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        MASTER.SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        MASTER.STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        MASTER.RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        MASTER.SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        MASTER.SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        MASTER.STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        MASTER.RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        MASTER.TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        MASTER.TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        MASTER.STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        MASTER.RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        MASTER.HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        MASTER.HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        MASTER.STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        MASTER.RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        MASTER.CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        MASTER.CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        MASTER.STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        MASTER.RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        MASTER.HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        MASTER.HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        MASTER.STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        MASTER.RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        MASTER.SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        MASTER.SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        MASTER.STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        MASTER.RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        DETAIL.DUMMY_JOIN AS DUMMY_JOIN,
        DETAIL.RANKING_CD_CONSUM AS RANKING_CD_CONSUM,
        DETAIL.RANKING_START_DT AS RANKING_START_DT,
        DETAIL.RANKING_END_DT AS RANKING_END_DT,
        DETAIL.RANKING_LEVEL_CONSUM AS RANKING_LEVEL_CONSUM,
        DETAIL.RANKING_START_PERCENT AS RANKING_START_PERCENT,
        DETAIL.RANKING_END_PERCENT AS RANKING_END_PERCENT,
        MASTER.RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        MASTER.RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        MASTER.RANKING_CD_MERCH AS RANKING_CD_MERCH,
        MASTER.RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        MASTER.RANKING_CD_SERVICES1 AS RANKING_CD_SERVICES1,
        MASTER.RANKING_LEVEL_SERVICES1 AS RANKING_LEVEL_SERVICES1,
        MASTER.RANKING_CD_SALON AS RANKING_CD_SALON,
        MASTER.RANKING_LEVEL_SALON1 AS RANKING_LEVEL_SALON,
        MASTER.RANKING_CD_TRAINING AS RANKING_CD_TRAINING,
        MASTER.RANKING_LEVEL_TRAINING AS RANKING_LEVEL_TRAINING,
        MASTER.RANKING_CD_HOTEL AS RANKING_CD_HOTEL,
        MASTER.RANKING_LEVEL_HOTEL AS RANKING_LEVEL_HOTEL,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        FIL_HOTEL_LKUP_33 MASTER 
    RIGHT JOIN
        EXP_CONSUM_LKUP_10 DETAIL 
            ON MASTER.DUMMY_JOIN1 = DETAIL.DUMMY_JOIN""")

df_34.createOrReplaceTempView("JNR_CONSUM_LKUP_34")

# COMMAND ----------

# DBTITLE 1, FIL_CONSUM_LKUP_35

df_35=spark.sql("""
    SELECT
        DUMMY_JOIN1 AS DUMMY_JOIN1,
        WEEK_DT AS WEEK_DT,
        LOCATION_ID AS LOCATION_ID,
        COMP_CURR_FLAG AS COMP_CURR_FLAG,
        SALES_CURR_FLAG AS SALES_CURR_FLAG,
        TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        RANKING_CD_CONSUM AS RANKING_CD_CONSUM,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_CONSUM AS RANKING_LEVEL_CONSUM,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        RANKING_CD_MERCH AS RANKING_CD_MERCH,
        RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        RANKING_CD_SERVICES1 AS RANKING_CD_SERVICES1,
        RANKING_LEVEL_SERVICES1 AS RANKING_LEVEL_SERVICES1,
        RANKING_CD_SALON AS RANKING_CD_SALON,
        RANKING_LEVEL_SALON1 AS RANKING_LEVEL_SALON1,
        RANKING_CD_TRAINING AS RANKING_CD_TRAINING,
        RANKING_LEVEL_TRAINING AS RANKING_LEVEL_TRAINING,
        RANKING_CD_HOTEL AS RANKING_CD_HOTEL,
        RANKING_LEVEL_HOTEL AS RANKING_LEVEL_HOTEL,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNR_CONSUM_LKUP_34 
    WHERE
        WEEK_DT >= RANKING_START_DT 
        AND WEEK_DT <= RANKING_END_DT 
        AND RUNNING_SUM_CONSUMABLES_SALES_PCT > RANKING_START_PERCENT 
        AND RUNNING_SUM_CONSUMABLES_SALES_PCT <= RANKING_END_PERCENT""")

df_35.createOrReplaceTempView("FIL_CONSUM_LKUP_35")

# COMMAND ----------

# DBTITLE 1, JNR_HGOODS_LKUP_36

df_36=spark.sql("""
    SELECT
        MASTER.DUMMY_JOIN1 AS DUMMY_JOIN1,
        MASTER.WEEK_DT AS WEEK_DT,
        MASTER.LOCATION_ID AS LOCATION_ID,
        MASTER.COMP_CURR_FLAG AS COMP_CURR_FLAG,
        MASTER.SALES_CURR_FLAG AS SALES_CURR_FLAG,
        MASTER.TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        MASTER.TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        MASTER.STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        MASTER.RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MASTER.MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MASTER.MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        MASTER.STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        MASTER.RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        MASTER.SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        MASTER.SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        MASTER.STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        MASTER.RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        MASTER.SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        MASTER.SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        MASTER.STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        MASTER.RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        MASTER.TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        MASTER.TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        MASTER.STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        MASTER.RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        MASTER.HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        MASTER.HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        MASTER.STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        MASTER.RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        MASTER.CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        MASTER.CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        MASTER.STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        MASTER.RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        MASTER.HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        MASTER.HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        MASTER.STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        MASTER.RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        MASTER.SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        MASTER.SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        MASTER.STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        MASTER.RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        DETAIL.DUMMY_JOIN AS DUMMY_JOIN,
        DETAIL.RANKING_CD_HGOODS AS RANKING_CD_HGOODS,
        DETAIL.RANKING_START_DT AS RANKING_START_DT,
        DETAIL.RANKING_END_DT AS RANKING_END_DT,
        DETAIL.RANKING_LEVEL_HGOODS AS RANKING_LEVEL_HGOODS,
        DETAIL.RANKING_START_PERCENT AS RANKING_START_PERCENT,
        DETAIL.RANKING_END_PERCENT AS RANKING_END_PERCENT,
        MASTER.RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        MASTER.RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        MASTER.RANKING_CD_MERCH AS RANKING_CD_MERCH,
        MASTER.RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        MASTER.RANKING_CD_SERVICES1 AS RANKING_CD_SERVICES1,
        MASTER.RANKING_LEVEL_SERVICES1 AS RANKING_LEVEL_SERVICES1,
        MASTER.RANKING_CD_SALON AS RANKING_CD_SALON,
        MASTER.RANKING_LEVEL_SALON1 AS RANKING_LEVEL_SALON,
        MASTER.RANKING_CD_TRAINING AS RANKING_CD_TRAINING,
        MASTER.RANKING_LEVEL_TRAINING AS RANKING_LEVEL_TRAINING,
        MASTER.RANKING_CD_HOTEL AS RANKING_CD_HOTEL,
        MASTER.RANKING_LEVEL_HOTEL AS RANKING_LEVEL_HOTEL,
        MASTER.RANKING_CD_CONSUM AS RANKING_CD_CONSUM,
        MASTER.RANKING_LEVEL_CONSUM AS RANKING_LEVEL_CONSUM,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        FIL_CONSUM_LKUP_35 MASTER 
    RIGHT JOIN
        EXP_HGOODS_LKUP_12 DETAIL 
            ON MASTER.DUMMY_JOIN1 = DETAIL.DUMMY_JOIN""")

df_36.createOrReplaceTempView("JNR_HGOODS_LKUP_36")

# COMMAND ----------

# DBTITLE 1, FIL_HGOODS_LKUP_37

df_37=spark.sql("""
    SELECT
        DUMMY_JOIN1 AS DUMMY_JOIN1,
        WEEK_DT AS WEEK_DT,
        LOCATION_ID AS LOCATION_ID,
        COMP_CURR_FLAG AS COMP_CURR_FLAG,
        SALES_CURR_FLAG AS SALES_CURR_FLAG,
        TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        RANKING_CD_HGOODS AS RANKING_CD_HGOODS,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_LEVEL_HGOODS AS RANKING_LEVEL_HGOODS,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        RANKING_CD_MERCH AS RANKING_CD_MERCH,
        RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        RANKING_CD_SERVICES1 AS RANKING_CD_SERVICES1,
        RANKING_LEVEL_SERVICES1 AS RANKING_LEVEL_SERVICES1,
        RANKING_CD_SALON AS RANKING_CD_SALON,
        RANKING_LEVEL_SALON1 AS RANKING_LEVEL_SALON1,
        RANKING_CD_TRAINING AS RANKING_CD_TRAINING,
        RANKING_LEVEL_TRAINING AS RANKING_LEVEL_TRAINING,
        RANKING_CD_HOTEL AS RANKING_CD_HOTEL,
        RANKING_LEVEL_HOTEL AS RANKING_LEVEL_HOTEL,
        RANKING_CD_CONSUM AS RANKING_CD_CONSUM,
        RANKING_LEVEL_CONSUM AS RANKING_LEVEL_CONSUM,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNR_HGOODS_LKUP_36 
    WHERE
        WEEK_DT >= RANKING_START_DT 
        AND WEEK_DT <= RANKING_END_DT 
        AND RUNNING_SUM_HARDGOODS_SALES_PCT > RANKING_START_PERCENT 
        AND RUNNING_SUM_HARDGOODS_SALES_PCT <= RANKING_END_PERCENT""")

df_37.createOrReplaceTempView("FIL_HGOODS_LKUP_37")

# COMMAND ----------

# DBTITLE 1, JNR_SPECIALTY_LKUP_38

df_38=spark.sql("""
    SELECT
        MASTER.DUMMY_JOIN1 AS DUMMY_JOIN1,
        MASTER.WEEK_DT AS WEEK_DT,
        MASTER.LOCATION_ID AS LOCATION_ID,
        MASTER.COMP_CURR_FLAG AS COMP_CURR_FLAG,
        MASTER.SALES_CURR_FLAG AS SALES_CURR_FLAG,
        MASTER.TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        MASTER.TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        MASTER.STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        MASTER.RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        MASTER.MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MASTER.MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        MASTER.STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        MASTER.RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        MASTER.SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        MASTER.SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        MASTER.STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        MASTER.RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        MASTER.SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        MASTER.SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        MASTER.STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        MASTER.RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        MASTER.TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        MASTER.TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        MASTER.STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        MASTER.RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        MASTER.HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        MASTER.HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        MASTER.STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        MASTER.RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        MASTER.CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        MASTER.CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        MASTER.STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        MASTER.RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        MASTER.HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        MASTER.HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        MASTER.STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        MASTER.RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        MASTER.SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        MASTER.SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        MASTER.STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        MASTER.RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        MASTER.RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        MASTER.RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        MASTER.RANKING_CD_MERCH AS RANKING_CD_MERCH,
        MASTER.RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        MASTER.RANKING_CD_SERVICES1 AS RANKING_CD_SERVICES1,
        MASTER.RANKING_LEVEL_SERVICES1 AS RANKING_LEVEL_SERVICES1,
        MASTER.RANKING_CD_SALON AS RANKING_CD_SALON,
        MASTER.RANKING_LEVEL_SALON1 AS RANKING_LEVEL_SALON,
        MASTER.RANKING_CD_TRAINING AS RANKING_CD_TRAINING,
        MASTER.RANKING_LEVEL_TRAINING AS RANKING_LEVEL_TRAINING,
        MASTER.RANKING_CD_HOTEL AS RANKING_CD_HOTEL,
        MASTER.RANKING_LEVEL_HOTEL AS RANKING_LEVEL_HOTEL,
        MASTER.RANKING_CD_CONSUM AS RANKING_CD_CONSUM,
        MASTER.RANKING_LEVEL_CONSUM AS RANKING_LEVEL_CONSUM,
        MASTER.RANKING_CD_HGOODS AS RANKING_CD_HGOODS,
        MASTER.RANKING_LEVEL_HGOODS AS RANKING_LEVEL_HGOODS,
        DETAIL.DUMMY_JOIN AS DUMMY_JOIN,
        DETAIL.RANKING_CD_SPECIALTY AS RANKING_CD_SPECIALTY,
        DETAIL.RANKING_START_DT AS RANKING_START_DT,
        DETAIL.RANKING_END_DT AS RANKING_END_DT,
        DETAIL.RANKING_LEVEL_SPECIALTY AS RANKING_LEVEL_SPECIALTY,
        DETAIL.RANKING_START_PERCENT AS RANKING_START_PERCENT,
        DETAIL.RANKING_END_PERCENT AS RANKING_END_PERCENT,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        FIL_HGOODS_LKUP_37 MASTER 
    RIGHT JOIN
        EXP_SPECIALTY_LKUP_14 DETAIL 
            ON MASTER.DUMMY_JOIN1 = DETAIL.DUMMY_JOIN""")

df_38.createOrReplaceTempView("JNR_SPECIALTY_LKUP_38")

# COMMAND ----------

# DBTITLE 1, FIL_SPECIALTY_LKUP_39

df_39=spark.sql("""
    SELECT
        DUMMY_JOIN1 AS DUMMY_JOIN1,
        WEEK_DT AS WEEK_DT,
        LOCATION_ID AS LOCATION_ID,
        COMP_CURR_FLAG AS COMP_CURR_FLAG,
        SALES_CURR_FLAG AS SALES_CURR_FLAG,
        TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
        TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
        STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
        RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
        RANKING_CD_TOTAL AS RANKING_CD_TOTAL,
        RANKING_LEVEL_TOTAL AS RANKING_LEVEL_TOTAL,
        MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
        MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
        STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
        RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
        RANKING_CD_MERCH AS RANKING_CD_MERCH,
        RANKING_LEVEL_MERCH AS RANKING_LEVEL_MERCH,
        SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
        SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
        STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
        RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
        RANKING_CD_SERVICES1 AS RANKING_CD_SERVICES1,
        RANKING_LEVEL_SERVICES1 AS RANKING_LEVEL_SERVICES1,
        SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
        SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
        STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
        RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
        RANKING_CD_SALON AS RANKING_CD_SALON,
        RANKING_LEVEL_SALON1 AS RANKING_LEVEL_SALON1,
        TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
        TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
        STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
        RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
        RANKING_CD_TRAINING AS RANKING_CD_TRAINING,
        RANKING_LEVEL_TRAINING AS RANKING_LEVEL_TRAINING,
        HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
        HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
        STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
        RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
        RANKING_CD_HOTEL AS RANKING_CD_HOTEL,
        RANKING_LEVEL_HOTEL AS RANKING_LEVEL_HOTEL,
        CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
        CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
        STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
        RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
        RANKING_CD_CONSUM AS RANKING_CD_CONSUM,
        RANKING_LEVEL_CONSUM AS RANKING_LEVEL_CONSUM,
        HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
        HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
        STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
        RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
        RANKING_CD_HGOODS AS RANKING_CD_HGOODS,
        RANKING_LEVEL_HGOODS AS RANKING_LEVEL_HGOODS,
        SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
        SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
        STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
        RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
        RANKING_CD_SPECIALTY AS RANKING_CD_SPECIALTY,
        RANKING_LEVEL_SPECIALTY AS RANKING_LEVEL_SPECIALTY,
        RANKING_START_DT AS RANKING_START_DT,
        RANKING_END_DT AS RANKING_END_DT,
        RANKING_START_PERCENT AS RANKING_START_PERCENT,
        RANKING_END_PERCENT AS RANKING_END_PERCENT,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNR_SPECIALTY_LKUP_38 
    WHERE
        WEEK_DT >= RANKING_START_DT 
        AND WEEK_DT <= RANKING_END_DT 
        AND RUNNING_SUM_SPECIALTY_SALES_PCT > RANKING_START_PERCENT 
        AND RUNNING_SUM_SPECIALTY_SALES_PCT <= RANKING_END_PERCENT""")

df_39.createOrReplaceTempView("FIL_SPECIALTY_LKUP_39")

# COMMAND ----------

# DBTITLE 1, SALES_RANKING_WK_PRE

spark.sql("""INSERT INTO SALES_RANKING_WK_PRE SELECT WEEK_DT AS WEEK_DT,
LOCATION_ID AS LOCATION_ID,
COMP_CURR_FLAG AS COMP_CURR_FLAG,
SALES_CURR_FLAG AS SALES_CURR_FLAG,
TOTAL_52WK_SALES_AMT AS TOTAL_52WK_SALES_AMT,
TOTAL_52WK_COMP_STORES_AMT AS TOTAL_52WK_COMP_STORES_AMT,
STORE_TOTAL_SALES_PCT AS STORE_TOTAL_SALES_PCT,
RUNNING_SUM_TOTAL_SALES_PCT AS RUNNING_SUM_TOTAL_SALES_PCT,
RANKING_CD_TOTAL AS TOTAL_SALES_RANKING_CD,
RANKING_LEVEL_TOTAL AS TOTAL_SALES_RANKING_LEVEL,
MERCH_52WK_SALES_AMT AS MERCH_52WK_SALES_AMT,
MERCH_52WK_COMP_STORES_AMT AS MERCH_52WK_COMP_STORES_AMT,
STORE_MERCH_SALES_PCT AS STORE_MERCH_SALES_PCT,
RUNNING_SUM_MERCH_SALES_PCT AS RUNNING_SUM_MERCH_SALES_PCT,
RANKING_CD_MERCH AS MERCH_SALES_RANKING_CD,
RANKING_LEVEL_MERCH AS MERCH_SALES_RANKING_LEVEL,
SERVICES_52WK_SALES_AMT AS SERVICES_52WK_SALES_AMT,
SERVICES_52WK_COMP_STORES_AMT AS SERVICES_52WK_COMP_STORES_AMT,
STORE_SERVICES_SALES_PCT AS STORE_SERVICES_SALES_PCT,
RUNNING_SUM_SERVICES_SALES_PCT AS RUNNING_SUM_SERVICES_SALES_PCT,
RANKING_CD_SERVICES1 AS SERVICES_SALES_RANKING_CD,
RANKING_LEVEL_SERVICES1 AS SERVICES_SALES_RANKING_LEVEL,
SALON_52WK_SALES_AMT AS SALON_52WK_SALES_AMT,
SALON_52WK_COMP_STORES_AMT AS SALON_52WK_COMP_STORES_AMT,
STORE_SALON_SALES_PCT AS STORE_SALON_SALES_PCT,
RUNNING_SUM_SALON_SALES_PCT AS RUNNING_SUM_SALON_SALES_PCT,
RANKING_CD_SALON AS SALON_SALES_RANKING_CD,
RANKING_LEVEL_SALON1 AS SALON_SALES_RANKING_LEVEL,
TRAINING_52WK_SALES_AMT AS TRAINING_52WK_SALES_AMT,
TRAINING_52WK_COMP_STORES_AMT AS TRAINING_52WK_COMP_STORES_AMT,
STORE_TRAINING_SALES_PCT AS STORE_TRAINING_SALES_PCT,
RUNNING_SUM_TRAINING_SALES_PCT AS RUNNING_SUM_TRAINING_SALES_PCT,
RANKING_CD_TRAINING AS TRAINING_SALES_RANKING_CD,
RANKING_LEVEL_TRAINING AS TRAINING_SALES_RANKING_LEVEL,
HOTEL_DDC_52WK_SALES_AMT AS HOTEL_DDC_52WK_SALES_AMT,
HOTEL_DDC_52WK_COMP_STORES_AMT AS HOTEL_DDC_52WK_COMP_STORES_AMT,
STORE_HOTEL_DDC_SALES_PCT AS STORE_HOTEL_DDC_SALES_PCT,
RUNNING_SUM_HOTEL_DDC_SALES_PCT AS RUNNING_SUM_HOTEL_DDC_SALES_PCT,
RANKING_CD_HOTEL AS HOTEL_DDC_SALES_RANKING_CD,
RANKING_LEVEL_HOTEL AS HOTEL_DDC_SALES_RANKING_LEVEL,
CONSUMABLES_52WK_SALES_AMT AS CONSUMABLES_52WK_SALES_AMT,
CONSUMABLES_52WK_COMP_STORES_AMT AS CONSUMABLES_52WK_COMP_STORES_AMT,
STORE_CONSUMABLES_SALES_PCT AS STORE_CONSUMABLES_SALES_PCT,
RUNNING_SUM_CONSUMABLES_SALES_PCT AS RUNNING_SUM_CONSUMABLES_SALES_PCT,
RANKING_CD_CONSUM AS CONSUMABLES_SALES_RANKING_CD,
RANKING_LEVEL_CONSUM AS CONSUMABLES_SALES_RANKING_LEVEL,
HARDGOODS_52WK_SALES_AMT AS HARDGOODS_52WK_SALES_AMT,
HARDGOODS_52WK_COMP_STORES_AMT AS HARDGOODS_52WK_COMP_STORES_AMT,
STORE_HARDGOODS_SALES_PCT AS STORE_HARDGOODS_SALES_PCT,
RUNNING_SUM_HARDGOODS_SALES_PCT AS RUNNING_SUM_HARDGOODS_SALES_PCT,
RANKING_CD_HGOODS AS HARDGOODS_SALES_RANKING_CD,
RANKING_LEVEL_HGOODS AS HARDGOODS_SALES_RANKING_LEVEL,
SPECIALTY_52WK_SALES_AMT AS SPECIALTY_52WK_SALES_AMT,
SPECIALTY_52WK_COMP_STORES_AMT AS SPECIALTY_52WK_COMP_STORES_AMT,
STORE_SPECIALTY_SALES_PCT AS STORE_SPECIALTY_SALES_PCT,
RUNNING_SUM_SPECIALTY_SALES_PCT AS RUNNING_SUM_SPECIALTY_SALES_PCT,
RANKING_CD_SPECIALTY AS SPECIALTY_SALES_RANKING_CD,
RANKING_LEVEL_SPECIALTY AS SPECIALTY_SALES_RANKING_LEVEL FROM FIL_SPECIALTY_LKUP_39""")
