# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")


# COMMAND ----------
# DBTITLE 1, EMPLOYEE_PROFILE_0


df_0=spark.sql("""
    SELECT
        EMPLOYEE_ID AS EMPLOYEE_ID,
        EMPL_FIRST_NAME AS EMPL_FIRST_NAME,
        EMPL_MIDDLE_NAME AS EMPL_MIDDLE_NAME,
        EMPL_LAST_NAME AS EMPL_LAST_NAME,
        EMPL_BIRTH_DT AS EMPL_BIRTH_DT,
        GENDER_CD AS GENDER_CD,
        PS_MARITAL_STATUS_CD AS PS_MARITAL_STATUS_CD,
        ETHNIC_GROUP_ID AS ETHNIC_GROUP_ID,
        EMPL_ADDR_1 AS EMPL_ADDR_1,
        EMPL_ADDR_2 AS EMPL_ADDR_2,
        EMPL_CITY AS EMPL_CITY,
        EMPL_STATE AS EMPL_STATE,
        EMPL_PROVINCE AS EMPL_PROVINCE,
        EMPL_ZIPCODE AS EMPL_ZIPCODE,
        COUNTRY_CD AS COUNTRY_CD,
        EMPL_HOME_PHONE AS EMPL_HOME_PHONE,
        EMPL_EMAIL_ADDR AS EMPL_EMAIL_ADDR,
        EMPL_LOGIN_ID AS EMPL_LOGIN_ID,
        BADGE_NBR AS BADGE_NBR,
        EMPL_STATUS_CD AS EMPL_STATUS_CD,
        STATUS_CHG_DT AS STATUS_CHG_DT,
        FULLPT_FLAG AS FULLPT_FLAG,
        FULLPT_CHG_DT AS FULLPT_CHG_DT,
        EMPL_TYPE_CD AS EMPL_TYPE_CD,
        PS_REG_TEMP_CD AS PS_REG_TEMP_CD,
        EMPL_CATEGORY_CD AS EMPL_CATEGORY_CD,
        EMPL_GROUP_CD AS EMPL_GROUP_CD,
        EMPL_SUBGROUP_CD AS EMPL_SUBGROUP_CD,
        EMPL_HIRE_DT AS EMPL_HIRE_DT,
        EMPL_REHIRE_DT AS EMPL_REHIRE_DT,
        EMPL_TERM_DT AS EMPL_TERM_DT,
        TERM_REASON_CD AS TERM_REASON_CD,
        EMPL_SENORITY_DT AS EMPL_SENORITY_DT,
        PS_ACTION_DT AS PS_ACTION_DT,
        PS_ACTION_CD AS PS_ACTION_CD,
        PS_ACTION_REASON_CD AS PS_ACTION_REASON_CD,
        LOCATION_ID AS LOCATION_ID,
        LOCATION_CHG_DT AS LOCATION_CHG_DT,
        STORE_NBR AS STORE_NBR,
        STORE_DEPT_NBR AS STORE_DEPT_NBR,
        COMPANY_ID AS COMPANY_ID,
        PS_PERSONNEL_AREA_ID AS PS_PERSONNEL_AREA_ID,
        PS_PERSONNEL_SUBAREA_ID AS PS_PERSONNEL_SUBAREA_ID,
        PS_DEPT_CD AS PS_DEPT_CD,
        PS_DEPT_CHG_DT AS PS_DEPT_CHG_DT,
        PS_POSITION_ID AS PS_POSITION_ID,
        POSITION_CHG_DT AS POSITION_CHG_DT,
        PS_SUPERVISOR_ID AS PS_SUPERVISOR_ID,
        JOB_CODE AS JOB_CODE,
        JOB_CODE_CHG_DT AS JOB_CODE_CHG_DT,
        EMPL_JOB_ENTRY_DT AS EMPL_JOB_ENTRY_DT,
        PS_GRADE_ID AS PS_GRADE_ID,
        EMPL_STD_BONUS_PCT AS EMPL_STD_BONUS_PCT,
        EMPL_OVR_BONUS_PCT AS EMPL_OVR_BONUS_PCT,
        EMPL_RATING AS EMPL_RATING,
        PAY_RATE_CHG_DT AS PAY_RATE_CHG_DT,
        PS_PAYROLL_AREA_CD AS PS_PAYROLL_AREA_CD,
        PS_TAX_COMPANY_CD AS PS_TAX_COMPANY_CD,
        PS_COMP_FREQ_CD AS PS_COMP_FREQ_CD,
        COMP_RATE_AMT AS COMP_RATE_AMT,
        ANNUAL_RATE_LOC_AMT AS ANNUAL_RATE_LOC_AMT,
        HOURLY_RATE_LOC_AMT AS HOURLY_RATE_LOC_AMT,
        CURRENCY_ID AS CURRENCY_ID,
        EXCH_RATE_PCT AS EXCH_RATE_PCT,
        LOAD_TSTMP AS LOAD_TSTMP,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        EMPLOYEE_PROFILE""")

df_0.createOrReplaceTempView("EMPLOYEE_PROFILE_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_EMPLOYEE_PROFILE_1


df_1=spark.sql("""
    SELECT
        EMPLOYEE_ID AS EMPLOYEE_ID,
        EMPL_FIRST_NAME AS EMPL_FIRST_NAME,
        EMPL_LAST_NAME AS EMPL_LAST_NAME,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        EMPLOYEE_PROFILE_0 
    WHERE
        EMPL_STATUS_CD <> 'T'""")

df_1.createOrReplaceTempView("SQ_Shortcut_to_EMPLOYEE_PROFILE_1")

# COMMAND ----------
# DBTITLE 1, SITE_PROFILE_2


df_2=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
        STORE_NBR AS STORE_NBR,
        STORE_NAME AS STORE_NAME,
        STORE_TYPE_ID AS STORE_TYPE_ID,
        STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
        COMPANY_ID AS COMPANY_ID,
        REGION_ID AS REGION_ID,
        DISTRICT_ID AS DISTRICT_ID,
        PRICE_ZONE_ID AS PRICE_ZONE_ID,
        PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
        REPL_DC_NBR AS REPL_DC_NBR,
        REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
        REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
        SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
        SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
        SITE_ADDRESS AS SITE_ADDRESS,
        SITE_CITY AS SITE_CITY,
        STATE_CD AS STATE_CD,
        COUNTRY_CD AS COUNTRY_CD,
        POSTAL_CD AS POSTAL_CD,
        SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
        SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
        SITE_EMAIL_ADDRESS AS SITE_EMAIL_ADDRESS,
        SITE_SALES_FLAG AS SITE_SALES_FLAG,
        EQUINE_MERCH_ID AS EQUINE_MERCH_ID,
        EQUINE_SITE_ID AS EQUINE_SITE_ID,
        EQUINE_SITE_OPEN_DT AS EQUINE_SITE_OPEN_DT,
        GEO_LATITUDE_NBR AS GEO_LATITUDE_NBR,
        GEO_LONGITUDE_NBR AS GEO_LONGITUDE_NBR,
        PETSMART_DMA_CD AS PETSMART_DMA_CD,
        LOYALTY_PGM_TYPE_ID AS LOYALTY_PGM_TYPE_ID,
        LOYALTY_PGM_STATUS_ID AS LOYALTY_PGM_STATUS_ID,
        LOYALTY_PGM_START_DT AS LOYALTY_PGM_START_DT,
        LOYALTY_PGM_CHANGE_DT AS LOYALTY_PGM_CHANGE_DT,
        BP_COMPANY_NBR AS BP_COMPANY_NBR,
        BP_GL_ACCT AS BP_GL_ACCT,
        TP_LOC_FLAG AS TP_LOC_FLAG,
        TP_ACTIVE_CNT AS TP_ACTIVE_CNT,
        PROMO_LABEL_CD AS PROMO_LABEL_CD,
        PARENT_LOCATION_ID AS PARENT_LOCATION_ID,
        LOCATION_NBR AS LOCATION_NBR,
        TIME_ZONE_ID AS TIME_ZONE_ID,
        DELV_SERVICE_CLASS_ID AS DELV_SERVICE_CLASS_ID,
        PICK_SERVICE_CLASS_ID AS PICK_SERVICE_CLASS_ID,
        SITE_LOGIN_ID AS SITE_LOGIN_ID,
        SITE_MANAGER_ID AS SITE_MANAGER_ID,
        SITE_OPEN_YRS_AMT AS SITE_OPEN_YRS_AMT,
        HOTEL_FLAG AS HOTEL_FLAG,
        DAYCAMP_FLAG AS DAYCAMP_FLAG,
        VET_FLAG AS VET_FLAG,
        DIST_MGR_NAME AS DIST_MGR_NAME,
        DIST_SVC_MGR_NAME AS DIST_SVC_MGR_NAME,
        REGION_VP_NAME AS REGION_VP_NAME,
        REGION_TRAINER_NAME AS REGION_TRAINER_NAME,
        ASSET_PROTECT_NAME AS ASSET_PROTECT_NAME,
        SITE_COUNTY AS SITE_COUNTY,
        SITE_FAX_NO AS SITE_FAX_NO,
        SFT_OPEN_DT AS SFT_OPEN_DT,
        DM_EMAIL_ADDRESS AS DM_EMAIL_ADDRESS,
        DSM_EMAIL_ADDRESS AS DSM_EMAIL_ADDRESS,
        RVP_EMAIL_ADDRESS AS RVP_EMAIL_ADDRESS,
        TRADE_AREA AS TRADE_AREA,
        FDLPS_NAME AS FDLPS_NAME,
        FDLPS_EMAIL AS FDLPS_EMAIL,
        OVERSITE_MGR_NAME AS OVERSITE_MGR_NAME,
        OVERSITE_MGR_EMAIL AS OVERSITE_MGR_EMAIL,
        SAFETY_DIRECTOR_NAME AS SAFETY_DIRECTOR_NAME,
        SAFETY_DIRECTOR_EMAIL AS SAFETY_DIRECTOR_EMAIL,
        RETAIL_MANAGER_SAFETY_NAME AS RETAIL_MANAGER_SAFETY_NAME,
        RETAIL_MANAGER_SAFETY_EMAIL AS RETAIL_MANAGER_SAFETY_EMAIL,
        AREA_DIRECTOR_NAME AS AREA_DIRECTOR_NAME,
        AREA_DIRECTOR_EMAIL AS AREA_DIRECTOR_EMAIL,
        DC_GENERAL_MANAGER_NAME AS DC_GENERAL_MANAGER_NAME,
        DC_GENERAL_MANAGER_EMAIL AS DC_GENERAL_MANAGER_EMAIL,
        ASST_DC_GENERAL_MANAGER_NAME1 AS ASST_DC_GENERAL_MANAGER_NAME1,
        ASST_DC_GENERAL_MANAGER_EMAIL1 AS ASST_DC_GENERAL_MANAGER_EMAIL1,
        ASST_DC_GENERAL_MANAGER_NAME2 AS ASST_DC_GENERAL_MANAGER_NAME2,
        ASST_DC_GENERAL_MANAGER_EMAIL2 AS ASST_DC_GENERAL_MANAGER_EMAIL2,
        REGIONAL_DC_SAFETY_MGR_NAME AS REGIONAL_DC_SAFETY_MGR_NAME,
        REGIONAL_DC_SAFETY_MGR_EMAIL AS REGIONAL_DC_SAFETY_MGR_EMAIL,
        DC_PEOPLE_SUPERVISOR_NAME AS DC_PEOPLE_SUPERVISOR_NAME,
        DC_PEOPLE_SUPERVISOR_EMAIL AS DC_PEOPLE_SUPERVISOR_EMAIL,
        PEOPLE_MANAGER_NAME AS PEOPLE_MANAGER_NAME,
        PEOPLE_MANAGER_EMAIL AS PEOPLE_MANAGER_EMAIL,
        ASSET_PROT_DIR_NAME AS ASSET_PROT_DIR_NAME,
        ASSET_PROT_DIR_EMAIL AS ASSET_PROT_DIR_EMAIL,
        SR_REG_ASSET_PROT_MGR_NAME AS SR_REG_ASSET_PROT_MGR_NAME,
        SR_REG_ASSET_PROT_MGR_EMAIL AS SR_REG_ASSET_PROT_MGR_EMAIL,
        REG_ASSET_PROT_MGR_NAME AS REG_ASSET_PROT_MGR_NAME,
        REG_ASSET_PROT_MGR_EMAIL AS REG_ASSET_PROT_MGR_EMAIL,
        ASSET_PROTECT_EMAIL AS ASSET_PROTECT_EMAIL,
        TP_START_DT AS TP_START_DT,
        OPEN_DT AS OPEN_DT,
        GR_OPEN_DT AS GR_OPEN_DT,
        CLOSE_DT AS CLOSE_DT,
        HOTEL_OPEN_DT AS HOTEL_OPEN_DT,
        ADD_DT AS ADD_DT,
        DELETE_DT AS DELETE_DT,
        UPDATE_DT AS UPDATE_DT,
        LOAD_DT AS LOAD_DT,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        SITE_PROFILE""")

df_2.createOrReplaceTempView("SITE_PROFILE_2")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_SITE_PROFILE_3


df_3=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
        STORE_NBR AS STORE_NBR,
        STORE_NAME AS STORE_NAME,
        STORE_TYPE_ID AS STORE_TYPE_ID,
        STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
        COMPANY_ID AS COMPANY_ID,
        REGION_ID AS REGION_ID,
        DISTRICT_ID AS DISTRICT_ID,
        PRICE_ZONE_ID AS PRICE_ZONE_ID,
        PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
        REPL_DC_NBR AS REPL_DC_NBR,
        REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
        REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
        SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
        SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
        SITE_ADDRESS AS SITE_ADDRESS,
        SITE_CITY AS SITE_CITY,
        STATE_CD AS STATE_CD,
        COUNTRY_CD AS COUNTRY_CD,
        POSTAL_CD AS POSTAL_CD,
        SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
        SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
        SITE_EMAIL_ADDRESS AS SITE_EMAIL_ADDRESS,
        SITE_SALES_FLAG AS SITE_SALES_FLAG,
        EQUINE_MERCH_ID AS EQUINE_MERCH_ID,
        EQUINE_SITE_ID AS EQUINE_SITE_ID,
        EQUINE_SITE_OPEN_DT AS EQUINE_SITE_OPEN_DT,
        GEO_LATITUDE_NBR AS GEO_LATITUDE_NBR,
        GEO_LONGITUDE_NBR AS GEO_LONGITUDE_NBR,
        PETSMART_DMA_CD AS PETSMART_DMA_CD,
        LOYALTY_PGM_TYPE_ID AS LOYALTY_PGM_TYPE_ID,
        LOYALTY_PGM_STATUS_ID AS LOYALTY_PGM_STATUS_ID,
        LOYALTY_PGM_START_DT AS LOYALTY_PGM_START_DT,
        LOYALTY_PGM_CHANGE_DT AS LOYALTY_PGM_CHANGE_DT,
        BP_COMPANY_NBR AS BP_COMPANY_NBR,
        BP_GL_ACCT AS BP_GL_ACCT,
        TP_LOC_FLAG AS TP_LOC_FLAG,
        TP_ACTIVE_CNT AS TP_ACTIVE_CNT,
        PROMO_LABEL_CD AS PROMO_LABEL_CD,
        PARENT_LOCATION_ID AS PARENT_LOCATION_ID,
        LOCATION_NBR AS LOCATION_NBR,
        TIME_ZONE_ID AS TIME_ZONE_ID,
        DELV_SERVICE_CLASS_ID AS DELV_SERVICE_CLASS_ID,
        PICK_SERVICE_CLASS_ID AS PICK_SERVICE_CLASS_ID,
        SITE_LOGIN_ID AS SITE_LOGIN_ID,
        SITE_MANAGER_ID AS SITE_MANAGER_ID,
        SITE_OPEN_YRS_AMT AS SITE_OPEN_YRS_AMT,
        HOTEL_FLAG AS HOTEL_FLAG,
        DAYCAMP_FLAG AS DAYCAMP_FLAG,
        VET_FLAG AS VET_FLAG,
        DIST_MGR_NAME AS DIST_MGR_NAME,
        DIST_SVC_MGR_NAME AS DIST_SVC_MGR_NAME,
        REGION_VP_NAME AS REGION_VP_NAME,
        REGION_TRAINER_NAME AS REGION_TRAINER_NAME,
        ASSET_PROTECT_NAME AS ASSET_PROTECT_NAME,
        SITE_COUNTY AS SITE_COUNTY,
        SITE_FAX_NO AS SITE_FAX_NO,
        SFT_OPEN_DT AS SFT_OPEN_DT,
        DM_EMAIL_ADDRESS AS DM_EMAIL_ADDRESS,
        DSM_EMAIL_ADDRESS AS DSM_EMAIL_ADDRESS,
        RVP_EMAIL_ADDRESS AS RVP_EMAIL_ADDRESS,
        TRADE_AREA AS TRADE_AREA,
        SAFETY_DIRECTOR_NAME AS SAFETY_DIRECTOR_NAME,
        SAFETY_DIRECTOR_EMAIL AS SAFETY_DIRECTOR_EMAIL,
        RETAIL_MANAGER_SAFETY_NAME AS RETAIL_MANAGER_SAFETY_NAME,
        RETAIL_MANAGER_SAFETY_EMAIL AS RETAIL_MANAGER_SAFETY_EMAIL,
        AREA_DIRECTOR_NAME AS AREA_DIRECTOR_NAME,
        AREA_DIRECTOR_EMAIL AS AREA_DIRECTOR_EMAIL,
        DC_GENERAL_MANAGER_NAME AS DC_GENERAL_MANAGER_NAME,
        DC_GENERAL_MANAGER_EMAIL AS DC_GENERAL_MANAGER_EMAIL,
        ASST_DC_GENERAL_MANAGER_NAME1 AS ASST_DC_GENERAL_MANAGER_NAME1,
        ASST_DC_GENERAL_MANAGER_EMAIL1 AS ASST_DC_GENERAL_MANAGER_EMAIL1,
        ASST_DC_GENERAL_MANAGER_NAME2 AS ASST_DC_GENERAL_MANAGER_NAME2,
        ASST_DC_GENERAL_MANAGER_EMAIL2 AS ASST_DC_GENERAL_MANAGER_EMAIL2,
        REGIONAL_DC_SAFETY_MGR_NAME AS REGIONAL_DC_SAFETY_MGR_NAME,
        REGIONAL_DC_SAFETY_MGR_EMAIL AS REGIONAL_DC_SAFETY_MGR_EMAIL,
        DC_PEOPLE_SUPERVISOR_NAME AS DC_PEOPLE_SUPERVISOR_NAME,
        DC_PEOPLE_SUPERVISOR_EMAIL AS DC_PEOPLE_SUPERVISOR_EMAIL,
        PEOPLE_MANAGER_NAME AS PEOPLE_MANAGER_NAME,
        PEOPLE_MANAGER_EMAIL AS PEOPLE_MANAGER_EMAIL,
        ASSET_PROT_DIR_NAME AS ASSET_PROT_DIR_NAME,
        ASSET_PROT_DIR_EMAIL AS ASSET_PROT_DIR_EMAIL,
        SR_REG_ASSET_PROT_MGR_NAME AS SR_REG_ASSET_PROT_MGR_NAME,
        SR_REG_ASSET_PROT_MGR_EMAIL AS SR_REG_ASSET_PROT_MGR_EMAIL,
        REG_ASSET_PROT_MGR_NAME AS REG_ASSET_PROT_MGR_NAME,
        REG_ASSET_PROT_MGR_EMAIL AS REG_ASSET_PROT_MGR_EMAIL,
        ASSET_PROTECT_EMAIL AS ASSET_PROTECT_EMAIL,
        TP_START_DT AS TP_START_DT,
        OPEN_DT AS OPEN_DT,
        GR_OPEN_DT AS GR_OPEN_DT,
        CLOSE_DT AS CLOSE_DT,
        HOTEL_OPEN_DT AS HOTEL_OPEN_DT,
        ADD_DT AS ADD_DT,
        DELETE_DT AS DELETE_DT,
        UPDATE_DT AS UPDATE_DT,
        LOAD_DT AS LOAD_DT,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SITE_PROFILE_2""")

df_3.createOrReplaceTempView("SQ_Shortcut_to_SITE_PROFILE_3")

# COMMAND ----------
# DBTITLE 1, JNR_Detail_Outer_Join_4


df_4=spark.sql("""
    SELECT
        MASTER.LOCATION_ID AS LOCATION_ID,
        MASTER.LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
        MASTER.STORE_NBR AS STORE_NBR,
        MASTER.STORE_NAME AS STORE_NAME,
        MASTER.STORE_TYPE_ID AS STORE_TYPE_ID,
        MASTER.STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
        MASTER.COMPANY_ID AS COMPANY_ID,
        MASTER.REGION_ID AS REGION_ID,
        MASTER.DISTRICT_ID AS DISTRICT_ID,
        MASTER.PRICE_ZONE_ID AS PRICE_ZONE_ID,
        MASTER.PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
        MASTER.REPL_DC_NBR AS REPL_DC_NBR,
        MASTER.REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
        MASTER.REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
        MASTER.SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
        MASTER.SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
        MASTER.SITE_ADDRESS AS SITE_ADDRESS,
        MASTER.SITE_CITY AS SITE_CITY,
        MASTER.STATE_CD AS STATE_CD,
        MASTER.COUNTRY_CD AS COUNTRY_CD,
        MASTER.POSTAL_CD AS POSTAL_CD,
        MASTER.SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
        MASTER.SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
        MASTER.SITE_EMAIL_ADDRESS AS SITE_EMAIL_ADDRESS,
        MASTER.SITE_SALES_FLAG AS SITE_SALES_FLAG,
        MASTER.EQUINE_MERCH_ID AS EQUINE_MERCH_ID,
        MASTER.EQUINE_SITE_ID AS EQUINE_SITE_ID,
        MASTER.EQUINE_SITE_OPEN_DT AS EQUINE_SITE_OPEN_DT,
        MASTER.GEO_LATITUDE_NBR AS GEO_LATITUDE_NBR,
        MASTER.GEO_LONGITUDE_NBR AS GEO_LONGITUDE_NBR,
        MASTER.PETSMART_DMA_CD AS PETSMART_DMA_CD,
        MASTER.LOYALTY_PGM_TYPE_ID AS LOYALTY_PGM_TYPE_ID,
        MASTER.LOYALTY_PGM_STATUS_ID AS LOYALTY_PGM_STATUS_ID,
        MASTER.LOYALTY_PGM_START_DT AS LOYALTY_PGM_START_DT,
        MASTER.LOYALTY_PGM_CHANGE_DT AS LOYALTY_PGM_CHANGE_DT,
        MASTER.BP_COMPANY_NBR AS BP_COMPANY_NBR,
        MASTER.BP_GL_ACCT AS BP_GL_ACCT,
        MASTER.TP_LOC_FLAG AS TP_LOC_FLAG,
        MASTER.TP_ACTIVE_CNT AS TP_ACTIVE_CNT,
        MASTER.PROMO_LABEL_CD AS PROMO_LABEL_CD,
        MASTER.PARENT_LOCATION_ID AS PARENT_LOCATION_ID,
        MASTER.LOCATION_NBR AS LOCATION_NBR,
        MASTER.TIME_ZONE_ID AS TIME_ZONE_ID,
        MASTER.DELV_SERVICE_CLASS_ID AS DELV_SERVICE_CLASS_ID,
        MASTER.PICK_SERVICE_CLASS_ID AS PICK_SERVICE_CLASS_ID,
        MASTER.SITE_LOGIN_ID AS SITE_LOGIN_ID,
        MASTER.SITE_MANAGER_ID AS SITE_MANAGER_ID,
        MASTER.SITE_OPEN_YRS_AMT AS SITE_OPEN_YRS_AMT,
        MASTER.HOTEL_FLAG AS HOTEL_FLAG,
        MASTER.DAYCAMP_FLAG AS DAYCAMP_FLAG,
        MASTER.VET_FLAG AS VET_FLAG,
        MASTER.DIST_MGR_NAME AS DIST_MGR_NAME,
        MASTER.DIST_SVC_MGR_NAME AS DIST_SVC_MGR_NAME,
        MASTER.REGION_VP_NAME AS REGION_VP_NAME,
        MASTER.REGION_TRAINER_NAME AS REGION_TRAINER_NAME,
        MASTER.ASSET_PROTECT_NAME AS ASSET_PROTECT_NAME,
        MASTER.SITE_COUNTY AS SITE_COUNTY,
        MASTER.SITE_FAX_NO AS SITE_FAX_NO,
        MASTER.SFT_OPEN_DT AS SFT_OPEN_DT,
        MASTER.DM_EMAIL_ADDRESS AS DM_EMAIL_ADDRESS,
        MASTER.DSM_EMAIL_ADDRESS AS DSM_EMAIL_ADDRESS,
        MASTER.RVP_EMAIL_ADDRESS AS RVP_EMAIL_ADDRESS,
        MASTER.TRADE_AREA AS TRADE_AREA,
        MASTER.SAFETY_DIRECTOR_NAME AS SAFETY_DIRECTOR_NAME,
        MASTER.SAFETY_DIRECTOR_EMAIL AS SAFETY_DIRECTOR_EMAIL,
        MASTER.RETAIL_MANAGER_SAFETY_NAME AS RETAIL_MANAGER_SAFETY_NAME,
        MASTER.RETAIL_MANAGER_SAFETY_EMAIL AS RETAIL_MANAGER_SAFETY_EMAIL,
        MASTER.AREA_DIRECTOR_NAME AS AREA_DIRECTOR_NAME,
        MASTER.AREA_DIRECTOR_EMAIL AS AREA_DIRECTOR_EMAIL,
        MASTER.DC_GENERAL_MANAGER_NAME AS DC_GENERAL_MANAGER_NAME,
        MASTER.DC_GENERAL_MANAGER_EMAIL AS DC_GENERAL_MANAGER_EMAIL,
        MASTER.ASST_DC_GENERAL_MANAGER_NAME1 AS ASST_DC_GENERAL_MANAGER_NAME1,
        MASTER.ASST_DC_GENERAL_MANAGER_EMAIL1 AS ASST_DC_GENERAL_MANAGER_EMAIL1,
        MASTER.ASST_DC_GENERAL_MANAGER_NAME2 AS ASST_DC_GENERAL_MANAGER_NAME2,
        MASTER.ASST_DC_GENERAL_MANAGER_EMAIL2 AS ASST_DC_GENERAL_MANAGER_EMAIL2,
        MASTER.REGIONAL_DC_SAFETY_MGR_NAME AS REGIONAL_DC_SAFETY_MGR_NAME,
        MASTER.REGIONAL_DC_SAFETY_MGR_EMAIL AS REGIONAL_DC_SAFETY_MGR_EMAIL,
        MASTER.DC_PEOPLE_SUPERVISOR_NAME AS DC_PEOPLE_SUPERVISOR_NAME,
        MASTER.DC_PEOPLE_SUPERVISOR_EMAIL AS DC_PEOPLE_SUPERVISOR_EMAIL,
        MASTER.PEOPLE_MANAGER_NAME AS PEOPLE_MANAGER_NAME,
        MASTER.PEOPLE_MANAGER_EMAIL AS PEOPLE_MANAGER_EMAIL,
        MASTER.ASSET_PROT_DIR_NAME AS ASSET_PROT_DIR_NAME,
        MASTER.ASSET_PROT_DIR_EMAIL AS ASSET_PROT_DIR_EMAIL,
        MASTER.SR_REG_ASSET_PROT_MGR_NAME AS SR_REG_ASSET_PROT_MGR_NAME,
        MASTER.SR_REG_ASSET_PROT_MGR_EMAIL AS SR_REG_ASSET_PROT_MGR_EMAIL,
        MASTER.REG_ASSET_PROT_MGR_NAME AS REG_ASSET_PROT_MGR_NAME,
        MASTER.REG_ASSET_PROT_MGR_EMAIL AS REG_ASSET_PROT_MGR_EMAIL,
        MASTER.ASSET_PROTECT_EMAIL AS ASSET_PROTECT_EMAIL,
        MASTER.TP_START_DT AS TP_START_DT,
        MASTER.OPEN_DT AS OPEN_DT,
        MASTER.GR_OPEN_DT AS GR_OPEN_DT,
        MASTER.CLOSE_DT AS CLOSE_DT,
        MASTER.HOTEL_OPEN_DT AS HOTEL_OPEN_DT,
        MASTER.ADD_DT AS ADD_DT,
        MASTER.DELETE_DT AS DELETE_DT,
        MASTER.UPDATE_DT AS UPDATE_DT,
        MASTER.LOAD_DT AS LOAD_DT,
        DETAIL.EMPLOYEE_ID AS o_EMPLOYEE_ID,
        DETAIL.EMPL_FIRST_NAME AS EMPL_FIRST_NAME,
        DETAIL.EMPL_LAST_NAME AS EMPL_LAST_NAME,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_to_SITE_PROFILE_3 MASTER 
    RIGHT JOIN
        SQ_Shortcut_to_EMPLOYEE_PROFILE_1 DETAIL 
            ON MASTER.SITE_MANAGER_ID = DETAIL.EMPLOYEE_ID""")

df_4.createOrReplaceTempView("JNR_Detail_Outer_Join_4")

# COMMAND ----------
# DBTITLE 1, LKP_STORE_TYPE_5


df_5=spark.sql("""
    SELECT
        STORE_TYPE_DESC AS STORE_TYPE_DESC,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        (SELECT
            STORE_TYPE.STORE_TYPE_DESC AS STORE_TYPE_DESC,
            TRIM(STORE_TYPE.STORE_TYPE_ID) AS STORE_TYPE_ID 
        FROM
            STORE_TYPE) AS STORE_TYPE 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON STORE_TYPE.STORE_TYPE_ID = JNR_Detail_Outer_Join_4.STORE_TYPE_ID""")

df_5.createOrReplaceTempView("LKP_STORE_TYPE_5")

# COMMAND ----------
# DBTITLE 1, LKP_DISTRICT_6


df_6=spark.sql("""
    SELECT
        DISTRICT_DESC AS DISTRICT_DESC,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        DISTRICT 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON DISTRICT.DISTRICT_ID = JNR_Detail_Outer_Join_4.DISTRICT_ID""")

df_6.createOrReplaceTempView("LKP_DISTRICT_6")

# COMMAND ----------
# DBTITLE 1, LKP_SLSCMP_STORE_7


df_7=spark.sql("""
    SELECT
        FIRST_SALE_DT AS FIRST_SALE_DT,
        FIRST_MEASURED_SALE_DT AS FIRST_MEASURED_SALE_DT,
        LAST_SALE_DT AS LAST_SALE_DT,
        SALES_CURR_FLAG AS SALES_CURR_FLAG,
        COMP_EFF_DT AS COMP_EFF_DT,
        COMP_END_DT AS COMP_END_DT,
        COMP_CURR_FLAG AS COMP_CURR_FLAG,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SLSCMP_STORE 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON SLSCMP_STORE.LOCATION_ID = JNR_Detail_Outer_Join_4.LOCATION_ID""")

df_7.createOrReplaceTempView("LKP_SLSCMP_STORE_7")

# COMMAND ----------
# DBTITLE 1, LKP_LOCATION_TYPE_8


df_8=spark.sql("""
    SELECT
        LOCATION_TYPE_DESC AS LOCATION_TYPE_DESC,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        LOCATION_TYPE 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON LOCATION_TYPE.LOCATION_TYPE_ID = JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID""")

df_8.createOrReplaceTempView("LKP_LOCATION_TYPE_8")

# COMMAND ----------
# DBTITLE 1, LKP_SALES_RANKING_WK_9


df_9=spark.sql("""
    SELECT
        TOTAL_SALES_RANKING_CD AS TOTAL_SALES_RANKING_CD,
        MERCH_SALES_RANKING_CD AS MERCH_SALES_RANKING_CD,
        SERVICES_SALES_RANKING_CD AS SERVICES_SALES_RANKING_CD,
        SALON_SALES_RANKING_CD AS SALON_SALES_RANKING_CD,
        TRAINING_SALES_RANKING_CD AS TRAINING_SALES_RANKING_CD,
        HOTEL_DDC_SALES_RANKING_CD AS HOTEL_DDC_SALES_RANKING_CD,
        CONSUMABLES_SALES_RANKING_CD AS CONSUMABLES_SALES_RANKING_CD,
        HARDGOODS_SALES_RANKING_CD AS HARDGOODS_SALES_RANKING_CD,
        SPECIALTY_SALES_RANKING_CD AS SPECIALTY_SALES_RANKING_CD,
        JNR_Detail_Outer_Join_4.LOCATION_ID AS in_LOCATION_ID,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        (SELECT
            SALES_RANKING_WK.TOTAL_SALES_RANKING_CD AS TOTAL_SALES_RANKING_CD,
            SALES_RANKING_WK.MERCH_SALES_RANKING_CD AS MERCH_SALES_RANKING_CD,
            SALES_RANKING_WK.SERVICES_SALES_RANKING_CD AS SERVICES_SALES_RANKING_CD,
            SALES_RANKING_WK.SALON_SALES_RANKING_CD AS SALON_SALES_RANKING_CD,
            SALES_RANKING_WK.TRAINING_SALES_RANKING_CD AS TRAINING_SALES_RANKING_CD,
            SALES_RANKING_WK.HOTEL_DDC_SALES_RANKING_CD AS HOTEL_DDC_SALES_RANKING_CD,
            SALES_RANKING_WK.CONSUMABLES_SALES_RANKING_CD AS CONSUMABLES_SALES_RANKING_CD,
            SALES_RANKING_WK.HARDGOODS_SALES_RANKING_CD AS HARDGOODS_SALES_RANKING_CD,
            SALES_RANKING_WK.SPECIALTY_SALES_RANKING_CD AS SPECIALTY_SALES_RANKING_CD,
            SALES_RANKING_WK.LOCATION_ID AS LOCATION_ID 
        FROM
            SALES_RANKING_WK 
        WHERE
            WEEK_DT = (
                SELECT
                    MAX(week_dt) 
                FROM
                    SALES_RANKING_WK 
                WHERE
                    WEEK_DT > current_date - 15
            )
        ) AS SALES_RANKING_WK 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON SALES_RANKING_WK.LOCATION_ID = JNR_Detail_Outer_Join_4.LOCATION_ID""")

df_9.createOrReplaceTempView("LKP_SALES_RANKING_WK_9")

# COMMAND ----------
# DBTITLE 1, EXP_SUPER_REGION_10


df_10=spark.sql("""
    SELECT
        REGION_ID AS REGION_ID,
        IFF(IN(REGION_ID,
        200,
        300,
        850,
        400),
        1,
        IFF(IN(REGION_ID,
        775,
        800,
        950,
        500),
        4,
        IFF(IN(REGION_ID,
        650),
        5,
        REGION_ID))) AS SUPER_REGION_ID,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNR_Detail_Outer_Join_4""")

df_10.createOrReplaceTempView("EXP_SUPER_REGION_10")

# COMMAND ----------
# DBTITLE 1, LKP_SUPER_REGION_11


df_11=spark.sql("""
    SELECT
        SUPER_REGION_DESC AS SUPER_REGION_DESC,
        EXP_SUPER_REGION_10.SUPER_REGION_ID AS SUPER_REGION_ID1,
        EXP_SUPER_REGION_10.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SUPER_REGION 
    RIGHT OUTER JOIN
        EXP_SUPER_REGION_10 
            ON SUPER_REGION.SUPER_REGION_ID = EXP_SUPER_REGION_10.SUPER_REGION_ID""")

df_11.createOrReplaceTempView("LKP_SUPER_REGION_11")

# COMMAND ----------
# DBTITLE 1, LKP_COMPANY_12


df_12=spark.sql("""
    SELECT
        COMPANY_DESC AS COMPANY_DESC,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        COMPANY 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON COMPANY.COMPANY_ID = JNR_Detail_Outer_Join_4.COMPANY_ID""")

df_12.createOrReplaceTempView("LKP_COMPANY_12")

# COMMAND ----------
# DBTITLE 1, LKP_COUNTRY_13


df_13=spark.sql("""
    SELECT
        COUNTRY_NAME AS COUNTRY_NAME,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        (SELECT
            COUNTRY.COUNTRY_NAME AS COUNTRY_NAME,
            TRIM(COUNTRY.COUNTRY_CD) AS COUNTRY_CD 
        FROM
            COUNTRY) AS COUNTRY 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON COUNTRY.COUNTRY_CD = JNR_Detail_Outer_Join_4.COUNTRY_CD""")

df_13.createOrReplaceTempView("LKP_COUNTRY_13")

# COMMAND ----------
# DBTITLE 1, LKP_DM_PG_STORE_14


df_14=spark.sql("""
    SELECT
        PURCH_GROUP_ID AS PURCH_GROUP_ID,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        DM_PG_STORE 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON DM_PG_STORE.STORE_NBR = JNR_Detail_Outer_Join_4.STORE_NBR""")

df_14.createOrReplaceTempView("LKP_DM_PG_STORE_14")

# COMMAND ----------
# DBTITLE 1, LKP_STATE_15


df_15=spark.sql("""
    SELECT
        STATE_NAME AS STATE_NAME,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        (SELECT
            STATE.STATE_NAME AS STATE_NAME,
            TRIM(STATE.STATE_CD) AS STATE_CD 
        FROM
            STATE) AS STATE 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON STATE.STATE_CD = JNR_Detail_Outer_Join_4.STATE_CD""")

df_15.createOrReplaceTempView("LKP_STATE_15")

# COMMAND ----------
# DBTITLE 1, LKP_EQUINE_MERCH_16


df_16=spark.sql("""
    SELECT
        EQUINE_MERCH_DESC AS EQUINE_MERCH_DESC,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        EQUINE_MERCH 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON EQUINE_MERCH.EQUINE_MERCH_ID = JNR_Detail_Outer_Join_4.EQUINE_MERCH_ID""")

df_16.createOrReplaceTempView("LKP_EQUINE_MERCH_16")

# COMMAND ----------
# DBTITLE 1, LKP_PRICE_ZONE_17


df_17=spark.sql("""
    SELECT
        PRICE_ZONE_DESC AS PRICE_ZONE_DESC,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        (SELECT
            PRICE_ZONE.PRICE_ZONE_DESC AS PRICE_ZONE_DESC,
            TRIM(PRICE_ZONE.PRICE_ZONE_ID) AS PRICE_ZONE_ID 
        FROM
            PRICE_ZONE) AS PRICE_ZONE 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON PRICE_ZONE.PRICE_ZONE_ID = JNR_Detail_Outer_Join_4.PRICE_ZONE_ID""")

df_17.createOrReplaceTempView("LKP_PRICE_ZONE_17")

# COMMAND ----------
# DBTITLE 1, LKP_STORE_TIME_ZONE_18


df_18=spark.sql("""
    SELECT
        TIME_ZONE AS TIME_ZONE,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        STORE_TIME_ZONE 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON STORE_TIME_ZONE.SITE_NBR = JNR_Detail_Outer_Join_4.STORE_NBR""")

df_18.createOrReplaceTempView("LKP_STORE_TIME_ZONE_18")

# COMMAND ----------
# DBTITLE 1, LKP_USR_DC_NAMES_19


df_19=spark.sql("""
    SELECT
        DC_RLPM_NAME AS DC_RLPM_NAME,
        DC_RLPM_EMAIL AS DC_RLPM_EMAIL,
        DC_ASST_GM1_NAME AS DC_ASST_GM1_NAME,
        DC_ASST_GM1_EMAIL AS DC_ASST_GM1_EMAIL,
        DC_ASST_GM2_NAME AS DC_ASST_GM2_NAME,
        DC_ASST_GM2_EMAIL AS DC_ASST_GM2_EMAIL,
        DC_GM_NAME AS DC_GM_NAME,
        DC_GM_EMAIL AS DC_GM_EMAIL,
        DC_HR_SUPER1_NAME AS DC_HR_SUPER1_NAME,
        DC_HR_SUPER1_EMAIL AS DC_HR_SUPER1_EMAIL,
        DC_HR_SUPER2_NAME AS DC_HR_SUPER2_NAME,
        DC_HR_SUPER2_EMAIL AS DC_HR_SUPER2_EMAIL,
        DC_HR_MGR_NAME AS DC_HR_MGR_NAME,
        DC_HR_MGR_EMAIL AS DC_HR_MGR_EMAIL,
        JNR_Detail_Outer_Join_4.STORE_NBR AS STORE_NBR1,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        USR_DC_NAMES 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON USR_DC_NAMES.STORE_NBR = JNR_Detail_Outer_Join_4.STORE_NBR""")

df_19.createOrReplaceTempView("LKP_USR_DC_NAMES_19")

# COMMAND ----------
# DBTITLE 1, LKP_PRICE_AD_ZONE_20


df_20=spark.sql("""
    SELECT
        PRICE_AD_ZONE_DESC AS PRICE_AD_ZONE_DESC,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        (SELECT
            PRICE_AD_ZONE.PRICE_AD_ZONE_DESC AS PRICE_AD_ZONE_DESC,
            TRIM(PRICE_AD_ZONE.PRICE_AD_ZONE_ID) AS PRICE_AD_ZONE_ID 
        FROM
            PRICE_AD_ZONE) AS PRICE_AD_ZONE 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON PRICE_AD_ZONE.PRICE_AD_ZONE_ID = JNR_Detail_Outer_Join_4.PRICE_AD_ZONE_ID""")

df_20.createOrReplaceTempView("LKP_PRICE_AD_ZONE_20")

# COMMAND ----------
# DBTITLE 1, EXP_Conv_21


df_21=spark.sql("""
    SELECT
        (CAST(LKP_DM_PG_STORE_14.PURCH_GROUP_ID AS DECIMAL (38,
        0))) AS o_PURCH_GROUP_ID,
        (CAST(JNR_Detail_Outer_Join_4.REGION_ID AS DECIMAL (38,
        0))) AS o_REGION_ID,
        (CAST(JNR_Detail_Outer_Join_4.DISTRICT_ID AS DECIMAL (38,
        0))) AS o_DISTRICT_ID,
        LKP_DM_PG_STORE_14.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        LKP_DM_PG_STORE_14 
    INNER JOIN
        JNR_Detail_Outer_Join_4 
            ON LKP_DM_PG_STORE_14.Monotonically_Increasing_Id = JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id""")

df_21.createOrReplaceTempView("EXP_Conv_21")

# COMMAND ----------
# DBTITLE 1, LKP_USR_REGION_NAMES_22


df_22=spark.sql("""
    SELECT
        REGION_ID AS REGION_ID,
        RVP_NAME AS RVP_NAME,
        RVP_EMAIL AS RVP_EMAIL,
        RD_NAME AS RD_NAME,
        RD_EMAIL AS RD_EMAIL,
        R_PEOPLE_DIR_NAME AS R_PEOPLE_DIR_NAME,
        R_PEOPLE_DIR_EMAIL AS R_PEOPLE_DIR_EMAIL,
        SR_LP_SAFETY_MGR_NAME AS SR_LP_SAFETY_MGR_NAME,
        SR_LP_SAFETY_MGR_EMAIL AS SR_LP_SAFETY_MGR_EMAIL,
        RETAIL_SAFETY_MGR_NAME AS RETAIL_SAFETY_MGR_NAME,
        RETAIL_SAFETY_MGR_EMAIL AS RETAIL_SAFETY_MGR_EMAIL,
        LP_SAFETY_DIR_NAME AS LP_SAFETY_DIR_NAME,
        LP_SAFETY_DIR_EMAIL AS LP_SAFETY_DIR_EMAIL,
        LEARN_SOLUTION_MGR_NAME AS LEARN_SOLUTION_MGR_NAME,
        LEARN_SOLUTION_MGR_EMAIL AS LEARN_SOLUTION_MGR_EMAIL,
        EXP_Conv_21.o_REGION_ID AS o_REGION_ID,
        EXP_Conv_21.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        USR_REGION_NAMES 
    RIGHT OUTER JOIN
        EXP_Conv_21 
            ON REGION_ID = EXP_Conv_21.o_REGION_ID""")

df_22.createOrReplaceTempView("LKP_USR_REGION_NAMES_22")

# COMMAND ----------
# DBTITLE 1, LKP_DM_PG_MGR_DVL_23


df_23=spark.sql("""
    SELECT
        MGR_ID AS MGR_ID,
        MGR_DESC AS MGR_DESC,
        DVL_ID AS DVL_ID,
        DVL_DESC AS DVL_DESC,
        PURCH_GROUP_NAME AS PURCH_GROUP_NAME,
        EXP_Conv_21.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        DM_PG_MGR_DVL 
    RIGHT OUTER JOIN
        EXP_Conv_21 
            ON DM_PG_MGR_DVL.PURCH_GROUP_ID = EXP_Conv_21.o_PURCH_GROUP_ID""")

df_23.createOrReplaceTempView("LKP_DM_PG_MGR_DVL_23")

# COMMAND ----------
# DBTITLE 1, LKP_USR_DISTRICT_NAMES_24


df_24=spark.sql("""
    SELECT
        DM_NAME AS DM_NAME,
        DM_NAME_EMAIL AS DM_NAME_EMAIL,
        LP_SAFETY_NAME AS LP_SAFETY_NAME,
        LP_SAFETY_EMAIL AS LP_SAFETY_EMAIL,
        HR_SUPER_NAME AS HR_SUPER_NAME,
        HR_SUPER_EMAIL AS HR_SUPER_EMAIL,
        EXP_Conv_21.o_DISTRICT_ID AS o_DISTRICT_ID,
        EXP_Conv_21.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        USR_DISTRICT_NAMES 
    RIGHT OUTER JOIN
        EXP_Conv_21 
            ON USR_DISTRICT_NAMES.DISTRICT_ID = EXP_Conv_21.o_DISTRICT_ID""")

df_24.createOrReplaceTempView("LKP_USR_DISTRICT_NAMES_24")

# COMMAND ----------
# DBTITLE 1, LKP_LOYALTY_PGM_TYPE_25


df_25=spark.sql("""
    SELECT
        LOYALTY_PGM_TYPE_DESC AS LOYALTY_PGM_TYPE_DESC,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        LOYALTY_PGM_TYPE 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON LOYALTY_PGM_TYPE.LOYALTY_PGM_TYPE_ID = JNR_Detail_Outer_Join_4.LOYALTY_PGM_TYPE_ID""")

df_25.createOrReplaceTempView("LKP_LOYALTY_PGM_TYPE_25")

# COMMAND ----------
# DBTITLE 1, LKP_PETSMART_DMA_26


df_26=spark.sql("""
    SELECT
        PETSMART_DMA_DESC AS PETSMART_DMA_DESC,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        (SELECT
            PETSMART_DMA.PETSMART_DMA_DESC AS PETSMART_DMA_DESC,
            TRIM(PETSMART_DMA.PETSMART_DMA_CD) AS PETSMART_DMA_CD 
        FROM
            PETSMART_DMA) AS PETSMART_DMA 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON PETSMART_DMA.PETSMART_DMA_CD = JNR_Detail_Outer_Join_4.PETSMART_DMA_CD""")

df_26.createOrReplaceTempView("LKP_PETSMART_DMA_26")

# COMMAND ----------
# DBTITLE 1, LKP_REGION_27


df_27=spark.sql("""
    SELECT
        REGION_DESC AS REGION_DESC,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        REGION 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON REGION.REGION_ID = JNR_Detail_Outer_Join_4.REGION_ID""")

df_27.createOrReplaceTempView("LKP_REGION_27")

# COMMAND ----------
# DBTITLE 1, LKP_EQUINE_SITE_28


df_28=spark.sql("""
    SELECT
        EQUINE_SITE_DESC AS EQUINE_SITE_DESC,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        EQUINE_SITE 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON EQUINE_SITE.EQUINE_SITE_ID = JNR_Detail_Outer_Join_4.EQUINE_SITE_ID""")

df_28.createOrReplaceTempView("LKP_EQUINE_SITE_28")

# COMMAND ----------
# DBTITLE 1, LKP_LOYALTY_PGM_STATUS_29


df_29=spark.sql("""
    SELECT
        LOYALTY_PGM_STATUS_DESC AS LOYALTY_PGM_STATUS_DESC,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        LOYALTY_PGM_STATUS 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON LOYALTY_PGM_STATUS.LOYALTY_PGM_STATUS_ID = JNR_Detail_Outer_Join_4.LOYALTY_PGM_STATUS_ID""")

df_29.createOrReplaceTempView("LKP_LOYALTY_PGM_STATUS_29")

# COMMAND ----------
# DBTITLE 1, EXP_Remove_30


df_30=spark.sql("""
    SELECT
        JNR_Detail_Outer_Join_4.LOCATION_ID AS LOCATION_ID,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
        RTRIM(LKP_LOCATION_TYPE_8.LOCATION_TYPE_DESC) AS o_LOCATION_TYPE_DESC,
        JNR_Detail_Outer_Join_4.STORE_NBR AS STORE_NBR1,
        RTRIM(JNR_Detail_Outer_Join_4.STORE_NAME) AS o_STORE_NAME,
        JNR_Detail_Outer_Join_4.STORE_TYPE_ID AS STORE_TYPE_ID,
        RTRIM(LKP_STORE_TYPE_5.STORE_TYPE_DESC) AS o_STORE_TYPE_DESC,
        JNR_Detail_Outer_Join_4.PARENT_LOCATION_ID AS PARENT_LOCATION_ID,
        JNR_Detail_Outer_Join_4.LOCATION_NBR AS LOCATION_NBR,
        JNR_Detail_Outer_Join_4.COMPANY_ID AS COMPANY_ID,
        RTRIM(LKP_COMPANY_12.COMPANY_DESC) AS o_COMPANY_DESC,
        LKP_SUPER_REGION_11.SUPER_REGION_ID1 AS SUPER_REGION_ID,
        LKP_SUPER_REGION_11.SUPER_REGION_DESC AS SUPER_REGION_DESC,
        JNR_Detail_Outer_Join_4.REGION_ID AS REGION_ID,
        RTRIM(LKP_REGION_27.REGION_DESC) AS o_REGION_DESC,
        JNR_Detail_Outer_Join_4.DISTRICT_ID AS DISTRICT_ID,
        RTRIM(LKP_DISTRICT_6.DISTRICT_DESC) AS o_DISTRICT_DESC,
        JNR_Detail_Outer_Join_4.SITE_ADDRESS AS SITE_ADDRESS,
        RTRIM(JNR_Detail_Outer_Join_4.SITE_CITY) AS o_SITE_CITY,
        RTRIM(JNR_Detail_Outer_Join_4.SITE_COUNTY) AS o_SITE_COUNTY,
        JNR_Detail_Outer_Join_4.STATE_CD AS STATE_CD,
        RTRIM(LKP_STATE_15.STATE_NAME) AS o_STATE_NAME,
        JNR_Detail_Outer_Join_4.POSTAL_CD AS POSTAL_CD,
        JNR_Detail_Outer_Join_4.COUNTRY_CD AS COUNTRY_CD,
        RTRIM(LKP_COUNTRY_13.COUNTRY_NAME) AS o_COUNTRY_NAME,
        JNR_Detail_Outer_Join_4.GEO_LATITUDE_NBR AS GEO_LATITUDE_NBR,
        JNR_Detail_Outer_Join_4.GEO_LONGITUDE_NBR AS GEO_LONGITUDE_NBR,
        JNR_Detail_Outer_Join_4.PETSMART_DMA_CD AS PETSMART_DMA_CD,
        RTRIM(LKP_PETSMART_DMA_26.PETSMART_DMA_DESC) AS o_PETSMART_DMA_DESC,
        JNR_Detail_Outer_Join_4.SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
        JNR_Detail_Outer_Join_4.SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
        JNR_Detail_Outer_Join_4.SITE_FAX_NO AS SITE_FAX_NO,
        RTRIM(JNR_Detail_Outer_Join_4.SITE_EMAIL_ADDRESS) AS o_SITE_EMAIL_ADDRESS,
        JNR_Detail_Outer_Join_4.STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
        JNR_Detail_Outer_Join_4.SFT_OPEN_DT AS SFT_OPEN_DT,
        JNR_Detail_Outer_Join_4.OPEN_DT AS OPEN_DT,
        JNR_Detail_Outer_Join_4.GR_OPEN_DT AS GR_OPEN_DT,
        JNR_Detail_Outer_Join_4.CLOSE_DT AS CLOSE_DT,
        JNR_Detail_Outer_Join_4.SITE_SALES_FLAG AS SITE_SALES_FLAG,
        LKP_SLSCMP_STORE_7.SALES_CURR_FLAG AS SALES_CURR_FLAG,
        JNR_Detail_Outer_Join_4.SITE_OPEN_YRS_AMT AS SITE_OPEN_YRS_AMT,
        LKP_SLSCMP_STORE_7.FIRST_SALE_DT AS FIRST_SALE_DT,
        LKP_SLSCMP_STORE_7.FIRST_MEASURED_SALE_DT AS FIRST_MEASURED_SALE_DT,
        LKP_SLSCMP_STORE_7.LAST_SALE_DT AS LAST_SALE_DT,
        LKP_SLSCMP_STORE_7.COMP_CURR_FLAG AS COMP_CURR_FLAG,
        LKP_SLSCMP_STORE_7.COMP_EFF_DT AS COMP_EFF_DT,
        LKP_SLSCMP_STORE_7.COMP_END_DT AS COMP_END_DT,
        JNR_Detail_Outer_Join_4.TP_LOC_FLAG AS TP_LOC_FLAG,
        JNR_Detail_Outer_Join_4.TP_ACTIVE_CNT AS TP_ACTIVE_CNT,
        JNR_Detail_Outer_Join_4.TP_START_DT AS TP_START_DT,
        JNR_Detail_Outer_Join_4.HOTEL_FLAG AS HOTEL_FLAG,
        JNR_Detail_Outer_Join_4.HOTEL_OPEN_DT AS HOTEL_OPEN_DT,
        JNR_Detail_Outer_Join_4.DAYCAMP_FLAG AS DAYCAMP_FLAG,
        JNR_Detail_Outer_Join_4.VET_FLAG AS VET_FLAG,
        SUBSTR(LKP_STORE_TIME_ZONE_18.TIME_ZONE,
        1,
        3) AS o_TIME_ZONE_ID,
        RTRIM(LKP_STORE_TIME_ZONE_18.TIME_ZONE) AS o_TIME_ZONE,
        JNR_Detail_Outer_Join_4.SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
        JNR_Detail_Outer_Join_4.SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
        JNR_Detail_Outer_Join_4.TRADE_AREA AS TRADE_AREA,
        JNR_Detail_Outer_Join_4.DELV_SERVICE_CLASS_ID AS DELV_SERVICE_CLASS_ID,
        JNR_Detail_Outer_Join_4.PICK_SERVICE_CLASS_ID AS PICK_SERVICE_CLASS_ID,
        JNR_Detail_Outer_Join_4.REPL_DC_NBR AS REPL_DC_NBR,
        JNR_Detail_Outer_Join_4.REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
        JNR_Detail_Outer_Join_4.REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
        JNR_Detail_Outer_Join_4.PROMO_LABEL_CD AS PROMO_LABEL_CD,
        JNR_Detail_Outer_Join_4.PRICE_ZONE_ID AS PRICE_ZONE_ID,
        RTRIM(LKP_PRICE_ZONE_17.PRICE_ZONE_DESC) AS o_PRICE_ZONE_DESC,
        JNR_Detail_Outer_Join_4.PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
        RTRIM(LKP_PRICE_AD_ZONE_20.PRICE_AD_ZONE_DESC) AS o_PRICE_AD_ZONE_DESC,
        JNR_Detail_Outer_Join_4.EQUINE_MERCH_ID AS EQUINE_MERCH_ID,
        RTRIM(LKP_EQUINE_MERCH_16.EQUINE_MERCH_DESC) AS o_EQUINE_MERCH_DESC,
        JNR_Detail_Outer_Join_4.EQUINE_SITE_ID AS EQUINE_SITE_ID,
        RTRIM(LKP_EQUINE_SITE_28.EQUINE_SITE_DESC) AS o_EQUINE_SITE_DESC,
        JNR_Detail_Outer_Join_4.EQUINE_SITE_OPEN_DT AS EQUINE_SITE_OPEN_DT,
        JNR_Detail_Outer_Join_4.LOYALTY_PGM_TYPE_ID AS LOYALTY_PGM_TYPE_ID,
        RTRIM(LKP_LOYALTY_PGM_TYPE_25.LOYALTY_PGM_TYPE_DESC) AS o_LOYALTY_PGM_TYPE_DESC,
        JNR_Detail_Outer_Join_4.LOYALTY_PGM_STATUS_ID AS LOYALTY_PGM_STATUS_ID,
        RTRIM(LKP_LOYALTY_PGM_STATUS_29.LOYALTY_PGM_STATUS_DESC) AS o_LOYALTY_PGM_STATUS_DESC,
        JNR_Detail_Outer_Join_4.LOYALTY_PGM_START_DT AS LOYALTY_PGM_START_DT,
        JNR_Detail_Outer_Join_4.LOYALTY_PGM_CHANGE_DT AS LOYALTY_PGM_CHANGE_DT,
        JNR_Detail_Outer_Join_4.BP_COMPANY_NBR AS BP_COMPANY_NBR,
        JNR_Detail_Outer_Join_4.BP_GL_ACCT AS BP_GL_ACCT,
        JNR_Detail_Outer_Join_4.SITE_LOGIN_ID AS SITE_LOGIN_ID,
        DECODE(ISNULL(JNR_Detail_Outer_Join_4.SITE_MANAGER_ID),
        0,
        JNR_Detail_Outer_Join_4.SITE_MANAGER_ID) AS o_SITE_MANAGER_ID,
        JNR_Detail_Outer_Join_4.EMPL_FIRST_NAME || ' ' || JNR_Detail_Outer_Join_4.EMPL_LAST_NAME AS SITE_MANAGER_NAME,
        LKP_DM_PG_MGR_DVL_23.MGR_ID AS MGR_ID,
        RTRIM(LKP_DM_PG_MGR_DVL_23.MGR_DESC) AS o_MGR_DESC,
        LKP_DM_PG_MGR_DVL_23.DVL_ID AS DVL_ID,
        RTRIM(LKP_DM_PG_MGR_DVL_23.DVL_DESC) AS o_DVL_DESC,
        EXP_Conv_21.o_PURCH_GROUP_ID AS PURCH_GROUP_ID,
        LKP_DM_PG_MGR_DVL_23.PURCH_GROUP_NAME AS PURCH_GROUP_NAME,
        LKP_SALES_RANKING_WK_9.TOTAL_SALES_RANKING_CD AS TOTAL_SALES_RANKING_CD,
        LKP_SALES_RANKING_WK_9.MERCH_SALES_RANKING_CD AS MERCH_SALES_RANKING_CD,
        LKP_SALES_RANKING_WK_9.SERVICES_SALES_RANKING_CD AS SERVICES_SALES_RANKING_CD,
        LKP_SALES_RANKING_WK_9.SALON_SALES_RANKING_CD AS SALON_SALES_RANKING_CD,
        LKP_SALES_RANKING_WK_9.TRAINING_SALES_RANKING_CD AS TRAINING_SALES_RANKING_CD,
        LKP_SALES_RANKING_WK_9.HOTEL_DDC_SALES_RANKING_CD AS HOTEL_DDC_SALES_RANKING_CD,
        LKP_SALES_RANKING_WK_9.CONSUMABLES_SALES_RANKING_CD AS CONSUMABLES_SALES_RANKING_CD,
        LKP_SALES_RANKING_WK_9.HARDGOODS_SALES_RANKING_CD AS HARDGOODS_SALES_RANKING_CD,
        LKP_SALES_RANKING_WK_9.SPECIALTY_SALES_RANKING_CD AS SPECIALTY_SALES_RANKING_CD,
        JNR_Detail_Outer_Join_4.DIST_MGR_NAME AS DIST_MGR_NAME,
        JNR_Detail_Outer_Join_4.DM_EMAIL_ADDRESS AS DM_EMAIL_ADDRESS,
        JNR_Detail_Outer_Join_4.AREA_DIRECTOR_NAME AS AREA_DIRECTOR_NAME,
        JNR_Detail_Outer_Join_4.AREA_DIRECTOR_EMAIL AS AREA_DIRECTOR_EMAIL,
        JNR_Detail_Outer_Join_4.DIST_SVC_MGR_NAME AS DIST_SVC_MGR_NAME,
        JNR_Detail_Outer_Join_4.DSM_EMAIL_ADDRESS AS DSM_EMAIL_ADDRESS,
        JNR_Detail_Outer_Join_4.REGION_VP_NAME AS REGION_VP_NAME,
        JNR_Detail_Outer_Join_4.RVP_EMAIL_ADDRESS AS RVP_EMAIL_ADDRESS,
        JNR_Detail_Outer_Join_4.REGION_TRAINER_NAME AS REGION_TRAINER_NAME,
        JNR_Detail_Outer_Join_4.ASSET_PROTECT_NAME AS ASSET_PROTECT_NAME,
        JNR_Detail_Outer_Join_4.ASSET_PROTECT_EMAIL AS ASSET_PROTECT_EMAIL,
        JNR_Detail_Outer_Join_4.SAFETY_DIRECTOR_NAME AS SAFETY_DIRECTOR_NAME,
        JNR_Detail_Outer_Join_4.SAFETY_DIRECTOR_EMAIL AS SAFETY_DIRECTOR_EMAIL,
        JNR_Detail_Outer_Join_4.SR_REG_ASSET_PROT_MGR_NAME AS SR_REG_ASSET_PROT_MGR_NAME,
        JNR_Detail_Outer_Join_4.SR_REG_ASSET_PROT_MGR_EMAIL AS SR_REG_ASSET_PROT_MGR_EMAIL,
        DECODE(TRUE,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 1,
        'N/A',
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 2,
        'N/A',
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 3,
        'N/A',
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 4,
        'N/A',
        JNR_Detail_Outer_Join_4.SR_REG_ASSET_PROT_MGR_NAME) AS SR_LP_SAFETY_MGR_NAME,
        DECODE(TRUE,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 1,
        'N/A',
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 2,
        'N/A',
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 3,
        'N/A',
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 4,
        'N/A',
        JNR_Detail_Outer_Join_4.SR_REG_ASSET_PROT_MGR_EMAIL) AS SR_LP_SAFETY_MGR_EMAIL,
        LKP_USR_DC_NAMES_19.DC_RLPM_NAME AS DC_RLPM_NAME,
        DECODE(TRUE,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 1,
        LKP_USR_DC_NAMES_19.DC_RLPM_NAME,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 2,
        LKP_USR_DC_NAMES_19.DC_RLPM_NAME,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 3,
        LKP_USR_DC_NAMES_19.DC_RLPM_NAME,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 4,
        LKP_USR_DC_NAMES_19.DC_RLPM_NAME,
        LKP_USR_DISTRICT_NAMES_24.LP_SAFETY_NAME) AS o_REGIONAL_LP_SAFETY_MGR_NAME,
        JNR_Detail_Outer_Join_4.REG_ASSET_PROT_MGR_EMAIL AS REG_ASSET_PROT_MGR_EMAIL,
        DECODE(TRUE,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 1,
        LKP_USR_DC_NAMES_19.DC_RLPM_EMAIL,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 2,
        LKP_USR_DC_NAMES_19.DC_RLPM_EMAIL,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 3,
        LKP_USR_DC_NAMES_19.DC_RLPM_EMAIL,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 4,
        LKP_USR_DC_NAMES_19.DC_RLPM_EMAIL,
        LKP_USR_DISTRICT_NAMES_24.LP_SAFETY_EMAIL) AS o_REGIONAL_LP_SAFETY_MGR_EMAIL,
        LKP_USR_DC_NAMES_19.DC_RLPM_EMAIL AS DC_RLPM_EMAIL,
        LKP_USR_DISTRICT_NAMES_24.LP_SAFETY_NAME AS LP_SAFETY_NAME,
        LKP_USR_DISTRICT_NAMES_24.LP_SAFETY_EMAIL AS LP_SAFETY_EMAIL,
        JNR_Detail_Outer_Join_4.RETAIL_MANAGER_SAFETY_NAME AS RETAIL_MANAGER_SAFETY_NAME,
        JNR_Detail_Outer_Join_4.RETAIL_MANAGER_SAFETY_EMAIL AS RETAIL_MANAGER_SAFETY_EMAIL,
        JNR_Detail_Outer_Join_4.DC_GENERAL_MANAGER_NAME AS DC_GENERAL_MANAGER_NAME,
        JNR_Detail_Outer_Join_4.DC_GENERAL_MANAGER_EMAIL AS DC_GENERAL_MANAGER_EMAIL,
        JNR_Detail_Outer_Join_4.ASST_DC_GENERAL_MANAGER_NAME1 AS ASST_DC_GENERAL_MANAGER_NAME1,
        JNR_Detail_Outer_Join_4.ASST_DC_GENERAL_MANAGER_EMAIL1 AS ASST_DC_GENERAL_MANAGER_EMAIL1,
        JNR_Detail_Outer_Join_4.ASST_DC_GENERAL_MANAGER_NAME2 AS ASST_DC_GENERAL_MANAGER_NAME2,
        JNR_Detail_Outer_Join_4.ASST_DC_GENERAL_MANAGER_EMAIL2 AS ASST_DC_GENERAL_MANAGER_EMAIL2,
        JNR_Detail_Outer_Join_4.PEOPLE_MANAGER_NAME AS PEOPLE_MANAGER_NAME,
        JNR_Detail_Outer_Join_4.PEOPLE_MANAGER_EMAIL AS PEOPLE_MANAGER_EMAIL,
        JNR_Detail_Outer_Join_4.DC_PEOPLE_SUPERVISOR_NAME AS DC_PEOPLE_SUPERVISOR_NAME,
        JNR_Detail_Outer_Join_4.DC_PEOPLE_SUPERVISOR_EMAIL AS DC_PEOPLE_SUPERVISOR_EMAIL,
        LKP_USR_DISTRICT_NAMES_24.HR_SUPER_NAME AS HR_SUPER_NAME,
        DECODE(TRUE,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 1,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER1_NAME,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 2,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER1_NAME,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 3,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER1_NAME,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 4,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER1_NAME,
        LKP_USR_DISTRICT_NAMES_24.HR_SUPER_NAME) AS HR_SUPERVISOR_NAME1,
        LKP_USR_DISTRICT_NAMES_24.HR_SUPER_EMAIL AS HR_SUPER_EMAIL,
        DECODE(TRUE,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 1,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER1_EMAIL,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 2,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER1_EMAIL,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 3,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER1_EMAIL,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 4,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER1_EMAIL,
        LKP_USR_DISTRICT_NAMES_24.HR_SUPER_EMAIL) AS HR_SUPERVISOR_EMAIL1,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER2_NAME AS DC_HR_SUPER2_NAME,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER2_EMAIL AS DC_HR_SUPER2_EMAIL,
        DECODE(TRUE,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 1,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER2_NAME,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 2,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER2_NAME,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 3,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER2_NAME,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 4,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER2_NAME,
        '') AS HR_SUPERVISOR_NAME2,
        DECODE(TRUE,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 1,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER2_EMAIL,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 2,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER2_EMAIL,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 3,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER2_EMAIL,
        JNR_Detail_Outer_Join_4.LOCATION_TYPE_ID = 4,
        LKP_USR_DC_NAMES_19.DC_HR_SUPER2_EMAIL,
        '') AS HR_SUPERVISOR_EMAIL2,
        LKP_USR_REGION_NAMES_22.LEARN_SOLUTION_MGR_NAME AS LEARN_SOLUTION_MGR_NAME,
        LKP_USR_REGION_NAMES_22.LEARN_SOLUTION_MGR_EMAIL AS LEARN_SOLUTION_MGR_EMAIL,
        JNR_Detail_Outer_Join_4.ADD_DT AS ADD_DT,
        JNR_Detail_Outer_Join_4.DELETE_DT AS DELETE_DT,
        JNR_Detail_Outer_Join_4.UPDATE_DT AS UPDATE_DT,
        JNR_Detail_Outer_Join_4.LOAD_DT AS LOAD_DT,
        JNR_Detail_Outer_Join_4.EMPL_FIRST_NAME AS EMPL_FIRST_NAME,
        JNR_Detail_Outer_Join_4.EMPL_LAST_NAME AS EMPL_LAST_NAME,
        LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        LKP_LOYALTY_PGM_STATUS_29 
    INNER JOIN
        LKP_EQUINE_SITE_28 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_EQUINE_SITE_28.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_USR_DISTRICT_NAMES_24 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_USR_DISTRICT_NAMES_24.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_REGION_27 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_REGION_27.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_PETSMART_DMA_26 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_PETSMART_DMA_26.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_LOYALTY_PGM_TYPE_25 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_LOYALTY_PGM_TYPE_25.Monotonically_Increasing_Id 
    INNER JOIN
        EXP_Conv_21 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = EXP_Conv_21.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_PRICE_AD_ZONE_20 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_PRICE_AD_ZONE_20.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_USR_DC_NAMES_19 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_USR_DC_NAMES_19.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_STORE_TIME_ZONE_18 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_STORE_TIME_ZONE_18.Monotonically_Increasing_Id 
    INNER JOIN
        JNR_Detail_Outer_Join_4 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_STORE_TYPE_5 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_STORE_TYPE_5.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_DISTRICT_6 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_DISTRICT_6.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_SLSCMP_STORE_7 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_SLSCMP_STORE_7.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_LOCATION_TYPE_8 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_LOCATION_TYPE_8.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_COUNTRY_13 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_COUNTRY_13.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_STATE_15 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_STATE_15.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_EQUINE_MERCH_16 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_EQUINE_MERCH_16.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_DM_PG_MGR_DVL_23 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_DM_PG_MGR_DVL_23.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_PRICE_ZONE_17 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_PRICE_ZONE_17.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_SALES_RANKING_WK_9 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_SALES_RANKING_WK_9.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_USR_REGION_NAMES_22 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_USR_REGION_NAMES_22.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_SUPER_REGION_11 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_SUPER_REGION_11.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_COMPANY_12 
            ON LKP_LOYALTY_PGM_STATUS_29.Monotonically_Increasing_Id = LKP_COMPANY_12.Monotonically_Increasing_Id""")

df_30.createOrReplaceTempView("EXP_Remove_30")

# COMMAND ----------
# DBTITLE 1, SITE_PROFILE_RPT


spark.sql("""INSERT INTO SITE_PROFILE_RPT SELECT LOCATION_ID AS LOCATION_ID,
LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
o_LOCATION_TYPE_DESC AS LOCATION_TYPE_DESC,
STORE_NBR1 AS STORE_NBR,
o_STORE_NAME AS STORE_NAME,
STORE_TYPE_ID AS STORE_TYPE_ID,
o_STORE_TYPE_DESC AS STORE_TYPE_DESC,
PARENT_LOCATION_ID AS PARENT_LOCATION_ID,
LOCATION_NBR AS LOCATION_NBR,
COMPANY_ID AS COMPANY_ID,
o_COMPANY_DESC AS COMPANY_DESC,
SUPER_REGION_ID AS SUPER_REGION_ID,
SUPER_REGION_DESC AS SUPER_REGION_DESC,
REGION_ID AS REGION_ID,
o_REGION_DESC AS REGION_DESC,
DISTRICT_ID AS DISTRICT_ID,
o_DISTRICT_DESC AS DISTRICT_DESC,
SITE_ADDRESS AS SITE_ADDRESS,
o_SITE_CITY AS SITE_CITY,
o_SITE_COUNTY AS SITE_COUNTY,
STATE_CD AS STATE_CD,
o_STATE_NAME AS STATE_NAME,
POSTAL_CD AS POSTAL_CD,
COUNTRY_CD AS COUNTRY_CD,
o_COUNTRY_NAME AS COUNTRY_NAME,
GEO_LATITUDE_NBR AS GEO_LATITUDE_NBR,
GEO_LONGITUDE_NBR AS GEO_LONGITUDE_NBR,
PETSMART_DMA_CD AS PETSMART_DMA_CD,
o_PETSMART_DMA_DESC AS PETSMART_DMA_DESC,
SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
SITE_FAX_NO AS SITE_FAX_NO,
o_SITE_EMAIL_ADDRESS AS SITE_EMAIL_ADDRESS,
STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
SFT_OPEN_DT AS SFT_OPEN_DT,
OPEN_DT AS OPEN_DT,
GR_OPEN_DT AS GR_OPEN_DT,
CLOSE_DT AS CLOSE_DT,
SITE_SALES_FLAG AS SITE_SALES_FLAG,
SALES_CURR_FLAG AS SALES_CURR_FLAG,
SITE_OPEN_YRS_AMT AS SITE_OPEN_YRS_AMT,
FIRST_SALE_DT AS FIRST_SALE_DT,
FIRST_MEASURED_SALE_DT AS FIRST_MEASURED_SALE_DT,
LAST_SALE_DT AS LAST_SALE_DT,
COMP_CURR_FLAG AS COMP_CURR_FLAG,
COMP_EFF_DT AS COMP_EFF_DT,
COMP_END_DT AS COMP_END_DT,
TP_LOC_FLAG AS TP_LOC_FLAG,
TP_ACTIVE_CNT AS TP_ACTIVE_CNT,
TP_START_DT AS TP_START_DT,
HOTEL_FLAG AS HOTEL_FLAG,
HOTEL_OPEN_DT AS HOTEL_OPEN_DT,
DAYCAMP_FLAG AS DAYCAMP_FLAG,
VET_FLAG AS VET_FLAG,
o_TIME_ZONE_ID AS TIME_ZONE_ID,
o_TIME_ZONE AS TIME_ZONE,
SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
TRADE_AREA AS TRADE_AREA,
DELV_SERVICE_CLASS_ID AS DELV_SERVICE_CLASS_ID,
PICK_SERVICE_CLASS_ID AS PICK_SERVICE_CLASS_ID,
REPL_DC_NBR AS REPL_DC_NBR,
REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
PROMO_LABEL_CD AS PROMO_LABEL_CD,
PRICE_ZONE_ID AS PRICE_ZONE_ID,
o_PRICE_ZONE_DESC AS PRICE_ZONE_DESC,
PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
o_PRICE_AD_ZONE_DESC AS PRICE_AD_ZONE_DESC,
EQUINE_MERCH_ID AS EQUINE_MERCH_ID,
o_EQUINE_MERCH_DESC AS EQUINE_MERCH_DESC,
EQUINE_SITE_ID AS EQUINE_SITE_ID,
o_EQUINE_SITE_DESC AS EQUINE_SITE_DESC,
EQUINE_SITE_OPEN_DT AS EQUINE_SITE_OPEN_DT,
LOYALTY_PGM_TYPE_ID AS LOYALTY_PGM_TYPE_ID,
o_LOYALTY_PGM_TYPE_DESC AS LOYALTY_PGM_TYPE_DESC,
LOYALTY_PGM_STATUS_ID AS LOYALTY_PGM_STATUS_ID,
o_LOYALTY_PGM_STATUS_DESC AS LOYALTY_PGM_STATUS_DESC,
LOYALTY_PGM_START_DT AS LOYALTY_PGM_START_DT,
LOYALTY_PGM_CHANGE_DT AS LOYALTY_PGM_CHANGE_DT,
BP_COMPANY_NBR AS BP_COMPANY_NBR,
BP_GL_ACCT AS BP_GL_ACCT,
SITE_LOGIN_ID AS SITE_LOGIN_ID,
o_SITE_MANAGER_ID AS SITE_MANAGER_ID,
SITE_MANAGER_NAME AS SITE_MANAGER_NAME,
MGR_ID AS MGR_ID,
o_MGR_DESC AS MGR_DESC,
DVL_ID AS DVL_ID,
o_DVL_DESC AS DVL_DESC,
PURCH_GROUP_ID AS PURCH_GROUP_ID,
PURCH_GROUP_NAME AS PURCH_GROUP_NAME,
TOTAL_SALES_RANKING_CD AS TOTAL_SALES_RANKING_CD,
MERCH_SALES_RANKING_CD AS MERCH_SALES_RANKING_CD,
SERVICES_SALES_RANKING_CD AS SERVICES_SALES_RANKING_CD,
SALON_SALES_RANKING_CD AS SALON_SALES_RANKING_CD,
TRAINING_SALES_RANKING_CD AS TRAINING_SALES_RANKING_CD,
HOTEL_DDC_SALES_RANKING_CD AS HOTEL_DDC_SALES_RANKING_CD,
CONSUMABLES_SALES_RANKING_CD AS CONSUMABLES_SALES_RANKING_CD,
HARDGOODS_SALES_RANKING_CD AS HARDGOODS_SALES_RANKING_CD,
SPECIALTY_SALES_RANKING_CD AS SPECIALTY_SALES_RANKING_CD,
DIST_MGR_NAME AS DIST_MGR_NAME,
DM_EMAIL_ADDRESS AS DM_EMAIL_ADDRESS,
AREA_DIRECTOR_NAME AS DC_AREA_DIRECTOR_NAME,
AREA_DIRECTOR_EMAIL AS DC_AREA_DIRECTOR_EMAIL,
DIST_SVC_MGR_NAME AS DIST_SVC_MGR_NAME,
DSM_EMAIL_ADDRESS AS DSM_EMAIL_ADDRESS,
REGION_VP_NAME AS REGION_VP_NAME,
RVP_EMAIL_ADDRESS AS RVP_EMAIL_ADDRESS,
REGION_TRAINER_NAME AS REGION_TRAINER_NAME,
ASSET_PROTECT_NAME AS ASSET_PROTECT_NAME,
ASSET_PROTECT_EMAIL AS ASSET_PROTECT_EMAIL,
SAFETY_DIRECTOR_NAME AS LP_SAFETY_DIRECTOR_NAME,
SAFETY_DIRECTOR_EMAIL AS LP_SAFETY_DIRECTOR_EMAIL,
SR_LP_SAFETY_MGR_NAME AS SR_LP_SAFETY_MGR_NAME,
SR_LP_SAFETY_MGR_EMAIL AS SR_LP_SAFETY_MGR_EMAIL,
o_REGIONAL_LP_SAFETY_MGR_NAME AS REGIONAL_LP_SAFETY_MGR_NAME,
o_REGIONAL_LP_SAFETY_MGR_EMAIL AS REGIONAL_LP_SAFETY_MGR_EMAIL,
RETAIL_MANAGER_SAFETY_NAME AS RETAIL_MANAGER_SAFETY_NAME,
RETAIL_MANAGER_SAFETY_EMAIL AS RETAIL_MANAGER_SAFETY_EMAIL,
DC_GENERAL_MANAGER_NAME AS DC_GENERAL_MANAGER_NAME,
DC_GENERAL_MANAGER_EMAIL AS DC_GENERAL_MANAGER_EMAIL,
ASST_DC_GENERAL_MANAGER_NAME1 AS ASST_DC_GENERAL_MANAGER_NAME1,
ASST_DC_GENERAL_MANAGER_EMAIL1 AS ASST_DC_GENERAL_MANAGER_EMAIL1,
ASST_DC_GENERAL_MANAGER_NAME2 AS ASST_DC_GENERAL_MANAGER_NAME2,
ASST_DC_GENERAL_MANAGER_EMAIL2 AS ASST_DC_GENERAL_MANAGER_EMAIL2,
PEOPLE_MANAGER_NAME AS HR_MANAGER_NAME,
PEOPLE_MANAGER_EMAIL AS HR_MANAGER_EMAIL,
HR_SUPERVISOR_NAME1 AS HR_SUPERVISOR_NAME1,
HR_SUPERVISOR_EMAIL1 AS HR_SUPERVISOR_EMAIL1,
HR_SUPERVISOR_NAME2 AS HR_SUPERVISOR_NAME2,
HR_SUPERVISOR_EMAIL2 AS HR_SUPERVISOR_EMAIL2,
LEARN_SOLUTION_MGR_NAME AS LEARN_SOLUTION_MGR_NAME,
LEARN_SOLUTION_MGR_EMAIL AS LEARN_SOLUTION_MGR_EMAIL,
ADD_DT AS ADD_DT,
DELETE_DT AS DELETE_DT,
UPDATE_DT AS UPDATE_DT,
LOAD_DT AS LOAD_DT FROM EXP_Remove_30""")