# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")


# COMMAND ----------

# DBTITLE 1, USR_DC_NAMES_0

df_0=spark.sql("""
    SELECT
        STORE_NBR AS STORE_NBR,
        DC_RLPM_NAME AS DC_RLPM_NAME,
        DC_RLPM_EMAIL AS DC_RLPM_EMAIL,
        DC_ASST_GM1_NAME AS DC_ASST_GM1_NAME,
        DC_ASST_GM1_EMAIL AS DC_ASST_GM1_EMAIL,
        DC_ASST_GM2_NAME AS DC_ASST_GM2_NAME,
        DC_ASST_GM2_EMAIL AS DC_ASST_GM2_EMAIL,
        DC_GM_NAME AS DC_GM_NAME,
        DC_GM_EMAIL AS DC_GM_EMAIL,
        DC_HR_SUPER1_NAME AS DC_HR_SUPER1_NAME,
        DC_HR_SUPER1_EMAIL AS DC_HR_SUPER1_EMAIL,
        DC_HR_SUPER2_NAME AS DC_HR_SUPER2_NAME,
        DC_HR_SUPER2_EMAIL AS DC_HR_SUPER2_EMAIL,
        DC_HR_MGR_NAME AS DC_HR_MGR_NAME,
        DC_HR_MGR_EMAIL AS DC_HR_MGR_EMAIL,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        USR_DC_NAMES""")

df_0.createOrReplaceTempView("USR_DC_NAMES_0")

# COMMAND ----------

# DBTITLE 1, SQ_USR_DC_NAMES_1

df_1=spark.sql("""
    SELECT
        store_nbr,
        UPPER(LTRIM(RTRIM(DC_GM_EMAIL))) AS DC_GM_EMAIL 
    FROM
        usr_dc_names""")

df_1.createOrReplaceTempView("SQ_USR_DC_NAMES_1")

# COMMAND ----------

# DBTITLE 1, EMPLOYEE_PROFILE_2

df_2=spark.sql("""
    SELECT
        EMPLOYEE_ID AS EMPLOYEE_ID,
        EMPL_FIRST_NAME AS EMPL_FIRST_NAME,
        EMPL_MIDDLE_NAME AS EMPL_MIDDLE_NAME,
        EMPL_LAST_NAME AS EMPL_LAST_NAME,
        EMPL_BIRTH_DT AS EMPL_BIRTH_DT,
        GENDER_CD AS GENDER_CD,
        PS_MARITAL_STATUS_CD AS PS_MARITAL_STATUS_CD,
        ETHNIC_GROUP_ID AS ETHNIC_GROUP_ID,
        EMPL_ADDR_1 AS EMPL_ADDR_1,
        EMPL_ADDR_2 AS EMPL_ADDR_2,
        EMPL_CITY AS EMPL_CITY,
        EMPL_STATE AS EMPL_STATE,
        EMPL_PROVINCE AS EMPL_PROVINCE,
        EMPL_ZIPCODE AS EMPL_ZIPCODE,
        COUNTRY_CD AS COUNTRY_CD,
        EMPL_HOME_PHONE AS EMPL_HOME_PHONE,
        EMPL_EMAIL_ADDR AS EMPL_EMAIL_ADDR,
        EMPL_LOGIN_ID AS EMPL_LOGIN_ID,
        BADGE_NBR AS BADGE_NBR,
        EMPL_STATUS_CD AS EMPL_STATUS_CD,
        STATUS_CHG_DT AS STATUS_CHG_DT,
        FULLPT_FLAG AS FULLPT_FLAG,
        FULLPT_CHG_DT AS FULLPT_CHG_DT,
        EMPL_TYPE_CD AS EMPL_TYPE_CD,
        PS_REG_TEMP_CD AS PS_REG_TEMP_CD,
        EMPL_CATEGORY_CD AS EMPL_CATEGORY_CD,
        EMPL_GROUP_CD AS EMPL_GROUP_CD,
        EMPL_SUBGROUP_CD AS EMPL_SUBGROUP_CD,
        EMPL_HIRE_DT AS EMPL_HIRE_DT,
        EMPL_REHIRE_DT AS EMPL_REHIRE_DT,
        EMPL_TERM_DT AS EMPL_TERM_DT,
        TERM_REASON_CD AS TERM_REASON_CD,
        EMPL_SENORITY_DT AS EMPL_SENORITY_DT,
        PS_ACTION_DT AS PS_ACTION_DT,
        PS_ACTION_CD AS PS_ACTION_CD,
        PS_ACTION_REASON_CD AS PS_ACTION_REASON_CD,
        LOCATION_ID AS LOCATION_ID,
        LOCATION_CHG_DT AS LOCATION_CHG_DT,
        STORE_NBR AS STORE_NBR,
        STORE_DEPT_NBR AS STORE_DEPT_NBR,
        COMPANY_ID AS COMPANY_ID,
        PS_PERSONNEL_AREA_ID AS PS_PERSONNEL_AREA_ID,
        PS_PERSONNEL_SUBAREA_ID AS PS_PERSONNEL_SUBAREA_ID,
        PS_DEPT_CD AS PS_DEPT_CD,
        PS_DEPT_CHG_DT AS PS_DEPT_CHG_DT,
        PS_POSITION_ID AS PS_POSITION_ID,
        POSITION_CHG_DT AS POSITION_CHG_DT,
        PS_SUPERVISOR_ID AS PS_SUPERVISOR_ID,
        JOB_CODE AS JOB_CODE,
        JOB_CODE_CHG_DT AS JOB_CODE_CHG_DT,
        EMPL_JOB_ENTRY_DT AS EMPL_JOB_ENTRY_DT,
        PS_GRADE_ID AS PS_GRADE_ID,
        EMPL_STD_BONUS_PCT AS EMPL_STD_BONUS_PCT,
        EMPL_OVR_BONUS_PCT AS EMPL_OVR_BONUS_PCT,
        EMPL_RATING AS EMPL_RATING,
        PAY_RATE_CHG_DT AS PAY_RATE_CHG_DT,
        PS_PAYROLL_AREA_CD AS PS_PAYROLL_AREA_CD,
        PS_TAX_COMPANY_CD AS PS_TAX_COMPANY_CD,
        PS_COMP_FREQ_CD AS PS_COMP_FREQ_CD,
        COMP_RATE_AMT AS COMP_RATE_AMT,
        ANNUAL_RATE_LOC_AMT AS ANNUAL_RATE_LOC_AMT,
        HOURLY_RATE_LOC_AMT AS HOURLY_RATE_LOC_AMT,
        CURRENCY_ID AS CURRENCY_ID,
        EXCH_RATE_PCT AS EXCH_RATE_PCT,
        LOAD_TSTMP AS LOAD_TSTMP,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        EMPLOYEE_PROFILE""")

df_2.createOrReplaceTempView("EMPLOYEE_PROFILE_2")

# COMMAND ----------

# DBTITLE 1, ASQ_Shortcut_to_EMPLOYEE_PROFILE_3

df_3=spark.sql("""
    SELECT
        sep.employee_id,
        sorg.location_id 
    FROM
        (SELECT
            h0.objid,
            h0.otype,
            h0.short,
            h0.stext,
            h0.begda,
            h0.endda,
            l.location_id 
        FROM
            sap_hrp1000_hist h0,
            site_profile L 
        WHERE
            h0.otype = 'O' 
            AND h0.plvar = '01' 
            AND h0.istat = '1' 
            AND h0.endda = TO_DATE('12319999', 'MMDDYYYY') 
            AND h0.short LIKE 'STR%' 
            AND SUBSTR(h0.short, 5, 4) = l.store_nbr) SORG 
    JOIN
        (
            SELECT
                sh1.objid,
                sh1.otype,
                sh1.sobid,
                sh0.short,
                sh0.stext,
                sh0.begda,
                sh0.endda 
            FROM
                sap_hrp1001_hist SH1,
                sap_hrp1000_hist SH0 
            WHERE
                sh1.otype = 'O' 
                AND sh1.plvar = '01' 
                AND sh1.istat = '1' 
                AND sh1.rsign = 'B' 
                AND sh1.relat = '012' 
                AND sh1.endda = TO_DATE('12319999', 'MMDDYYYY') 
                AND sh1.sobid = sh0.objid 
                AND sh0.endda = TO_DATE('12319999', 'MMDDYYYY')
        ) SPOS 
            ON sorg.objid = spos.objid 
    LEFT OUTER JOIN
        employee_profile SEP 
            ON spos.sobid = sep.ps_position_id 
    ORDER BY
        1""")

df_3.createOrReplaceTempView("ASQ_Shortcut_to_EMPLOYEE_PROFILE_3")

# COMMAND ----------

# DBTITLE 1, UPD_MANAGER_ID_4

df_4=spark.sql("""
    SELECT
        EMPLOYEE_ID AS EMPLOYEE_ID,
        LOCATION_ID AS LOCATION_ID,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        ASQ_Shortcut_to_EMPLOYEE_PROFILE_3""")

df_4.createOrReplaceTempView("UPD_MANAGER_ID_4")

# COMMAND ----------

# DBTITLE 1, ASQ_Shortcut_to_EMPLOYEE_PROFILE1_5

df_5=spark.sql("""
    SELECT
        employee_id,
        UPPER(TRIM(EMPL_EMAIL_ADDR)) AS EMPL_EMAIL_ADDR 
    FROM
        employee_profile""")

df_5.createOrReplaceTempView("ASQ_Shortcut_to_EMPLOYEE_PROFILE1_5")

# COMMAND ----------

# DBTITLE 1, JNRTRANS_6

df_6=spark.sql("""
    SELECT
        DETAIL.EMPLOYEE_ID AS EMPLOYEE_ID,
        DETAIL.EMPL_EMAIL_ADDR AS EMPL_EMAIL_ADDR,
        MASTER.STORE_NBR AS STORE_NBR,
        MASTER.DC_GM_EMAIL AS DC_GM_EMAIL,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_USR_DC_NAMES_1 MASTER 
    INNER JOIN
        ASQ_Shortcut_to_EMPLOYEE_PROFILE1_5 DETAIL 
            ON MASTER.DC_GM_EMAIL = DETAIL.EMPL_EMAIL_ADDR""")

df_6.createOrReplaceTempView("JNRTRANS_6")

# COMMAND ----------

# DBTITLE 1, SITE_PROFILE_7

df_7=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
        STORE_NBR AS STORE_NBR,
        STORE_NAME AS STORE_NAME,
        STORE_TYPE_ID AS STORE_TYPE_ID,
        STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
        COMPANY_ID AS COMPANY_ID,
        REGION_ID AS REGION_ID,
        DISTRICT_ID AS DISTRICT_ID,
        PRICE_ZONE_ID AS PRICE_ZONE_ID,
        PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
        REPL_DC_NBR AS REPL_DC_NBR,
        REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
        REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
        SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
        SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
        SITE_ADDRESS AS SITE_ADDRESS,
        SITE_CITY AS SITE_CITY,
        STATE_CD AS STATE_CD,
        COUNTRY_CD AS COUNTRY_CD,
        POSTAL_CD AS POSTAL_CD,
        SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
        SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
        SITE_EMAIL_ADDRESS AS SITE_EMAIL_ADDRESS,
        SITE_SALES_FLAG AS SITE_SALES_FLAG,
        EQUINE_MERCH_ID AS EQUINE_MERCH_ID,
        EQUINE_SITE_ID AS EQUINE_SITE_ID,
        EQUINE_SITE_OPEN_DT AS EQUINE_SITE_OPEN_DT,
        GEO_LATITUDE_NBR AS GEO_LATITUDE_NBR,
        GEO_LONGITUDE_NBR AS GEO_LONGITUDE_NBR,
        PETSMART_DMA_CD AS PETSMART_DMA_CD,
        LOYALTY_PGM_TYPE_ID AS LOYALTY_PGM_TYPE_ID,
        LOYALTY_PGM_STATUS_ID AS LOYALTY_PGM_STATUS_ID,
        LOYALTY_PGM_START_DT AS LOYALTY_PGM_START_DT,
        LOYALTY_PGM_CHANGE_DT AS LOYALTY_PGM_CHANGE_DT,
        BP_COMPANY_NBR AS BP_COMPANY_NBR,
        BP_GL_ACCT AS BP_GL_ACCT,
        TP_LOC_FLAG AS TP_LOC_FLAG,
        TP_ACTIVE_CNT AS TP_ACTIVE_CNT,
        PROMO_LABEL_CD AS PROMO_LABEL_CD,
        PARENT_LOCATION_ID AS PARENT_LOCATION_ID,
        LOCATION_NBR AS LOCATION_NBR,
        TIME_ZONE_ID AS TIME_ZONE_ID,
        DELV_SERVICE_CLASS_ID AS DELV_SERVICE_CLASS_ID,
        PICK_SERVICE_CLASS_ID AS PICK_SERVICE_CLASS_ID,
        SITE_LOGIN_ID AS SITE_LOGIN_ID,
        SITE_MANAGER_ID AS SITE_MANAGER_ID,
        SITE_OPEN_YRS_AMT AS SITE_OPEN_YRS_AMT,
        HOTEL_FLAG AS HOTEL_FLAG,
        DAYCAMP_FLAG AS DAYCAMP_FLAG,
        VET_FLAG AS VET_FLAG,
        DIST_MGR_NAME AS DIST_MGR_NAME,
        DIST_SVC_MGR_NAME AS DIST_SVC_MGR_NAME,
        REGION_VP_NAME AS REGION_VP_NAME,
        REGION_TRAINER_NAME AS REGION_TRAINER_NAME,
        ASSET_PROTECT_NAME AS ASSET_PROTECT_NAME,
        SITE_COUNTY AS SITE_COUNTY,
        SITE_FAX_NO AS SITE_FAX_NO,
        SFT_OPEN_DT AS SFT_OPEN_DT,
        DM_EMAIL_ADDRESS AS DM_EMAIL_ADDRESS,
        DSM_EMAIL_ADDRESS AS DSM_EMAIL_ADDRESS,
        RVP_EMAIL_ADDRESS AS RVP_EMAIL_ADDRESS,
        TRADE_AREA AS TRADE_AREA,
        FDLPS_NAME AS FDLPS_NAME,
        FDLPS_EMAIL AS FDLPS_EMAIL,
        OVERSITE_MGR_NAME AS OVERSITE_MGR_NAME,
        OVERSITE_MGR_EMAIL AS OVERSITE_MGR_EMAIL,
        SAFETY_DIRECTOR_NAME AS SAFETY_DIRECTOR_NAME,
        SAFETY_DIRECTOR_EMAIL AS SAFETY_DIRECTOR_EMAIL,
        RETAIL_MANAGER_SAFETY_NAME AS RETAIL_MANAGER_SAFETY_NAME,
        RETAIL_MANAGER_SAFETY_EMAIL AS RETAIL_MANAGER_SAFETY_EMAIL,
        AREA_DIRECTOR_NAME AS AREA_DIRECTOR_NAME,
        AREA_DIRECTOR_EMAIL AS AREA_DIRECTOR_EMAIL,
        DC_GENERAL_MANAGER_NAME AS DC_GENERAL_MANAGER_NAME,
        DC_GENERAL_MANAGER_EMAIL AS DC_GENERAL_MANAGER_EMAIL,
        ASST_DC_GENERAL_MANAGER_NAME1 AS ASST_DC_GENERAL_MANAGER_NAME1,
        ASST_DC_GENERAL_MANAGER_EMAIL1 AS ASST_DC_GENERAL_MANAGER_EMAIL1,
        ASST_DC_GENERAL_MANAGER_NAME2 AS ASST_DC_GENERAL_MANAGER_NAME2,
        ASST_DC_GENERAL_MANAGER_EMAIL2 AS ASST_DC_GENERAL_MANAGER_EMAIL2,
        REGIONAL_DC_SAFETY_MGR_NAME AS REGIONAL_DC_SAFETY_MGR_NAME,
        REGIONAL_DC_SAFETY_MGR_EMAIL AS REGIONAL_DC_SAFETY_MGR_EMAIL,
        DC_PEOPLE_SUPERVISOR_NAME AS DC_PEOPLE_SUPERVISOR_NAME,
        DC_PEOPLE_SUPERVISOR_EMAIL AS DC_PEOPLE_SUPERVISOR_EMAIL,
        PEOPLE_MANAGER_NAME AS PEOPLE_MANAGER_NAME,
        PEOPLE_MANAGER_EMAIL AS PEOPLE_MANAGER_EMAIL,
        ASSET_PROT_DIR_NAME AS ASSET_PROT_DIR_NAME,
        ASSET_PROT_DIR_EMAIL AS ASSET_PROT_DIR_EMAIL,
        SR_REG_ASSET_PROT_MGR_NAME AS SR_REG_ASSET_PROT_MGR_NAME,
        SR_REG_ASSET_PROT_MGR_EMAIL AS SR_REG_ASSET_PROT_MGR_EMAIL,
        REG_ASSET_PROT_MGR_NAME AS REG_ASSET_PROT_MGR_NAME,
        REG_ASSET_PROT_MGR_EMAIL AS REG_ASSET_PROT_MGR_EMAIL,
        ASSET_PROTECT_EMAIL AS ASSET_PROTECT_EMAIL,
        TP_START_DT AS TP_START_DT,
        OPEN_DT AS OPEN_DT,
        GR_OPEN_DT AS GR_OPEN_DT,
        CLOSE_DT AS CLOSE_DT,
        HOTEL_OPEN_DT AS HOTEL_OPEN_DT,
        ADD_DT AS ADD_DT,
        DELETE_DT AS DELETE_DT,
        UPDATE_DT AS UPDATE_DT,
        LOAD_DT AS LOAD_DT,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        SITE_PROFILE""")

df_7.createOrReplaceTempView("SITE_PROFILE_7")

# COMMAND ----------

# DBTITLE 1, SQ_Shortcut_to_SITE_PROFILE_8

df_8=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        STORE_NBR AS STORE_NBR,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SITE_PROFILE_7""")

df_8.createOrReplaceTempView("SQ_Shortcut_to_SITE_PROFILE_8")

# COMMAND ----------

# DBTITLE 1, JNRTRANS1_9

df_9=spark.sql("""
    SELECT
        DETAIL.LOCATION_ID AS LOCATION_ID,
        DETAIL.STORE_NBR AS STORE_NBR,
        MASTER.EMPLOYEE_ID AS EMPLOYEE_ID,
        MASTER.STORE_NBR AS STORE_NBR1,
        MASTER.DC_GM_EMAIL AS DC_GM_EMAIL,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNRTRANS_6 MASTER 
    INNER JOIN
        SQ_Shortcut_to_SITE_PROFILE_8 DETAIL 
            ON MASTER.STORE_NBR = DETAIL.STORE_NBR""")

df_9.createOrReplaceTempView("JNRTRANS1_9")

# COMMAND ----------

# DBTITLE 1, UPD_MANAGER_ID1_10

df_10=spark.sql("""
    SELECT
        EMPLOYEE_ID AS EMPLOYEE_ID,
        LOCATION_ID AS LOCATION_ID,
        DC_GM_EMAIL AS DC_GM_EMAIL,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNRTRANS1_9""")

df_10.createOrReplaceTempView("UPD_MANAGER_ID1_10")

# COMMAND ----------

# DBTITLE 1, SITE_PROFILE

spark.sql("""INSERT INTO SITE_PROFILE SELECT LOCATION_ID AS LOCATION_ID,
LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
STORE_NBR AS STORE_NBR,
VENDOR_NAME AS STORE_NAME,
STORE_TYPE_ID AS STORE_TYPE_ID,
STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
COMPANY_ID AS COMPANY_ID,
REGION_ID AS REGION_ID,
DISTRICT_ID AS DISTRICT_ID,
PRICE_ZONE_ID AS PRICE_ZONE_ID,
PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
REPL_DC_NBR AS REPL_DC_NBR,
REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
ADDRESS AS SITE_ADDRESS,
CITY AS SITE_CITY,
STATE AS STATE_CD,
COUNTRY_CD AS COUNTRY_CD,
ZIP AS POSTAL_CD,
PHONE AS SITE_MAIN_TELE_NO,
SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
SITE_EMAIL_ADDRESS AS SITE_EMAIL_ADDRESS,
SITE_SALES_FLAG AS SITE_SALES_FLAG,
EQUINE_MERCH_ID AS EQUINE_MERCH_ID,
EQUINE_SITE_ID AS EQUINE_SITE_ID,
EQUINE_SITE_OPEN_DT AS EQUINE_SITE_OPEN_DT,
GEO_LATITUDE_NBR AS GEO_LATITUDE_NBR,
GEO_LONGITUDE_NBR AS GEO_LONGITUDE_NBR,
PETSMART_DMA_CD AS PETSMART_DMA_CD,
LOYALTY_PGM_TYPE_ID AS LOYALTY_PGM_TYPE_ID,
LOYALTY_PGM_STATUS_ID AS LOYALTY_PGM_STATUS_ID,
LOYALTY_PGM_START_DT AS LOYALTY_PGM_START_DT,
LOYALTY_PGM_CHANGE_DT AS LOYALTY_PGM_CHANGE_DT,
BP_COMPANY_NBR AS BP_COMPANY_NBR,
BP_GL_ACCT AS BP_GL_ACCT,
TP_LOC_FLAG AS TP_LOC_FLAG,
TP_ACTIVE_CNT AS TP_ACTIVE_CNT,
PROMO_LABEL_CD AS PROMO_LABEL_CD,
PARENT_VENDOR_ID AS PARENT_LOCATION_ID,
VENDOR_NBR AS LOCATION_NBR,
TIME_ZONE_ID AS TIME_ZONE_ID,
DELV_SERVICE_CLASS_ID AS DELV_SERVICE_CLASS_ID,
PICK_SERVICE_CLASS_ID AS PICK_SERVICE_CLASS_ID,
SITE_LOGIN_ID AS SITE_LOGIN_ID,
SITE_MANAGER_ID AS SITE_MANAGER_ID,
SITE_OPEN_YRS_AMT AS SITE_OPEN_YRS_AMT,
HOTEL_FLAG AS HOTEL_FLAG,
DAYCAMP_FLAG AS DAYCAMP_FLAG,
VET_FLAG AS VET_FLAG,
DIST_MGR_NAME AS DIST_MGR_NAME,
DIST_SVC_MGR_NAME AS DIST_SVC_MGR_NAME,
REGION_VP_NAME AS REGION_VP_NAME,
REGION_TRAINER_NAME AS REGION_TRAINER_NAME,
ASSET_PROTECT_NAME AS ASSET_PROTECT_NAME,
SITE_COUNTY AS SITE_COUNTY,
SITE_FAX_NO AS SITE_FAX_NO,
SFT_OPEN_DT AS SFT_OPEN_DT,
DM_EMAIL_ADDRESS AS DM_EMAIL_ADDRESS,
DSM_EMAIL_ADDRESS AS DSM_EMAIL_ADDRESS,
RVP_EMAIL_ADDRESS AS RVP_EMAIL_ADDRESS,
TRADE_AREA AS TRADE_AREA,
FDLPS_NAME AS FDLPS_NAME,
FDLPS_EMAIL AS FDLPS_EMAIL,
OVERSITE_MGR_NAME AS OVERSITE_MGR_NAME,
OVERSITE_MGR_EMAIL AS OVERSITE_MGR_EMAIL,
SAFETY_DIRECTOR_NAME AS SAFETY_DIRECTOR_NAME,
SAFETY_DIRECTOR_EMAIL AS SAFETY_DIRECTOR_EMAIL,
RETAIL_MANAGER_SAFETY_NAME AS RETAIL_MANAGER_SAFETY_NAME,
RETAIL_MANAGER_SAFETY_EMAIL AS RETAIL_MANAGER_SAFETY_EMAIL,
AREA_DIRECTOR_NAME AS AREA_DIRECTOR_NAME,
AREA_DIRECTOR_EMAIL AS AREA_DIRECTOR_EMAIL,
DC_GENERAL_MANAGER_NAME AS DC_GENERAL_MANAGER_NAME,
DC_GENERAL_MANAGER_EMAIL AS DC_GENERAL_MANAGER_EMAIL,
ASST_DC_GENERAL_MANAGER_NAME1 AS ASST_DC_GENERAL_MANAGER_NAME1,
ASST_DC_GENERAL_MANAGER_EMAIL1 AS ASST_DC_GENERAL_MANAGER_EMAIL1,
ASST_DC_GENERAL_MANAGER_NAME2 AS ASST_DC_GENERAL_MANAGER_NAME2,
ASST_DC_GENERAL_MANAGER_EMAIL2 AS ASST_DC_GENERAL_MANAGER_EMAIL2,
REGIONAL_DC_SAFETY_MGR_NAME AS REGIONAL_DC_SAFETY_MGR_NAME,
REGIONAL_DC_SAFETY_MGR_EMAIL AS REGIONAL_DC_SAFETY_MGR_EMAIL,
DC_PEOPLE_SUPERVISOR_NAME AS DC_PEOPLE_SUPERVISOR_NAME,
DC_PEOPLE_SUPERVISOR_EMAIL AS DC_PEOPLE_SUPERVISOR_EMAIL,
PEOPLE_MANAGER_NAME AS PEOPLE_MANAGER_NAME,
PEOPLE_MANAGER_EMAIL AS PEOPLE_MANAGER_EMAIL,
ASSET_PROT_DIR_NAME AS ASSET_PROT_DIR_NAME,
ASSET_PROT_DIR_EMAIL AS ASSET_PROT_DIR_EMAIL,
SR_REG_ASSET_PROT_MGR_NAME AS SR_REG_ASSET_PROT_MGR_NAME,
SR_REG_ASSET_PROT_MGR_EMAIL AS SR_REG_ASSET_PROT_MGR_EMAIL,
REG_ASSET_PROT_MGR_NAME AS REG_ASSET_PROT_MGR_NAME,
REG_ASSET_PROT_MGR_EMAIL AS REG_ASSET_PROT_MGR_EMAIL,
ASSET_PROTECT_EMAIL AS ASSET_PROTECT_EMAIL,
TP_START_DT AS TP_START_DT,
OPEN_DT AS OPEN_DT,
GR_OPEN_DT AS GR_OPEN_DT,
CLOSE_DT AS CLOSE_DT,
HOTEL_OPEN_DT AS HOTEL_OPEN_DT,
ADD_DT AS ADD_DT,
DELETE_DT AS DELETE_DT,
UPDATE_DT AS UPDATE_DT,
LOAD_DT AS LOAD_DT FROM UPD_MANAGER_ID_4""")

# COMMAND ----------

# DBTITLE 1, SITE_PROFILE

spark.sql("""INSERT INTO SITE_PROFILE SELECT LOCATION_ID AS LOCATION_ID,
LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
STORE_NBR AS STORE_NBR,
VENDOR_NAME AS STORE_NAME,
STORE_TYPE_ID AS STORE_TYPE_ID,
STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
COMPANY_ID AS COMPANY_ID,
REGION_ID AS REGION_ID,
DISTRICT_ID AS DISTRICT_ID,
PRICE_ZONE_ID AS PRICE_ZONE_ID,
PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
REPL_DC_NBR AS REPL_DC_NBR,
REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
ADDRESS AS SITE_ADDRESS,
CITY AS SITE_CITY,
STATE AS STATE_CD,
COUNTRY_CD AS COUNTRY_CD,
ZIP AS POSTAL_CD,
PHONE AS SITE_MAIN_TELE_NO,
SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
SITE_EMAIL_ADDRESS AS SITE_EMAIL_ADDRESS,
SITE_SALES_FLAG AS SITE_SALES_FLAG,
EQUINE_MERCH_ID AS EQUINE_MERCH_ID,
EQUINE_SITE_ID AS EQUINE_SITE_ID,
EQUINE_SITE_OPEN_DT AS EQUINE_SITE_OPEN_DT,
GEO_LATITUDE_NBR AS GEO_LATITUDE_NBR,
GEO_LONGITUDE_NBR AS GEO_LONGITUDE_NBR,
PETSMART_DMA_CD AS PETSMART_DMA_CD,
LOYALTY_PGM_TYPE_ID AS LOYALTY_PGM_TYPE_ID,
LOYALTY_PGM_STATUS_ID AS LOYALTY_PGM_STATUS_ID,
LOYALTY_PGM_START_DT AS LOYALTY_PGM_START_DT,
LOYALTY_PGM_CHANGE_DT AS LOYALTY_PGM_CHANGE_DT,
BP_COMPANY_NBR AS BP_COMPANY_NBR,
BP_GL_ACCT AS BP_GL_ACCT,
TP_LOC_FLAG AS TP_LOC_FLAG,
TP_ACTIVE_CNT AS TP_ACTIVE_CNT,
PROMO_LABEL_CD AS PROMO_LABEL_CD,
PARENT_VENDOR_ID AS PARENT_LOCATION_ID,
VENDOR_NBR AS LOCATION_NBR,
TIME_ZONE_ID AS TIME_ZONE_ID,
DELV_SERVICE_CLASS_ID AS DELV_SERVICE_CLASS_ID,
PICK_SERVICE_CLASS_ID AS PICK_SERVICE_CLASS_ID,
SITE_LOGIN_ID AS SITE_LOGIN_ID,
SITE_MANAGER_ID AS SITE_MANAGER_ID,
SITE_OPEN_YRS_AMT AS SITE_OPEN_YRS_AMT,
HOTEL_FLAG AS HOTEL_FLAG,
DAYCAMP_FLAG AS DAYCAMP_FLAG,
VET_FLAG AS VET_FLAG,
DIST_MGR_NAME AS DIST_MGR_NAME,
DIST_SVC_MGR_NAME AS DIST_SVC_MGR_NAME,
REGION_VP_NAME AS REGION_VP_NAME,
REGION_TRAINER_NAME AS REGION_TRAINER_NAME,
ASSET_PROTECT_NAME AS ASSET_PROTECT_NAME,
SITE_COUNTY AS SITE_COUNTY,
SITE_FAX_NO AS SITE_FAX_NO,
SFT_OPEN_DT AS SFT_OPEN_DT,
DM_EMAIL_ADDRESS AS DM_EMAIL_ADDRESS,
DSM_EMAIL_ADDRESS AS DSM_EMAIL_ADDRESS,
RVP_EMAIL_ADDRESS AS RVP_EMAIL_ADDRESS,
TRADE_AREA AS TRADE_AREA,
FDLPS_NAME AS FDLPS_NAME,
FDLPS_EMAIL AS FDLPS_EMAIL,
OVERSITE_MGR_NAME AS OVERSITE_MGR_NAME,
OVERSITE_MGR_EMAIL AS OVERSITE_MGR_EMAIL,
SAFETY_DIRECTOR_NAME AS SAFETY_DIRECTOR_NAME,
SAFETY_DIRECTOR_EMAIL AS SAFETY_DIRECTOR_EMAIL,
RETAIL_MANAGER_SAFETY_NAME AS RETAIL_MANAGER_SAFETY_NAME,
RETAIL_MANAGER_SAFETY_EMAIL AS RETAIL_MANAGER_SAFETY_EMAIL,
AREA_DIRECTOR_NAME AS AREA_DIRECTOR_NAME,
AREA_DIRECTOR_EMAIL AS AREA_DIRECTOR_EMAIL,
DC_GENERAL_MANAGER_NAME AS DC_GENERAL_MANAGER_NAME,
DC_GENERAL_MANAGER_EMAIL AS DC_GENERAL_MANAGER_EMAIL,
ASST_DC_GENERAL_MANAGER_NAME1 AS ASST_DC_GENERAL_MANAGER_NAME1,
ASST_DC_GENERAL_MANAGER_EMAIL1 AS ASST_DC_GENERAL_MANAGER_EMAIL1,
ASST_DC_GENERAL_MANAGER_NAME2 AS ASST_DC_GENERAL_MANAGER_NAME2,
ASST_DC_GENERAL_MANAGER_EMAIL2 AS ASST_DC_GENERAL_MANAGER_EMAIL2,
REGIONAL_DC_SAFETY_MGR_NAME AS REGIONAL_DC_SAFETY_MGR_NAME,
REGIONAL_DC_SAFETY_MGR_EMAIL AS REGIONAL_DC_SAFETY_MGR_EMAIL,
DC_PEOPLE_SUPERVISOR_NAME AS DC_PEOPLE_SUPERVISOR_NAME,
DC_PEOPLE_SUPERVISOR_EMAIL AS DC_PEOPLE_SUPERVISOR_EMAIL,
PEOPLE_MANAGER_NAME AS PEOPLE_MANAGER_NAME,
PEOPLE_MANAGER_EMAIL AS PEOPLE_MANAGER_EMAIL,
ASSET_PROT_DIR_NAME AS ASSET_PROT_DIR_NAME,
ASSET_PROT_DIR_EMAIL AS ASSET_PROT_DIR_EMAIL,
SR_REG_ASSET_PROT_MGR_NAME AS SR_REG_ASSET_PROT_MGR_NAME,
SR_REG_ASSET_PROT_MGR_EMAIL AS SR_REG_ASSET_PROT_MGR_EMAIL,
REG_ASSET_PROT_MGR_NAME AS REG_ASSET_PROT_MGR_NAME,
REG_ASSET_PROT_MGR_EMAIL AS REG_ASSET_PROT_MGR_EMAIL,
ASSET_PROTECT_EMAIL AS ASSET_PROTECT_EMAIL,
TP_START_DT AS TP_START_DT,
OPEN_DT AS OPEN_DT,
GR_OPEN_DT AS GR_OPEN_DT,
CLOSE_DT AS CLOSE_DT,
HOTEL_OPEN_DT AS HOTEL_OPEN_DT,
ADD_DT AS ADD_DT,
DELETE_DT AS DELETE_DT,
UPDATE_DT AS UPDATE_DT,
LOAD_DT AS LOAD_DT FROM UPD_MANAGER_ID1_10""")
