# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")


# COMMAND ----------

# DBTITLE 1, SITE_PROFILE_PRE_0

df_0=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        COMPANY_DESC AS COMPANY_DESC,
        COMPANY_ID AS COMPANY_ID,
        ADD_DT AS ADD_DT,
        CLOSE_DT AS CLOSE_DT,
        DELETE_DT AS DELETE_DT,
        OPEN_DT AS OPEN_DT,
        DISTRICT_DESC AS DISTRICT_DESC,
        DISTRICT_ID AS DISTRICT_ID,
        PRICE_AD_ZONE_DESC AS PRICE_AD_ZONE_DESC,
        PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
        PRICE_ZONE_DESC AS PRICE_ZONE_DESC,
        PRICE_ZONE_ID AS PRICE_ZONE_ID,
        REGION_DESC AS REGION_DESC,
        REGION_ID AS REGION_ID,
        REPL_DC_NBR AS REPL_DC_NBR,
        REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
        REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
        COUNTRY_CD AS COUNTRY_CD,
        COUNTRY_NAME AS COUNTRY_NAME,
        STORE_NAME AS STORE_NAME,
        STORE_NBR AS STORE_NBR,
        STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
        STATE_CD AS STATE_CD,
        STORE_TYPE_DESC AS STORE_TYPE_DESC,
        STORE_TYPE_ID AS STORE_TYPE_ID,
        EQUINE_MERCH_DESC AS EQUINE_MERCH_DESC,
        GR_OPEN_DT AS GR_OPEN_DT,
        SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
        SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
        BP_COMPANY_NBR AS BP_COMPANY_NBR,
        BP_GL_ACCT AS BP_GL_ACCT,
        SITE_ADDRESS AS SITE_ADDRESS,
        POSTAL_CD AS POSTAL_CD,
        SITE_CITY AS SITE_CITY,
        SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
        SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
        LOAD_DT AS LOAD_DT,
        PROMO_LABEL_CD AS PROMO_LABEL_CD,
        SFT_OPEN_DT AS SFT_OPEN_DT,
        BANFIELD_FLAG AS BANFIELD_FLAG,
        SALES_AREA_FLR_SPC AS SALES_AREA_FLR_SPC,
        SITE_CATEGORY AS SITE_CATEGORY,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        SITE_PROFILE_PRE""")

df_0.createOrReplaceTempView("SITE_PROFILE_PRE_0")

# COMMAND ----------

# DBTITLE 1, SQ_Shortcut_to_SITE_PROFILE_PRE_1

df_1=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        COMPANY_ID AS COMPANY_ID,
        ADD_DT AS ADD_DT,
        CLOSE_DT AS CLOSE_DT,
        DELETE_DT AS DELETE_DT,
        OPEN_DT AS OPEN_DT,
        DISTRICT_ID AS DISTRICT_ID,
        PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
        PRICE_ZONE_ID AS PRICE_ZONE_ID,
        REGION_ID AS REGION_ID,
        REPL_DC_NBR AS REPL_DC_NBR,
        REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
        REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
        COUNTRY_CD AS COUNTRY_CD,
        STORE_NAME AS STORE_NAME,
        STORE_NBR AS STORE_NBR,
        STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
        STATE_CD AS STATE_CD,
        STORE_TYPE_ID AS STORE_TYPE_ID,
        GR_OPEN_DT AS GR_OPEN_DT,
        SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
        SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
        BP_COMPANY_NBR AS BP_COMPANY_NBR,
        BP_GL_ACCT AS BP_GL_ACCT,
        SITE_ADDRESS AS SITE_ADDRESS,
        POSTAL_CD AS POSTAL_CD,
        SITE_CITY AS SITE_CITY,
        SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
        SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
        LOAD_DT AS LOAD_DT,
        PROMO_LABEL_CD AS PROMO_LABEL_CD,
        SFT_OPEN_DT AS SFT_OPEN_DT,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SITE_PROFILE_PRE_0""")

df_1.createOrReplaceTempView("SQ_Shortcut_to_SITE_PROFILE_PRE_1")

# COMMAND ----------

# DBTITLE 1, SITE_PROFILE_2

df_2=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
        STORE_NBR AS STORE_NBR,
        STORE_NAME AS STORE_NAME,
        STORE_TYPE_ID AS STORE_TYPE_ID,
        STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
        COMPANY_ID AS COMPANY_ID,
        REGION_ID AS REGION_ID,
        DISTRICT_ID AS DISTRICT_ID,
        PRICE_ZONE_ID AS PRICE_ZONE_ID,
        PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
        REPL_DC_NBR AS REPL_DC_NBR,
        REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
        REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
        SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
        SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
        SITE_ADDRESS AS SITE_ADDRESS,
        SITE_CITY AS SITE_CITY,
        STATE_CD AS STATE_CD,
        COUNTRY_CD AS COUNTRY_CD,
        POSTAL_CD AS POSTAL_CD,
        SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
        SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
        SITE_EMAIL_ADDRESS AS SITE_EMAIL_ADDRESS,
        SITE_SALES_FLAG AS SITE_SALES_FLAG,
        EQUINE_MERCH_ID AS EQUINE_MERCH_ID,
        EQUINE_SITE_ID AS EQUINE_SITE_ID,
        EQUINE_SITE_OPEN_DT AS EQUINE_SITE_OPEN_DT,
        GEO_LATITUDE_NBR AS GEO_LATITUDE_NBR,
        GEO_LONGITUDE_NBR AS GEO_LONGITUDE_NBR,
        PETSMART_DMA_CD AS PETSMART_DMA_CD,
        LOYALTY_PGM_TYPE_ID AS LOYALTY_PGM_TYPE_ID,
        LOYALTY_PGM_STATUS_ID AS LOYALTY_PGM_STATUS_ID,
        LOYALTY_PGM_START_DT AS LOYALTY_PGM_START_DT,
        LOYALTY_PGM_CHANGE_DT AS LOYALTY_PGM_CHANGE_DT,
        BP_COMPANY_NBR AS BP_COMPANY_NBR,
        BP_GL_ACCT AS BP_GL_ACCT,
        TP_LOC_FLAG AS TP_LOC_FLAG,
        TP_ACTIVE_CNT AS TP_ACTIVE_CNT,
        PROMO_LABEL_CD AS PROMO_LABEL_CD,
        PARENT_LOCATION_ID AS PARENT_LOCATION_ID,
        LOCATION_NBR AS LOCATION_NBR,
        TIME_ZONE_ID AS TIME_ZONE_ID,
        DELV_SERVICE_CLASS_ID AS DELV_SERVICE_CLASS_ID,
        PICK_SERVICE_CLASS_ID AS PICK_SERVICE_CLASS_ID,
        SITE_LOGIN_ID AS SITE_LOGIN_ID,
        SITE_MANAGER_ID AS SITE_MANAGER_ID,
        SITE_OPEN_YRS_AMT AS SITE_OPEN_YRS_AMT,
        HOTEL_FLAG AS HOTEL_FLAG,
        DAYCAMP_FLAG AS DAYCAMP_FLAG,
        VET_FLAG AS VET_FLAG,
        DIST_MGR_NAME AS DIST_MGR_NAME,
        DIST_SVC_MGR_NAME AS DIST_SVC_MGR_NAME,
        REGION_VP_NAME AS REGION_VP_NAME,
        REGION_TRAINER_NAME AS REGION_TRAINER_NAME,
        ASSET_PROTECT_NAME AS ASSET_PROTECT_NAME,
        SITE_COUNTY AS SITE_COUNTY,
        SITE_FAX_NO AS SITE_FAX_NO,
        SFT_OPEN_DT AS SFT_OPEN_DT,
        DM_EMAIL_ADDRESS AS DM_EMAIL_ADDRESS,
        DSM_EMAIL_ADDRESS AS DSM_EMAIL_ADDRESS,
        RVP_EMAIL_ADDRESS AS RVP_EMAIL_ADDRESS,
        TRADE_AREA AS TRADE_AREA,
        FDLPS_NAME AS FDLPS_NAME,
        FDLPS_EMAIL AS FDLPS_EMAIL,
        OVERSITE_MGR_NAME AS OVERSITE_MGR_NAME,
        OVERSITE_MGR_EMAIL AS OVERSITE_MGR_EMAIL,
        SAFETY_DIRECTOR_NAME AS SAFETY_DIRECTOR_NAME,
        SAFETY_DIRECTOR_EMAIL AS SAFETY_DIRECTOR_EMAIL,
        RETAIL_MANAGER_SAFETY_NAME AS RETAIL_MANAGER_SAFETY_NAME,
        RETAIL_MANAGER_SAFETY_EMAIL AS RETAIL_MANAGER_SAFETY_EMAIL,
        AREA_DIRECTOR_NAME AS AREA_DIRECTOR_NAME,
        AREA_DIRECTOR_EMAIL AS AREA_DIRECTOR_EMAIL,
        DC_GENERAL_MANAGER_NAME AS DC_GENERAL_MANAGER_NAME,
        DC_GENERAL_MANAGER_EMAIL AS DC_GENERAL_MANAGER_EMAIL,
        ASST_DC_GENERAL_MANAGER_NAME1 AS ASST_DC_GENERAL_MANAGER_NAME1,
        ASST_DC_GENERAL_MANAGER_EMAIL1 AS ASST_DC_GENERAL_MANAGER_EMAIL1,
        ASST_DC_GENERAL_MANAGER_NAME2 AS ASST_DC_GENERAL_MANAGER_NAME2,
        ASST_DC_GENERAL_MANAGER_EMAIL2 AS ASST_DC_GENERAL_MANAGER_EMAIL2,
        REGIONAL_DC_SAFETY_MGR_NAME AS REGIONAL_DC_SAFETY_MGR_NAME,
        REGIONAL_DC_SAFETY_MGR_EMAIL AS REGIONAL_DC_SAFETY_MGR_EMAIL,
        DC_PEOPLE_SUPERVISOR_NAME AS DC_PEOPLE_SUPERVISOR_NAME,
        DC_PEOPLE_SUPERVISOR_EMAIL AS DC_PEOPLE_SUPERVISOR_EMAIL,
        PEOPLE_MANAGER_NAME AS PEOPLE_MANAGER_NAME,
        PEOPLE_MANAGER_EMAIL AS PEOPLE_MANAGER_EMAIL,
        ASSET_PROT_DIR_NAME AS ASSET_PROT_DIR_NAME,
        ASSET_PROT_DIR_EMAIL AS ASSET_PROT_DIR_EMAIL,
        SR_REG_ASSET_PROT_MGR_NAME AS SR_REG_ASSET_PROT_MGR_NAME,
        SR_REG_ASSET_PROT_MGR_EMAIL AS SR_REG_ASSET_PROT_MGR_EMAIL,
        REG_ASSET_PROT_MGR_NAME AS REG_ASSET_PROT_MGR_NAME,
        REG_ASSET_PROT_MGR_EMAIL AS REG_ASSET_PROT_MGR_EMAIL,
        ASSET_PROTECT_EMAIL AS ASSET_PROTECT_EMAIL,
        TP_START_DT AS TP_START_DT,
        OPEN_DT AS OPEN_DT,
        GR_OPEN_DT AS GR_OPEN_DT,
        CLOSE_DT AS CLOSE_DT,
        HOTEL_OPEN_DT AS HOTEL_OPEN_DT,
        ADD_DT AS ADD_DT,
        DELETE_DT AS DELETE_DT,
        UPDATE_DT AS UPDATE_DT,
        LOAD_DT AS LOAD_DT,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        SITE_PROFILE""")

df_2.createOrReplaceTempView("SITE_PROFILE_2")

# COMMAND ----------

# DBTITLE 1, SQ_Shortcut_to_SITE_PROFILE_3

df_3=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        SITE_SALES_FLAG AS SITE_SALES_FLAG,
        PARENT_LOCATION_ID AS PARENT_LOCATION_ID,
        LOCATION_NBR AS LOCATION_NBR,
        SITE_COUNTY AS SITE_COUNTY,
        SITE_MANAGER_ID AS SITE_MANAGER_ID,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SITE_PROFILE_2""")

df_3.createOrReplaceTempView("SQ_Shortcut_to_SITE_PROFILE_3")

# COMMAND ----------

# DBTITLE 1, JNR_Detail_Outer_Join_4

df_4=spark.sql("""
    SELECT
        MASTER.LOCATION_ID AS LOCATION_ID1,
        MASTER.STORE_NBR AS STORE_NBR,
        MASTER.STORE_NAME AS STORE_NAME,
        MASTER.STORE_TYPE_ID AS STORE_TYPE_ID,
        MASTER.STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
        MASTER.COMPANY_ID AS COMPANY_ID,
        MASTER.REGION_ID AS REGION_ID,
        MASTER.DISTRICT_ID AS DISTRICT_ID,
        MASTER.PRICE_ZONE_ID AS PRICE_ZONE_ID,
        MASTER.PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
        MASTER.REPL_DC_NBR AS REPL_DC_NBR,
        MASTER.REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
        MASTER.REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
        MASTER.SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
        MASTER.SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
        MASTER.SITE_ADDRESS AS SITE_ADDRESS,
        MASTER.SITE_CITY AS SITE_CITY,
        MASTER.STATE_CD AS STATE_CD,
        MASTER.COUNTRY_CD AS COUNTRY_CD,
        MASTER.POSTAL_CD AS POSTAL_CD,
        MASTER.SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
        MASTER.SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
        DETAIL.SITE_SALES_FLAG AS SITE_SALES_FLAG,
        DETAIL.SITE_MANAGER_ID AS SITE_MANAGER_ID,
        MASTER.BP_COMPANY_NBR AS BP_COMPANY_NBR,
        MASTER.BP_GL_ACCT AS BP_GL_ACCT,
        MASTER.PROMO_LABEL_CD AS PROMO_LABEL_CD,
        DETAIL.PARENT_LOCATION_ID AS PARENT_LOCATION_ID,
        DETAIL.LOCATION_NBR AS LOCATION_NBR,
        MASTER.SFT_OPEN_DT AS SFT_OPEN_DT,
        DETAIL.SITE_COUNTY AS SITE_COUNTY,
        MASTER.OPEN_DT AS OPEN_DT,
        MASTER.GR_OPEN_DT AS GR_OPEN_DT,
        MASTER.CLOSE_DT AS CLOSE_DT,
        MASTER.ADD_DT AS ADD_DT,
        MASTER.DELETE_DT AS DELETE_DT,
        MASTER.LOAD_DT AS LOAD_DT,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_to_SITE_PROFILE_PRE_1 MASTER 
    RIGHT JOIN
        SQ_Shortcut_to_SITE_PROFILE_3 DETAIL 
            ON MASTER.LOCATION_ID = LOCATION_ID""")

df_4.createOrReplaceTempView("JNR_Detail_Outer_Join_4")

# COMMAND ----------

# DBTITLE 1, LKP_USR_DC_NAMES_5

df_5=spark.sql("""
    SELECT
        DC_RLPM_NAME AS DC_RLPM_NAME,
        DC_RLPM_EMAIL AS DC_RLPM_EMAIL,
        DC_ASST_GM1_NAME AS DC_ASST_GM1_NAME,
        DC_ASST_GM1_EMAIL AS DC_ASST_GM1_EMAIL,
        DC_ASST_GM2_NAME AS DC_ASST_GM2_NAME,
        DC_ASST_GM2_EMAIL AS DC_ASST_GM2_EMAIL,
        DC_GM_NAME AS DC_GM_NAME,
        DC_GM_EMAIL AS DC_GM_EMAIL,
        DC_HR_SUPER1_NAME AS DC_HR_SUPER1_NAME,
        DC_HR_SUPER1_EMAIL AS DC_HR_SUPER1_EMAIL,
        DC_HR_SUPER2_NAME AS DC_HR_SUPER2_NAME,
        DC_HR_SUPER2_EMAIL AS DC_HR_SUPER2_EMAIL,
        DC_HR_MGR_NAME AS DC_HR_MGR_NAME,
        DC_HR_MGR_EMAIL AS DC_HR_MGR_EMAIL,
        JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        USR_DC_NAMES 
    RIGHT OUTER JOIN
        JNR_Detail_Outer_Join_4 
            ON USR_DC_NAMES.STORE_NBR = JNR_Detail_Outer_Join_4.STORE_NBR""")

df_5.createOrReplaceTempView("LKP_USR_DC_NAMES_5")

# COMMAND ----------

# DBTITLE 1, EXP_Conv_STORE_NBR_6

df_6=spark.sql("""
    SELECT
        TO_CHAR(STORE_NBR) AS o_STORE_NBR,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNR_Detail_Outer_Join_4""")

df_6.createOrReplaceTempView("EXP_Conv_STORE_NBR_6")

# COMMAND ----------

# DBTITLE 1, LKP_SAP_T001W_SITE_PRE_7

df_7=spark.sql("""
    SELECT
        BEZEI AS BEZEI,
        EXP_Conv_STORE_NBR_6.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SAP_T001W_SITE_PRE 
    RIGHT OUTER JOIN
        EXP_Conv_STORE_NBR_6 
            ON SAP_T001W_SITE_PRE.WERKS = EXP_Conv_STORE_NBR_6.o_STORE_NBR""")

df_7.createOrReplaceTempView("LKP_SAP_T001W_SITE_PRE_7")

# COMMAND ----------

# DBTITLE 1, EXP_Conv_REGION_8

df_8=spark.sql("""
    SELECT
        REGION_ID AS REGION_ID,
        (CAST(REGION_ID AS DECIMAL (38,
        0))) AS o_REGION_ID,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNR_Detail_Outer_Join_4""")

df_8.createOrReplaceTempView("EXP_Conv_REGION_8")

# COMMAND ----------

# DBTITLE 1, LKP_USR_REGION_NAMES_9

df_9=spark.sql("""
    SELECT
        RVP_NAME AS RVP_NAME,
        RVP_EMAIL AS RVP_EMAIL,
        RD_NAME AS RD_NAME,
        RD_EMAIL AS RD_EMAIL,
        R_PEOPLE_DIR_NAME AS R_PEOPLE_DIR_NAME,
        R_PEOPLE_DIR_EMAIL AS R_PEOPLE_DIR_EMAIL,
        SR_LP_SAFETY_MGR_NAME AS SR_LP_SAFETY_MGR_NAME,
        SR_LP_SAFETY_MGR_EMAIL AS SR_LP_SAFETY_MGR_EMAIL,
        RETAIL_SAFETY_MGR_NAME AS RETAIL_SAFETY_MGR_NAME,
        RETAIL_SAFETY_MGR_EMAIL AS RETAIL_SAFETY_MGR_EMAIL,
        LP_SAFETY_DIR_NAME AS LP_SAFETY_DIR_NAME,
        LP_SAFETY_DIR_EMAIL AS LP_SAFETY_DIR_EMAIL,
        LEARN_SOLUTION_MGR_NAME AS LEARN_SOLUTION_MGR_NAME,
        LEARN_SOLUTION_MGR_EMAIL AS LEARN_SOLUTION_MGR_EMAIL,
        EXP_Conv_REGION_8.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        USR_REGION_NAMES 
    RIGHT OUTER JOIN
        EXP_Conv_REGION_8 
            ON USR_REGION_NAMES.REGION_ID = EXP_Conv_REGION_8.o_REGION_ID""")

df_9.createOrReplaceTempView("LKP_USR_REGION_NAMES_9")

# COMMAND ----------

# DBTITLE 1, EXP_Conv_DISTRICT_10

df_10=spark.sql("""
    SELECT
        (CAST(DISTRICT_ID AS DECIMAL (38,
        0))) AS o_DISTRICT_ID,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNR_Detail_Outer_Join_4""")

df_10.createOrReplaceTempView("EXP_Conv_DISTRICT_10")

# COMMAND ----------

# DBTITLE 1, LKP_USR_DISTRICT_NAMES_11

df_11=spark.sql("""
    SELECT
        DM_NAME AS DM_NAME,
        DM_NAME_EMAIL AS DM_NAME_EMAIL,
        LP_SAFETY_NAME AS LP_SAFETY_NAME,
        LP_SAFETY_EMAIL AS LP_SAFETY_EMAIL,
        HR_SUPER_NAME AS HR_SUPER_NAME,
        HR_SUPER_EMAIL AS HR_SUPER_EMAIL,
        EXP_Conv_DISTRICT_10.o_DISTRICT_ID AS o_DISTRICT_ID,
        EXP_Conv_DISTRICT_10.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        USR_DISTRICT_NAMES 
    RIGHT OUTER JOIN
        EXP_Conv_DISTRICT_10 
            ON USR_DISTRICT_NAMES.DISTRICT_ID = EXP_Conv_DISTRICT_10.o_DISTRICT_ID""")

df_11.createOrReplaceTempView("LKP_USR_DISTRICT_NAMES_11")

# COMMAND ----------

# DBTITLE 1, EXP_Default_12

df_12=spark.sql("""
    SELECT
        JNR_Detail_Outer_Join_4.LOCATION_ID1 AS LOCATION_ID1,
        LOCATION_TYPE_ID AS o_LOCATION_TYPE_ID,
        JNR_Detail_Outer_Join_4.STORE_NBR AS STORE_NBR1,
        JNR_Detail_Outer_Join_4.STORE_NAME AS STORE_NAME,
        JNR_Detail_Outer_Join_4.STORE_TYPE_ID AS STORE_TYPE_ID,
        JNR_Detail_Outer_Join_4.STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
        JNR_Detail_Outer_Join_4.COMPANY_ID AS COMPANY_ID,
        JNR_Detail_Outer_Join_4.REGION_ID AS REGION_ID,
        JNR_Detail_Outer_Join_4.DISTRICT_ID AS DISTRICT_ID,
        JNR_Detail_Outer_Join_4.PRICE_ZONE_ID AS PRICE_ZONE_ID,
        JNR_Detail_Outer_Join_4.PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
        JNR_Detail_Outer_Join_4.REPL_DC_NBR AS REPL_DC_NBR,
        JNR_Detail_Outer_Join_4.REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
        JNR_Detail_Outer_Join_4.REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
        JNR_Detail_Outer_Join_4.SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
        JNR_Detail_Outer_Join_4.SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
        JNR_Detail_Outer_Join_4.SITE_ADDRESS AS SITE_ADDRESS,
        JNR_Detail_Outer_Join_4.SITE_CITY AS SITE_CITY,
        JNR_Detail_Outer_Join_4.STATE_CD AS STATE_CD,
        JNR_Detail_Outer_Join_4.COUNTRY_CD AS COUNTRY_CD,
        JNR_Detail_Outer_Join_4.POSTAL_CD AS POSTAL_CD,
        JNR_Detail_Outer_Join_4.SITE_MAIN_TELE_NO AS SITE_MAIN_TELE_NO,
        JNR_Detail_Outer_Join_4.SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
        IFF(LOCATION_TYPE_ID = 8,
        v_SITE_LOGIN_ID || '@PETsMART.com',
        'Not Defined') AS o_SITE_EMAIL_ADDRESS,
        IFF(ISNULL(JNR_Detail_Outer_Join_4.SITE_SALES_FLAG),
        '0',
        JNR_Detail_Outer_Join_4.SITE_SALES_FLAG) AS o_SITE_SALES_FLAG,
        0 AS EQUINE_SITE_ID,
        JNR_Detail_Outer_Join_4.BP_COMPANY_NBR AS BP_COMPANY_NBR,
        JNR_Detail_Outer_Join_4.BP_GL_ACCT AS BP_GL_ACCT,
        JNR_Detail_Outer_Join_4.PROMO_LABEL_CD AS PROMO_LABEL_CD,
        IFF(ISNULL(JNR_Detail_Outer_Join_4.PARENT_LOCATION_ID),
        90000,
        JNR_Detail_Outer_Join_4.PARENT_LOCATION_ID) AS o_PARENT_LOCATION_ID,
        IFF(ISNULL(JNR_Detail_Outer_Join_4.LOCATION_NBR),
        (LPAD(v_STORE_NBR,
        4,
        '0')),
        JNR_Detail_Outer_Join_4.LOCATION_NBR) AS o_LOCATION_NBR,
        DECODE(TRUE,
        LOCATION_TYPE_ID = 8 
        AND STORE_NBR >= 1 
        AND STORE_NBR <= 9,
        'M000' || STORE_NBR,
        LOCATION_TYPE_ID = 8 
        AND STORE_NBR >= 10 
        AND STORE_NBR <= 99,
        'M00' || STORE_NBR,
        LOCATION_TYPE_ID = 8 
        AND STORE_NBR >= 100 
        AND STORE_NBR <= 999,
        'M0' || STORE_NBR,
        LOCATION_TYPE_ID = 8 
        AND STORE_NBR >= 1000 
        AND STORE_NBR <= 9999,
        'M' || STORE_NBR,
        NULL) AS o_SITE_LOGIN_ID,
        DECODE(ISNULL(JNR_Detail_Outer_Join_4.SITE_MANAGER_ID),
        0,
        JNR_Detail_Outer_Join_4.SITE_MANAGER_ID) AS o_SITE_MANAGER_ID,
        DECODE(TRUE,
        JNR_Detail_Outer_Join_4.OPEN_DT = TO_DATE('99991231',
        'YYYYMMDD'),
        0,
        ROUND(DATE_DIFF(current_timestamp,
        JNR_Detail_Outer_Join_4.OPEN_DT,
        'MM') / 12,
        1)) AS o_SITE_OPEN_YRS_AMT,
        LKP_USR_DISTRICT_NAMES_11.DM_NAME AS DM_NAME,
        LKP_USR_REGION_NAMES_9.RVP_NAME AS RVP_NAME,
        JNR_Detail_Outer_Join_4.SFT_OPEN_DT AS SFT_OPEN_DT,
        LKP_USR_DISTRICT_NAMES_11.LP_SAFETY_NAME AS LP_SAFETY_NAME,
        DECODE(TRUE,
        NOT ISNULL(LKP_SAP_T001W_SITE_PRE_7.BEZEI),
        LKP_SAP_T001W_SITE_PRE_7.BEZEI,
        ISNULL(LKP_SAP_T001W_SITE_PRE_7.BEZEI) 
        AND JNR_Detail_Outer_Join_4.SITE_COUNTY <> 'Not Defined',
        JNR_Detail_Outer_Join_4.SITE_COUNTY,
        'Not Defined') AS o_SITE_COUNTY,
        '0' AS SITE_FAX_NO,
        LKP_USR_DISTRICT_NAMES_11.DM_NAME_EMAIL AS DM_NAME_EMAIL,
        LKP_USR_REGION_NAMES_9.RVP_EMAIL AS RVP_EMAIL,
        LKP_USR_REGION_NAMES_9.RETAIL_SAFETY_MGR_NAME AS RETAIL_SAFETY_MGR_NAME,
        LKP_USR_REGION_NAMES_9.RETAIL_SAFETY_MGR_EMAIL AS RETAIL_SAFETY_MGR_EMAIL,
        DECODE(TRUE,
        LOCATION_TYPE_ID = 1,
        LKP_USR_DISTRICT_NAMES_11.DM_NAME,
        LOCATION_TYPE_ID = 2,
        LKP_USR_DISTRICT_NAMES_11.DM_NAME,
        LOCATION_TYPE_ID = 3,
        LKP_USR_DISTRICT_NAMES_11.DM_NAME,
        LOCATION_TYPE_ID = 4,
        LKP_USR_DISTRICT_NAMES_11.DM_NAME,
        '') AS AREA_DIRECTOR_NAME,
        DECODE(TRUE,
        LOCATION_TYPE_ID = 1,
        LKP_USR_DISTRICT_NAMES_11.DM_NAME_EMAIL,
        LOCATION_TYPE_ID = 2,
        LKP_USR_DISTRICT_NAMES_11.DM_NAME_EMAIL,
        LOCATION_TYPE_ID = 3,
        LKP_USR_DISTRICT_NAMES_11.DM_NAME_EMAIL,
        LOCATION_TYPE_ID = 4,
        LKP_USR_DISTRICT_NAMES_11.DM_NAME_EMAIL,
        '') AS AREA_DIRECTOR_EMAIL,
        LKP_USR_DC_NAMES_5.DC_GM_NAME AS DC_GM_NAME,
        LKP_USR_DC_NAMES_5.DC_GM_EMAIL AS DC_GM_EMAIL,
        LKP_USR_DC_NAMES_5.DC_ASST_GM1_NAME AS DC_ASST_GM1_NAME,
        LKP_USR_DC_NAMES_5.DC_ASST_GM1_EMAIL AS DC_ASST_GM1_EMAIL,
        LKP_USR_DC_NAMES_5.DC_ASST_GM2_NAME AS DC_ASST_GM2_NAME,
        LKP_USR_DC_NAMES_5.DC_ASST_GM2_EMAIL AS DC_ASST_GM2_EMAIL,
        LKP_USR_DC_NAMES_5.DC_RLPM_NAME AS DC_RLPM_NAME,
        LKP_USR_DC_NAMES_5.DC_RLPM_EMAIL AS DC_RLPM_EMAIL,
        LKP_USR_DC_NAMES_5.DC_HR_SUPER1_NAME AS DC_HR_SUPER1_NAME,
        LKP_USR_DC_NAMES_5.DC_HR_SUPER1_EMAIL AS DC_HR_SUPER1_EMAIL,
        LKP_USR_DC_NAMES_5.DC_HR_SUPER2_NAME AS DC_HR_SUPER2_NAME,
        LKP_USR_DC_NAMES_5.DC_HR_SUPER2_EMAIL AS DC_HR_SUPER2_EMAIL,
        LKP_USR_DC_NAMES_5.DC_HR_MGR_NAME AS DC_HR_MANAGER_NAME,
        LKP_USR_DC_NAMES_5.DC_HR_MGR_EMAIL AS DC_HR_MANAGER_EMAIL,
        DECODE(TRUE,
        LOCATION_TYPE_ID = 1,
        DC_HR_MGR_NAME,
        LOCATION_TYPE_ID = 2,
        DC_HR_MGR_NAME,
        LOCATION_TYPE_ID = 3,
        DC_HR_MGR_NAME,
        LOCATION_TYPE_ID = 4,
        DC_HR_MGR_NAME,
        LKP_USR_REGION_NAMES_9.R_PEOPLE_DIR_NAME) AS o_PEOPLE_MANAGER_NAME,
        DECODE(TRUE,
        LOCATION_TYPE_ID = 1,
        DC_HR_MGR_EMAIL,
        LOCATION_TYPE_ID = 2,
        DC_HR_MGR_EMAIL,
        LOCATION_TYPE_ID = 3,
        DC_HR_MGR_EMAIL,
        LOCATION_TYPE_ID = 4,
        DC_HR_MGR_EMAIL,
        LKP_USR_REGION_NAMES_9.R_PEOPLE_DIR_EMAIL) AS o_PEOPLE_MANAGER_EMAIL,
        LKP_USR_REGION_NAMES_9.RD_NAME AS RD_NAME,
        LKP_USR_REGION_NAMES_9.RD_EMAIL AS RD_EMAIL,
        LKP_USR_REGION_NAMES_9.R_PEOPLE_DIR_NAME AS R_PEOPLE_DIR_NAME,
        LKP_USR_REGION_NAMES_9.R_PEOPLE_DIR_EMAIL AS R_PEOPLE_DIR_EMAIL,
        LKP_USR_REGION_NAMES_9.LP_SAFETY_DIR_NAME AS LP_SAFETY_DIR_NAME,
        LKP_USR_REGION_NAMES_9.LP_SAFETY_DIR_EMAIL AS LP_SAFETY_DIR_EMAIL,
        LKP_USR_REGION_NAMES_9.SR_LP_SAFETY_MGR_NAME AS SR_LP_SAFETY_MGR_NAME,
        LKP_USR_REGION_NAMES_9.SR_LP_SAFETY_MGR_EMAIL AS SR_LP_SAFETY_MGR_EMAIL,
        DECODE(TRUE,
        LOCATION_TYPE_ID = 1,
        LKP_USR_DC_NAMES_5.DC_RLPM_NAME,
        LOCATION_TYPE_ID = 2,
        LKP_USR_DC_NAMES_5.DC_RLPM_NAME,
        LOCATION_TYPE_ID = 3,
        LKP_USR_DC_NAMES_5.DC_RLPM_NAME,
        LOCATION_TYPE_ID = 4,
        LKP_USR_DC_NAMES_5.DC_RLPM_NAME,
        LKP_USR_REGION_NAMES_9.LP_SAFETY_DIR_NAME) AS o_REG_ASSET_PROT_MGR_NAME,
        DECODE(TRUE,
        LOCATION_TYPE_ID = 1,
        LKP_USR_DC_NAMES_5.DC_RLPM_EMAIL,
        LOCATION_TYPE_ID = 2,
        LKP_USR_DC_NAMES_5.DC_RLPM_EMAIL,
        LOCATION_TYPE_ID = 1,
        LKP_USR_DC_NAMES_5.DC_RLPM_EMAIL,
        LOCATION_TYPE_ID = 1,
        LKP_USR_DC_NAMES_5.DC_RLPM_EMAIL,
        LKP_USR_REGION_NAMES_9.LP_SAFETY_DIR_EMAIL) AS o_REG_ASSET_PROT_MGR_EMAIL,
        LKP_USR_DISTRICT_NAMES_11.LP_SAFETY_EMAIL AS LP_SAFETY_EMAIL,
        LKP_USR_DISTRICT_NAMES_11.HR_SUPER_NAME AS HR_SUPER_NAME,
        LKP_USR_DISTRICT_NAMES_11.HR_SUPER_EMAIL AS HR_SUPER_EMAIL,
        LKP_USR_REGION_NAMES_9.LEARN_SOLUTION_MGR_NAME AS LEARN_SOLUTION_MGR_NAME,
        LKP_USR_REGION_NAMES_9.LEARN_SOLUTION_MGR_EMAIL AS LEARN_SOLUTION_MGR_EMAIL,
        JNR_Detail_Outer_Join_4.OPEN_DT AS OPEN_DT,
        JNR_Detail_Outer_Join_4.GR_OPEN_DT AS GR_OPEN_DT,
        JNR_Detail_Outer_Join_4.CLOSE_DT AS CLOSE_DT,
        JNR_Detail_Outer_Join_4.ADD_DT AS ADD_DT,
        JNR_Detail_Outer_Join_4.DELETE_DT AS DELETE_DT,
        JNR_Detail_Outer_Join_4.LOAD_DT AS LOAD_DT,
        LKP_USR_DISTRICT_NAMES_11.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        LKP_USR_DISTRICT_NAMES_11 
    INNER JOIN
        LKP_USR_REGION_NAMES_9 
            ON LKP_USR_DISTRICT_NAMES_11.Monotonically_Increasing_Id = LKP_USR_REGION_NAMES_9.Monotonically_Increasing_Id 
    INNER JOIN
        JNR_Detail_Outer_Join_4 
            ON LKP_USR_DISTRICT_NAMES_11.Monotonically_Increasing_Id = JNR_Detail_Outer_Join_4.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_SAP_T001W_SITE_PRE_7 
            ON LKP_USR_DISTRICT_NAMES_11.Monotonically_Increasing_Id = LKP_SAP_T001W_SITE_PRE_7.Monotonically_Increasing_Id 
    INNER JOIN
        LKP_USR_DC_NAMES_5 
            ON LKP_USR_DISTRICT_NAMES_11.Monotonically_Increasing_Id = LKP_USR_DC_NAMES_5.Monotonically_Increasing_Id""")

df_12.createOrReplaceTempView("EXP_Default_12")

# COMMAND ----------

# DBTITLE 1, SITE_PROFILE

spark.sql("""INSERT INTO SITE_PROFILE SELECT LOCATION_ID AS LOCATION_ID,
LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
STORE_NBR AS STORE_NBR,
VENDOR_NAME AS STORE_NAME,
STORE_TYPE_ID AS STORE_TYPE_ID,
STORE_OPEN_CLOSE_FLAG AS STORE_OPEN_CLOSE_FLAG,
COMPANY_ID AS COMPANY_ID,
REGION_ID AS REGION_ID,
DISTRICT_ID AS DISTRICT_ID,
PRICE_ZONE_ID AS PRICE_ZONE_ID,
PRICE_AD_ZONE_ID AS PRICE_AD_ZONE_ID,
REPL_DC_NBR AS REPL_DC_NBR,
REPL_FISH_DC_NBR AS REPL_FISH_DC_NBR,
REPL_FWD_DC_NBR AS REPL_FWD_DC_NBR,
SQ_FEET_RETAIL AS SQ_FEET_RETAIL,
SQ_FEET_TOTAL AS SQ_FEET_TOTAL,
ADDRESS AS SITE_ADDRESS,
CITY AS SITE_CITY,
STATE AS STATE_CD,
COUNTRY_CD AS COUNTRY_CD,
ZIP AS POSTAL_CD,
PHONE AS SITE_MAIN_TELE_NO,
SITE_GROOM_TELE_NO AS SITE_GROOM_TELE_NO,
SITE_EMAIL_ADDRESS AS SITE_EMAIL_ADDRESS,
SITE_SALES_FLAG AS SITE_SALES_FLAG,
EQUINE_MERCH_ID AS EQUINE_MERCH_ID,
EQUINE_SITE_ID AS EQUINE_SITE_ID,
EQUINE_SITE_OPEN_DT AS EQUINE_SITE_OPEN_DT,
GEO_LATITUDE_NBR AS GEO_LATITUDE_NBR,
GEO_LONGITUDE_NBR AS GEO_LONGITUDE_NBR,
PETSMART_DMA_CD AS PETSMART_DMA_CD,
LOYALTY_PGM_TYPE_ID AS LOYALTY_PGM_TYPE_ID,
LOYALTY_PGM_STATUS_ID AS LOYALTY_PGM_STATUS_ID,
LOYALTY_PGM_START_DT AS LOYALTY_PGM_START_DT,
LOYALTY_PGM_CHANGE_DT AS LOYALTY_PGM_CHANGE_DT,
BP_COMPANY_NBR AS BP_COMPANY_NBR,
BP_GL_ACCT AS BP_GL_ACCT,
TP_LOC_FLAG AS TP_LOC_FLAG,
TP_ACTIVE_CNT AS TP_ACTIVE_CNT,
PROMO_LABEL_CD AS PROMO_LABEL_CD,
PARENT_VENDOR_ID AS PARENT_LOCATION_ID,
VENDOR_NBR AS LOCATION_NBR,
TIME_ZONE_ID AS TIME_ZONE_ID,
DELV_SERVICE_CLASS_ID AS DELV_SERVICE_CLASS_ID,
PICK_SERVICE_CLASS_ID AS PICK_SERVICE_CLASS_ID,
SITE_LOGIN_ID AS SITE_LOGIN_ID,
SITE_MANAGER_ID AS SITE_MANAGER_ID,
SITE_OPEN_YRS_AMT AS SITE_OPEN_YRS_AMT,
HOTEL_FLAG AS HOTEL_FLAG,
DAYCAMP_FLAG AS DAYCAMP_FLAG,
VET_FLAG AS VET_FLAG,
DIST_MGR_NAME AS DIST_MGR_NAME,
DIST_SVC_MGR_NAME AS DIST_SVC_MGR_NAME,
REGION_VP_NAME AS REGION_VP_NAME,
REGION_TRAINER_NAME AS REGION_TRAINER_NAME,
ASSET_PROTECT_NAME AS ASSET_PROTECT_NAME,
SITE_COUNTY AS SITE_COUNTY,
SITE_FAX_NO AS SITE_FAX_NO,
SFT_OPEN_DT AS SFT_OPEN_DT,
DM_EMAIL_ADDRESS AS DM_EMAIL_ADDRESS,
DSM_EMAIL_ADDRESS AS DSM_EMAIL_ADDRESS,
RVP_EMAIL_ADDRESS AS RVP_EMAIL_ADDRESS,
TRADE_AREA AS TRADE_AREA,
FDLPS_NAME AS FDLPS_NAME,
FDLPS_EMAIL AS FDLPS_EMAIL,
OVERSITE_MGR_NAME AS OVERSITE_MGR_NAME,
OVERSITE_MGR_EMAIL AS OVERSITE_MGR_EMAIL,
SAFETY_DIRECTOR_NAME AS SAFETY_DIRECTOR_NAME,
SAFETY_DIRECTOR_EMAIL AS SAFETY_DIRECTOR_EMAIL,
RETAIL_MANAGER_SAFETY_NAME AS RETAIL_MANAGER_SAFETY_NAME,
RETAIL_MANAGER_SAFETY_EMAIL AS RETAIL_MANAGER_SAFETY_EMAIL,
AREA_DIRECTOR_NAME AS AREA_DIRECTOR_NAME,
AREA_DIRECTOR_EMAIL AS AREA_DIRECTOR_EMAIL,
DC_GENERAL_MANAGER_NAME AS DC_GENERAL_MANAGER_NAME,
DC_GENERAL_MANAGER_EMAIL AS DC_GENERAL_MANAGER_EMAIL,
ASST_DC_GENERAL_MANAGER_NAME1 AS ASST_DC_GENERAL_MANAGER_NAME1,
ASST_DC_GENERAL_MANAGER_EMAIL1 AS ASST_DC_GENERAL_MANAGER_EMAIL1,
ASST_DC_GENERAL_MANAGER_NAME2 AS ASST_DC_GENERAL_MANAGER_NAME2,
ASST_DC_GENERAL_MANAGER_EMAIL2 AS ASST_DC_GENERAL_MANAGER_EMAIL2,
REGIONAL_DC_SAFETY_MGR_NAME AS REGIONAL_DC_SAFETY_MGR_NAME,
REGIONAL_DC_SAFETY_MGR_EMAIL AS REGIONAL_DC_SAFETY_MGR_EMAIL,
DC_PEOPLE_SUPERVISOR_NAME AS DC_PEOPLE_SUPERVISOR_NAME,
DC_PEOPLE_SUPERVISOR_EMAIL AS DC_PEOPLE_SUPERVISOR_EMAIL,
PEOPLE_MANAGER_NAME AS PEOPLE_MANAGER_NAME,
PEOPLE_MANAGER_EMAIL AS PEOPLE_MANAGER_EMAIL,
ASSET_PROT_DIR_NAME AS ASSET_PROT_DIR_NAME,
ASSET_PROT_DIR_EMAIL AS ASSET_PROT_DIR_EMAIL,
SR_REG_ASSET_PROT_MGR_NAME AS SR_REG_ASSET_PROT_MGR_NAME,
SR_REG_ASSET_PROT_MGR_EMAIL AS SR_REG_ASSET_PROT_MGR_EMAIL,
REG_ASSET_PROT_MGR_NAME AS REG_ASSET_PROT_MGR_NAME,
REG_ASSET_PROT_MGR_EMAIL AS REG_ASSET_PROT_MGR_EMAIL,
ASSET_PROTECT_EMAIL AS ASSET_PROTECT_EMAIL,
TP_START_DT AS TP_START_DT,
OPEN_DT AS OPEN_DT,
GR_OPEN_DT AS GR_OPEN_DT,
CLOSE_DT AS CLOSE_DT,
HOTEL_OPEN_DT AS HOTEL_OPEN_DT,
ADD_DT AS ADD_DT,
DELETE_DT AS DELETE_DT,
UPDATE_DT AS UPDATE_DT,
LOAD_DT AS LOAD_DT FROM EXP_Default_12""")
