# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")


# COMMAND ----------
# DBTITLE 1, SKU_ATTR_0


df_0=spark.sql("""
    SELECT
        PRODUCT_ID AS PRODUCT_ID,
        SKU_ATTR1_ID AS SKU_ATTR1_ID,
        SKU_ATTR1_DESC AS SKU_ATTR1_DESC,
        SKU_ATTR2_ID AS SKU_ATTR2_ID,
        SKU_ATTR2_DESC AS SKU_ATTR2_DESC,
        SKU_ATTR3_ID AS SKU_ATTR3_ID,
        SKU_ATTR3_DESC AS SKU_ATTR3_DESC,
        SKU_ATTR4_ID AS SKU_ATTR4_ID,
        SKU_ATTR4_DESC AS SKU_ATTR4_DESC,
        SKU_ATTR5_ID AS SKU_ATTR5_ID,
        SKU_ATTR5_DESC AS SKU_ATTR5_DESC,
        SKU_ATTR6_ID AS SKU_ATTR6_ID,
        SKU_ATTR6_DESC AS SKU_ATTR6_DESC,
        SKU_ATTR7_ID AS SKU_ATTR7_ID,
        SKU_ATTR7_DESC AS SKU_ATTR7_DESC,
        SKU_ATTR8_ID AS SKU_ATTR8_ID,
        SKU_ATTR8_DESC AS SKU_ATTR8_DESC,
        SKU_ATTR9_ID AS SKU_ATTR9_ID,
        SKU_ATTR9_DESC AS SKU_ATTR9_DESC,
        SKU_ATTR10_ID AS SKU_ATTR10_ID,
        SKU_ATTR10_DESC AS SKU_ATTR10_DESC,
        SKU_ATTR11_ID AS SKU_ATTR11_ID,
        SKU_ATTR11_DESC AS SKU_ATTR11_DESC,
        SKU_ATTR12_ID AS SKU_ATTR12_ID,
        SKU_ATTR12_DESC AS SKU_ATTR12_DESC,
        SKU_ATTR13_ID AS SKU_ATTR13_ID,
        SKU_ATTR13_DESC AS SKU_ATTR13_DESC,
        SKU_ATTR14_ID AS SKU_ATTR14_ID,
        SKU_ATTR14_DESC AS SKU_ATTR14_DESC,
        SKU_ATTR15_ID AS SKU_ATTR15_ID,
        SKU_ATTR15_DESC AS SKU_ATTR15_DESC,
        SKU_ATTR16_ID AS SKU_ATTR16_ID,
        SKU_ATTR16_DESC AS SKU_ATTR16_DESC,
        SKU_ATTR17_ID AS SKU_ATTR17_ID,
        SKU_ATTR17_DESC AS SKU_ATTR17_DESC,
        SKU_ATTR18_ID AS SKU_ATTR18_ID,
        SKU_ATTR18_DESC AS SKU_ATTR18_DESC,
        SKU_ATTR19_ID AS SKU_ATTR19_ID,
        SKU_ATTR19_DESC AS SKU_ATTR19_DESC,
        SKU_ATTR20_ID AS SKU_ATTR20_ID,
        SKU_ATTR20_DESC AS SKU_ATTR20_DESC,
        SKU_ATTR21_ID AS SKU_ATTR21_ID,
        SKU_ATTR21_DESC AS SKU_ATTR21_DESC,
        SKU_ATTR22_ID AS SKU_ATTR22_ID,
        SKU_ATTR22_DESC AS SKU_ATTR22_DESC,
        SKU_ATTR23_ID AS SKU_ATTR23_ID,
        SKU_ATTR23_DESC AS SKU_ATTR23_DESC,
        SKU_ATTR24_ID AS SKU_ATTR24_ID,
        SKU_ATTR24_DESC AS SKU_ATTR24_DESC,
        SKU_ATTR25_ID AS SKU_ATTR25_ID,
        SKU_ATTR25_DESC AS SKU_ATTR25_DESC,
        SKU_ATTR26_ID AS SKU_ATTR26_ID,
        SKU_ATTR26_DESC AS SKU_ATTR26_DESC,
        SKU_ATTR27_ID AS SKU_ATTR27_ID,
        SKU_ATTR27_DESC AS SKU_ATTR27_DESC,
        SKU_ATTR28_ID AS SKU_ATTR28_ID,
        SKU_ATTR28_DESC AS SKU_ATTR28_DESC,
        SKU_ATTR29_ID AS SKU_ATTR29_ID,
        SKU_ATTR29_DESC AS SKU_ATTR29_DESC,
        SKU_ATTR30_ID AS SKU_ATTR30_ID,
        SKU_ATTR30_DESC AS SKU_ATTR30_DESC,
        SKU_ATTR31_ID AS SKU_ATTR31_ID,
        SKU_ATTR31_DESC AS SKU_ATTR31_DESC,
        SKU_ATTR32_ID AS SKU_ATTR32_ID,
        SKU_ATTR32_DESC AS SKU_ATTR32_DESC,
        SKU_ATTR33_ID AS SKU_ATTR33_ID,
        SKU_ATTR33_DESC AS SKU_ATTR33_DESC,
        SKU_ATTR34_ID AS SKU_ATTR34_ID,
        SKU_ATTR34_DESC AS SKU_ATTR34_DESC,
        SKU_ATTR35_ID AS SKU_ATTR35_ID,
        SKU_ATTR35_DESC AS SKU_ATTR35_DESC,
        SKU_ATTR36_ID AS SKU_ATTR36_ID,
        SKU_ATTR36_DESC AS SKU_ATTR36_DESC,
        SKU_ATTR37_ID AS SKU_ATTR37_ID,
        SKU_ATTR37_DESC AS SKU_ATTR37_DESC,
        SKU_ATTR38_ID AS SKU_ATTR38_ID,
        SKU_ATTR38_DESC AS SKU_ATTR38_DESC,
        SKU_ATTR39_ID AS SKU_ATTR39_ID,
        SKU_ATTR39_DESC AS SKU_ATTR39_DESC,
        SKU_ATTR40_ID AS SKU_ATTR40_ID,
        SKU_ATTR40_DESC AS SKU_ATTR40_DESC,
        SKU_ATTR41_ID AS SKU_ATTR41_ID,
        SKU_ATTR41_DESC AS SKU_ATTR41_DESC,
        SKU_ATTR42_ID AS SKU_ATTR42_ID,
        SKU_ATTR42_DESC AS SKU_ATTR42_DESC,
        SKU_ATTR43_ID AS SKU_ATTR43_ID,
        SKU_ATTR43_DESC AS SKU_ATTR43_DESC,
        SKU_ATTR44_ID AS SKU_ATTR44_ID,
        SKU_ATTR44_DESC AS SKU_ATTR44_DESC,
        SKU_ATTR45_ID AS SKU_ATTR45_ID,
        SKU_ATTR45_DESC AS SKU_ATTR45_DESC,
        SKU_ATTR46_ID AS SKU_ATTR46_ID,
        SKU_ATTR46_DESC AS SKU_ATTR46_DESC,
        SKU_ATTR47_ID AS SKU_ATTR47_ID,
        SKU_ATTR47_DESC AS SKU_ATTR47_DESC,
        SKU_ATTR48_ID AS SKU_ATTR48_ID,
        SKU_ATTR48_DESC AS SKU_ATTR48_DESC,
        SKU_ATTR49_ID AS SKU_ATTR49_ID,
        SKU_ATTR49_DESC AS SKU_ATTR49_DESC,
        SKU_ATTR50_ID AS SKU_ATTR50_ID,
        SKU_ATTR50_DESC AS SKU_ATTR50_DESC,
        UPDATE_TSTMP AS UPDATE_TSTMP,
        LOAD_TSTMP AS LOAD_TSTMP,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        SKU_ATTR""")

df_0.createOrReplaceTempView("SKU_ATTR_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_SKU_ATTR_1


df_1=spark.sql("""
    SELECT
        PRODUCT_ID AS PRODUCT_ID,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SKU_ATTR_0""")

df_1.createOrReplaceTempView("SQ_Shortcut_to_SKU_ATTR_1")

# COMMAND ----------
# DBTITLE 1, SKU_PROFILE_2


df_2=spark.sql("""
    SELECT
        PRODUCT_ID AS PRODUCT_ID,
        SKU_NBR AS SKU_NBR,
        SKU_TYPE AS SKU_TYPE,
        PRIMARY_UPC_ID AS PRIMARY_UPC_ID,
        STATUS_ID AS STATUS_ID,
        SUBS_HIST_FLAG AS SUBS_HIST_FLAG,
        SUBS_CURR_FLAG AS SUBS_CURR_FLAG,
        SKU_DESC AS SKU_DESC,
        ALT_DESC AS ALT_DESC,
        SAP_CATEGORY_ID AS SAP_CATEGORY_ID,
        SAP_CLASS_ID AS SAP_CLASS_ID,
        SAP_DEPT_ID AS SAP_DEPT_ID,
        SAP_DIVISION_ID AS SAP_DIVISION_ID,
        PRIMARY_VENDOR_ID AS PRIMARY_VENDOR_ID,
        PARENT_VENDOR_ID AS PARENT_VENDOR_ID,
        COUNTRY_CD AS COUNTRY_CD,
        IMPORT_FLAG AS IMPORT_FLAG,
        HTS_CODE_ID AS HTS_CODE_ID,
        CONTENTS AS CONTENTS,
        CONTENTS_UNITS AS CONTENTS_UNITS,
        WEIGHT_NET_AMT AS WEIGHT_NET_AMT,
        WEIGHT_UOM_CD AS WEIGHT_UOM_CD,
        SIZE_DESC AS SIZE_DESC,
        BUM_QTY AS BUM_QTY,
        UOM_CD AS UOM_CD,
        UNIT_NUMERATOR AS UNIT_NUMERATOR,
        UNIT_DENOMINATOR AS UNIT_DENOMINATOR,
        BUYER_ID AS BUYER_ID,
        PURCH_GROUP_ID AS PURCH_GROUP_ID,
        PURCH_COST_AMT AS PURCH_COST_AMT,
        NAT_PRICE_US_AMT AS NAT_PRICE_US_AMT,
        TAX_CLASS_ID AS TAX_CLASS_ID,
        VALUATION_CLASS_CD AS VALUATION_CLASS_CD,
        BRAND_CD AS BRAND_CD,
        BRAND_CLASSIFICATION_ID AS BRAND_CLASSIFICATION_ID,
        OWNBRAND_FLAG AS OWNBRAND_FLAG,
        STATELINE_FLAG AS STATELINE_FLAG,
        SIGN_TYPE_CD AS SIGN_TYPE_CD,
        OLD_ARTICLE_NBR AS OLD_ARTICLE_NBR,
        VENDOR_ARTICLE_NBR AS VENDOR_ARTICLE_NBR,
        INIT_MKDN_DT AS INIT_MKDN_DT,
        DISC_START_DT AS DISC_START_DT,
        ADD_DT AS ADD_DT,
        DELETE_DT AS DELETE_DT,
        UPDATE_DT AS UPDATE_DT,
        FIRST_SALE_DT AS FIRST_SALE_DT,
        LAST_SALE_DT AS LAST_SALE_DT,
        FIRST_INV_DT AS FIRST_INV_DT,
        LAST_INV_DT AS LAST_INV_DT,
        LOAD_DT AS LOAD_DT,
        BASE_NBR AS BASE_NBR,
        BP_COLOR_ID AS BP_COLOR_ID,
        BP_SIZE_ID AS BP_SIZE_ID,
        BP_BREED_ID AS BP_BREED_ID,
        BP_ITEM_CONCATENATED AS BP_ITEM_CONCATENATED,
        BP_AEROSOL_FLAG AS BP_AEROSOL_FLAG,
        BP_HAZMAT_FLAG AS BP_HAZMAT_FLAG,
        CANADIAN_HTS_CD AS CANADIAN_HTS_CD,
        NAT_PRICE_CA_AMT AS NAT_PRICE_CA_AMT,
        NAT_PRICE_PR_AMT AS NAT_PRICE_PR_AMT,
        RTV_DEPT_CD AS RTV_DEPT_CD,
        GL_ACCT_NBR AS GL_ACCT_NBR,
        ARTICLE_CATEGORY_ID AS ARTICLE_CATEGORY_ID,
        COMPONENT_FLAG AS COMPONENT_FLAG,
        ZDISCO_SCHED_TYPE_ID AS ZDISCO_SCHED_TYPE_ID,
        ZDISCO_MKDN_SCHED_ID AS ZDISCO_MKDN_SCHED_ID,
        ZDISCO_PID_DT AS ZDISCO_PID_DT,
        ZDISCO_START_DT AS ZDISCO_START_DT,
        ZDISCO_INIT_MKDN_DT AS ZDISCO_INIT_MKDN_DT,
        ZDISCO_DC_DT AS ZDISCO_DC_DT,
        ZDISCO_STR_DT AS ZDISCO_STR_DT,
        ZDISCO_STR_OWNRSHP_DT AS ZDISCO_STR_OWNRSHP_DT,
        ZDISCO_STR_WRT_OFF_DT AS ZDISCO_STR_WRT_OFF_DT,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        SKU_PROFILE""")

df_2.createOrReplaceTempView("SKU_PROFILE_2")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_To_SKU_PROFILE_3


df_3=spark.sql("""
    SELECT
        PRODUCT_ID AS PRODUCT_ID,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SKU_PROFILE_2""")

df_3.createOrReplaceTempView("SQ_Shortcut_To_SKU_PROFILE_3")

# COMMAND ----------
# DBTITLE 1, Jnr_Sku_Attr_4


df_4=spark.sql("""
    SELECT
        MASTER.PRODUCT_ID AS PRODUCT_ID,
        DETAIL.PRODUCT_ID AS PRODUCT_ID1,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_To_SKU_PROFILE_3 MASTER 
    RIGHT JOIN
        SQ_Shortcut_to_SKU_ATTR_1 DETAIL 
            ON MASTER.PRODUCT_ID = DETAIL.PRODUCT_ID""")

df_4.createOrReplaceTempView("Jnr_Sku_Attr_4")

# COMMAND ----------
# DBTITLE 1, Fil_Sku_Attr_5


df_5=spark.sql("""
    SELECT
        PRODUCT_ID AS PRODUCT_ID,
        PRODUCT_ID1 AS PRODUCT_ID1,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        Jnr_Sku_Attr_4 
    WHERE
        NOT ISNULL(PRODUCT_ID) 
        AND ISNULL(PRODUCT_ID1)""")

df_5.createOrReplaceTempView("Fil_Sku_Attr_5")

# COMMAND ----------
# DBTITLE 1, Exp_SKU_Attr_6


df_6=spark.sql("""
    SELECT
        PRODUCT_ID AS PRODUCT_ID,
        current_timestamp AS UPDATE_TSTMP,
        current_timestamp AS LOAD_TSTMP,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        Fil_Sku_Attr_5""")

df_6.createOrReplaceTempView("Exp_SKU_Attr_6")

# COMMAND ----------
# DBTITLE 1, SKU_ATTR


spark.sql("""INSERT INTO SKU_ATTR SELECT PRODUCT_ID AS PRODUCT_ID,
SKU_ATTR1_ID AS SKU_ATTR1_ID,
SKU_ATTR1_DESC AS SKU_ATTR1_DESC,
SKU_ATTR2_ID AS SKU_ATTR2_ID,
SKU_ATTR2_DESC AS SKU_ATTR2_DESC,
SKU_SAP_KOI_ID AS SKU_ATTR3_ID,
SKU_SAP_KOI_DESC AS SKU_ATTR3_DESC,
SKU_ATTR4_ID AS SKU_ATTR4_ID,
SKU_ATTR4_DESC AS SKU_ATTR4_DESC,
SKU_ATTR5_ID AS SKU_ATTR5_ID,
SKU_ATTR5_DESC AS SKU_ATTR5_DESC,
SKU_ATTR6_ID AS SKU_ATTR6_ID,
SKU_ATTR6_DESC AS SKU_ATTR6_DESC,
SKU_ATTR7_ID AS SKU_ATTR7_ID,
SKU_ATTR7_DESC AS SKU_ATTR7_DESC,
SKU_ATTR8_ID AS SKU_ATTR8_ID,
SKU_ATTR8_DESC AS SKU_ATTR8_DESC,
SKU_ATTR9_ID AS SKU_ATTR9_ID,
SKU_ATTR9_DESC AS SKU_ATTR9_DESC,
SKU_ATTR10_ID AS SKU_ATTR10_ID,
SKU_ATTR10_DESC AS SKU_ATTR10_DESC,
SKU_SAP_PROD_GROUP_ID AS SKU_ATTR11_ID,
SKU_SAP_PROD_GROUP_DESC AS SKU_ATTR11_DESC,
SKU_SAP_FAMILY_ID AS SKU_ATTR12_ID,
SKU_SAP_FAMILY_DESC AS SKU_ATTR12_DESC,
SKU_SAP_PPU_GROUP_ID AS SKU_ATTR13_ID,
SKU_SAP_PPU_GROUP_DESC AS SKU_ATTR13_DESC,
SKU_SAP_PRVT_LABEL_ID AS SKU_ATTR14_ID,
SKU_SAP_PRVT_LABEL_DESC AS SKU_ATTR14_DESC,
SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_ATTR15_ID,
SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_ATTR15_DESC,
SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_ATTR16_ID,
SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_ATTR16_DESC,
SKU_SAP_MAP_ID AS SKU_ATTR17_ID,
SKU_SAP_MAP_DESC AS SKU_ATTR17_DESC,
SKU_ATTR18_ID AS SKU_ATTR18_ID,
SKU_ATTR18_DESC AS SKU_ATTR18_DESC,
SKU_ATTR19_ID AS SKU_ATTR19_ID,
SKU_ATTR19_DESC AS SKU_ATTR19_DESC,
SKU_ATTR20_ID AS SKU_ATTR20_ID,
SKU_ATTR20_DESC AS SKU_ATTR20_DESC,
SKU_ATTR21_ID AS SKU_ATTR21_ID,
SKU_ATTR21_DESC AS SKU_ATTR21_DESC,
SKU_ATTR22_ID AS SKU_ATTR22_ID,
SKU_ATTR22_DESC AS SKU_ATTR22_DESC,
SKU_ATTR23_ID AS SKU_ATTR23_ID,
SKU_ATTR23_DESC AS SKU_ATTR23_DESC,
SKU_ATTR24_ID AS SKU_ATTR24_ID,
SKU_ATTR24_DESC AS SKU_ATTR24_DESC,
SKU_ATTR25_ID AS SKU_ATTR25_ID,
SKU_ATTR25_DESC AS SKU_ATTR25_DESC,
SKU_ATTR26_ID AS SKU_ATTR26_ID,
SKU_ATTR26_DESC AS SKU_ATTR26_DESC,
SKU_ATTR27_ID AS SKU_ATTR27_ID,
SKU_ATTR27_DESC AS SKU_ATTR27_DESC,
SKU_ATTR28_ID AS SKU_ATTR28_ID,
SKU_ATTR28_DESC AS SKU_ATTR28_DESC,
SKU_ATTR29_ID AS SKU_ATTR29_ID,
SKU_ATTR29_DESC AS SKU_ATTR29_DESC,
SKU_ATTR30_ID AS SKU_ATTR30_ID,
SKU_ATTR30_DESC AS SKU_ATTR30_DESC,
SKU_ATTR31_ID AS SKU_ATTR31_ID,
SKU_ATTR31_DESC AS SKU_ATTR31_DESC,
SKU_ATTR32_ID AS SKU_ATTR32_ID,
SKU_ATTR32_DESC AS SKU_ATTR32_DESC,
SKU_ATTR33_ID AS SKU_ATTR33_ID,
SKU_ATTR33_DESC AS SKU_ATTR33_DESC,
SKU_ATTR34_ID AS SKU_ATTR34_ID,
SKU_ATTR34_DESC AS SKU_ATTR34_DESC,
SKU_ATTR35_ID AS SKU_ATTR35_ID,
SKU_ATTR35_DESC AS SKU_ATTR35_DESC,
SKU_ATTR36_ID AS SKU_ATTR36_ID,
SKU_ATTR36_DESC AS SKU_ATTR36_DESC,
SKU_ATTR37_ID AS SKU_ATTR37_ID,
SKU_ATTR37_DESC AS SKU_ATTR37_DESC,
SKU_ATTR38_ID AS SKU_ATTR38_ID,
SKU_ATTR38_DESC AS SKU_ATTR38_DESC,
SKU_ATTR39_ID AS SKU_ATTR39_ID,
SKU_ATTR39_DESC AS SKU_ATTR39_DESC,
SKU_ATTR40_ID AS SKU_ATTR40_ID,
SKU_ATTR40_DESC AS SKU_ATTR40_DESC,
SKU_ATTR41_ID AS SKU_ATTR41_ID,
SKU_ATTR41_DESC AS SKU_ATTR41_DESC,
SKU_ATTR42_ID AS SKU_ATTR42_ID,
SKU_ATTR42_DESC AS SKU_ATTR42_DESC,
SKU_ATTR43_ID AS SKU_ATTR43_ID,
SKU_ATTR43_DESC AS SKU_ATTR43_DESC,
SKU_ATTR44_ID AS SKU_ATTR44_ID,
SKU_ATTR44_DESC AS SKU_ATTR44_DESC,
SKU_ATTR45_ID AS SKU_ATTR45_ID,
SKU_ATTR45_DESC AS SKU_ATTR45_DESC,
SKU_ATTR46_ID AS SKU_ATTR46_ID,
SKU_ATTR46_DESC AS SKU_ATTR46_DESC,
SKU_ATTR47_ID AS SKU_ATTR47_ID,
SKU_ATTR47_DESC AS SKU_ATTR47_DESC,
SKU_ATTR48_ID AS SKU_ATTR48_ID,
SKU_ATTR48_DESC AS SKU_ATTR48_DESC,
SKU_ATTR49_ID AS SKU_ATTR49_ID,
SKU_ATTR49_DESC AS SKU_ATTR49_DESC,
SKU_ATTR50_ID AS SKU_ATTR50_ID,
SKU_ATTR50_DESC AS SKU_ATTR50_DESC,
o_UPDATE_TSTMP AS UPDATE_TSTMP,
o_LOAD_TSTMP AS LOAD_TSTMP FROM Exp_SKU_Attr_6""")