# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")


# COMMAND ----------
# DBTITLE 1, SKU_SAP_ATTR_PRE_0


df_0=spark.sql("""
    SELECT
        PRODUCT_ID AS PRODUCT_ID,
        SKU_NBR AS SKU_NBR,
        SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
        SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
        SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
        SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
        SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
        SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
        SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
        SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
        SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
        SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
        SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
        SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
        SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
        SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
        LOAD_TSTMP AS LOAD_TSTMP,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        SKU_SAP_ATTR_PRE""")

df_0.createOrReplaceTempView("SKU_SAP_ATTR_PRE_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_SKU_SAP_ATTR_PRE_1


df_1=spark.sql("""
    SELECT
        PRODUCT_ID AS PRODUCT_ID,
        SKU_NBR AS SKU_NBR,
        SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
        SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
        SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
        SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
        SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
        SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
        SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
        SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
        SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
        SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
        SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
        SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
        LOAD_TSTMP AS LOAD_TSTMP,
        SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
        SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SKU_SAP_ATTR_PRE_0""")

df_1.createOrReplaceTempView("SQ_Shortcut_to_SKU_SAP_ATTR_PRE_1")

# COMMAND ----------
# DBTITLE 1, SKU_SAP_ATTR_2


df_2=spark.sql("""
    SELECT
        PRODUCT_ID AS PRODUCT_ID,
        SKU_NBR AS SKU_NBR,
        SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
        SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
        SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
        SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
        SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
        SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
        SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
        SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
        SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
        SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
        SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
        SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
        SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
        SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
        UPDATE_TSTMP AS UPDATE_TSTMP,
        LOAD_TSTMP AS LOAD_TSTMP,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        SKU_SAP_ATTR""")

df_2.createOrReplaceTempView("SKU_SAP_ATTR_2")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_SKU_SAP_ATTR_3


df_3=spark.sql("""
    SELECT
        PRODUCT_ID AS PRODUCT_ID,
        SKU_NBR AS SKU_NBR,
        SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
        SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
        SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
        SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
        SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
        SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
        SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
        SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
        SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
        SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
        SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
        SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
        UPDATE_TSTMP AS UPDATE_TSTMP,
        LOAD_TSTMP AS LOAD_TSTMP,
        SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
        SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SKU_SAP_ATTR_2""")

df_3.createOrReplaceTempView("SQ_Shortcut_to_SKU_SAP_ATTR_3")

# COMMAND ----------
# DBTITLE 1, JNR_SKU_SAP_ATTR_4


df_4=spark.sql("""
    SELECT
        DETAIL.PRODUCT_ID AS PRODUCT_ID,
        DETAIL.SKU_NBR AS SKU_NBR,
        DETAIL.SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
        DETAIL.SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
        DETAIL.SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
        DETAIL.SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
        DETAIL.SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
        DETAIL.SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
        DETAIL.SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
        DETAIL.SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
        DETAIL.SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
        DETAIL.SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
        DETAIL.SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
        DETAIL.SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
        DETAIL.SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
        DETAIL.SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
        DETAIL.SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
        DETAIL.SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
        DETAIL.LOAD_TSTMP AS LOAD_TSTMP,
        MASTER.PRODUCT_ID AS PRODUCT_ID1,
        MASTER.SKU_NBR AS SKU_NBR1,
        MASTER.SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID1,
        MASTER.SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC1,
        MASTER.SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID1,
        MASTER.SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC1,
        MASTER.SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID1,
        MASTER.SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC1,
        MASTER.SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID1,
        MASTER.SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC1,
        MASTER.SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID1,
        MASTER.SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC1,
        MASTER.SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID1,
        MASTER.SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC1,
        MASTER.SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID1,
        MASTER.SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC1,
        MASTER.UPDATE_TSTMP AS UPDATE_TSTMP,
        MASTER.LOAD_TSTMP AS LOAD_TSTMP1,
        MASTER.SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID1,
        MASTER.SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC1,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_to_SKU_SAP_ATTR_3 MASTER 
    LEFT JOIN
        SQ_Shortcut_to_SKU_SAP_ATTR_PRE_1 DETAIL 
            ON MASTER.PRODUCT_ID = DETAIL.PRODUCT_ID""")

df_4.createOrReplaceTempView("JNR_SKU_SAP_ATTR_4")

# COMMAND ----------
# DBTITLE 1, EXP_UPDT_TSTMP_5


df_5=spark.sql("""
    SELECT
        PRODUCT_ID AS PRODUCT_ID,
        SKU_NBR AS SKU_NBR,
        SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
        SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
        SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
        SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
        SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
        SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
        SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
        SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
        SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
        SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
        SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
        SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
        SKU_SAP_KOI_ID1 AS SKU_SAP_KOI_ID1,
        SKU_SAP_KOI_DESC1 AS SKU_SAP_KOI_DESC1,
        PRODUCT_ID1 AS PRODUCT_ID1,
        SKU_NBR1 AS SKU_NBR1,
        SKU_SAP_PROD_GROUP_ID1 AS SKU_SAP_PROD_GROUP_ID1,
        SKU_SAP_PROD_GROUP_DESC1 AS SKU_SAP_PROD_GROUP_DESC1,
        SKU_SAP_FAMILY_ID1 AS SKU_SAP_FAMILY_ID1,
        SKU_SAP_FAMILY_DESC1 AS SKU_SAP_FAMILY_DESC1,
        SKU_SAP_PPU_GROUP_ID1 AS SKU_SAP_PPU_GROUP_ID1,
        SKU_SAP_PPU_GROUP_DESC1 AS SKU_SAP_PPU_GROUP_DESC1,
        SKU_SAP_PRVT_LABEL_ID1 AS SKU_SAP_PRVT_LABEL_ID1,
        SKU_SAP_PRVT_LABEL_DESC1 AS SKU_SAP_PRVT_LABEL_DESC1,
        SKU_SAP_PRVT_LABEL_TIER_ID1 AS SKU_SAP_PRVT_LABEL_TIER_ID1,
        SKU_SAP_PRVT_LABEL_TIER_DESC1 AS SKU_SAP_PRVT_LABEL_TIER_DESC1,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_ID1 AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID1,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC1 AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC1,
        SKU_SAP_MAP_ID1 AS SKU_SAP_MAP_ID1,
        SKU_SAP_MAP_DESC1 AS SKU_SAP_MAP_DESC1,
        SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
        SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
        SYSTIMESTAMP() AS o_UPDATE_TSTMP,
        IFF(ISNULL(LOAD_TSTMP1),
        SYSTIMESTAMP(),
        LOAD_TSTMP1) AS o_LOAD_TSTMP,
        IFF(ISNULL(PRODUCT_ID1),
        'I',
        IFF((SKU_NBR <> SKU_NBR1) 
        OR IFF(ISNULL(SKU_SAP_PROD_GROUP_ID),
        9999,
        SKU_SAP_PROD_GROUP_ID) <> IFF(ISNULL(SKU_SAP_PROD_GROUP_ID1),
        9999,
        SKU_SAP_PROD_GROUP_ID1) 
        OR IFF(ISNULL(SKU_SAP_PROD_GROUP_DESC),
        ' ',
        SKU_SAP_PROD_GROUP_DESC) <> IFF(ISNULL(SKU_SAP_PROD_GROUP_DESC1),
        ' ',
        SKU_SAP_PROD_GROUP_DESC1) 
        OR IFF(ISNULL(SKU_SAP_FAMILY_ID),
        9999,
        SKU_SAP_FAMILY_ID) <> IFF(ISNULL(SKU_SAP_FAMILY_ID1),
        9999,
        SKU_SAP_FAMILY_ID1) 
        OR IFF(ISNULL(SKU_SAP_FAMILY_DESC),
        ' ',
        SKU_SAP_FAMILY_DESC) <> IFF(ISNULL(SKU_SAP_FAMILY_DESC1),
        ' ',
        SKU_SAP_FAMILY_DESC1) 
        OR IFF(ISNULL(SKU_SAP_PPU_GROUP_ID),
        9999,
        SKU_SAP_PPU_GROUP_ID) <> IFF(ISNULL(SKU_SAP_PPU_GROUP_ID1),
        9999,
        SKU_SAP_PPU_GROUP_ID1) 
        OR IFF(ISNULL(SKU_SAP_PPU_GROUP_DESC),
        ' ',
        SKU_SAP_PPU_GROUP_DESC) <> IFF(ISNULL(SKU_SAP_PPU_GROUP_DESC1),
        ' ',
        SKU_SAP_PPU_GROUP_DESC1) 
        OR IFF(ISNULL(SKU_SAP_PRVT_LABEL_ID),
        9999,
        SKU_SAP_PRVT_LABEL_ID) <> IFF(ISNULL(SKU_SAP_PRVT_LABEL_ID1),
        9999,
        SKU_SAP_PRVT_LABEL_ID1) 
        OR IFF(ISNULL(SKU_SAP_PRVT_LABEL_DESC),
        ' ',
        SKU_SAP_PRVT_LABEL_DESC) <> IFF(ISNULL(SKU_SAP_PRVT_LABEL_DESC1),
        ' ',
        SKU_SAP_PRVT_LABEL_DESC1) 
        OR IFF(ISNULL(SKU_SAP_MAP_DESC),
        ' ',
        SKU_SAP_MAP_DESC) <> IFF(ISNULL(SKU_SAP_MAP_DESC1),
        ' ',
        SKU_SAP_MAP_DESC1) 
        OR IFF(ISNULL(SKU_SAP_PRVT_LABEL_TIER_DESC),
        ' ',
        SKU_SAP_PRVT_LABEL_TIER_DESC) <> IFF(ISNULL(SKU_SAP_PRVT_LABEL_TIER_DESC1),
        ' ',
        SKU_SAP_PRVT_LABEL_TIER_DESC1) 
        OR IFF(ISNULL(SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC),
        ' ',
        SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC) <> IFF(ISNULL(SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC1),
        ' ',
        SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC1) 
        OR IFF(ISNULL(SKU_SAP_KOI_ID),
        9999,
        SKU_SAP_KOI_ID) <> IFF(ISNULL(SKU_SAP_KOI_ID),
        9999,
        SKU_SAP_KOI_ID) 
        OR IFF(ISNULL(SKU_SAP_KOI_DESC),
        'ZZZ',
        SKU_SAP_KOI_DESC) <> IFF(ISNULL(SKU_SAP_KOI_DESC),
        'ZZZ',
        SKU_SAP_KOI_DESC),
        'U',
        'R')) AS o_UPD_FLG,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNR_SKU_SAP_ATTR_4""")

df_5.createOrReplaceTempView("EXP_UPDT_TSTMP_5")

# COMMAND ----------
# DBTITLE 1, FIL_UPD_FLG_6


df_6=spark.sql("""
    SELECT
        PRODUCT_ID AS PRODUCT_ID,
        SKU_NBR AS SKU_NBR,
        SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
        SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
        SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
        SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
        SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
        SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
        SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
        SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
        SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
        SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
        SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
        SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
        SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
        SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
        o_UPDATE_TSTMP AS o_UPDATE_TSTMP,
        o_LOAD_TSTMP AS o_LOAD_TSTMP,
        o_UPD_FLG AS o_UPD_FLG,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        EXP_UPDT_TSTMP_5 
    WHERE
        o_UPD_FLG = 'I' 
        OR o_UPD_FLG = 'U'""")

df_6.createOrReplaceTempView("FIL_UPD_FLG_6")

# COMMAND ----------
# DBTITLE 1, UPD_SKU_SAP_ATTR_7


df_7=spark.sql("""
    SELECT
        PRODUCT_ID AS PRODUCT_ID,
        SKU_NBR AS SKU_NBR,
        SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
        SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
        SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
        SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
        SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
        SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
        SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
        SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
        SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
        SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
        SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
        SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
        SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
        SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
        SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
        o_UPDATE_TSTMP AS o_UPDATE_TSTMP,
        o_LOAD_TSTMP AS o_LOAD_TSTMP,
        o_UPD_FLG AS o_UPD_FLG,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        FIL_UPD_FLG_6""")

df_7.createOrReplaceTempView("UPD_SKU_SAP_ATTR_7")

# COMMAND ----------
# DBTITLE 1, SKU_SAP_ATTR


spark.sql("""INSERT INTO SKU_SAP_ATTR SELECT PRODUCT_ID AS PRODUCT_ID,
SKU_NBR AS SKU_NBR,
SKU_SAP_PROD_GROUP_ID AS SKU_SAP_PROD_GROUP_ID,
SKU_SAP_PROD_GROUP_DESC AS SKU_SAP_PROD_GROUP_DESC,
SKU_SAP_FAMILY_ID AS SKU_SAP_FAMILY_ID,
SKU_SAP_FAMILY_DESC AS SKU_SAP_FAMILY_DESC,
SKU_SAP_PPU_GROUP_ID AS SKU_SAP_PPU_GROUP_ID,
SKU_SAP_PPU_GROUP_DESC AS SKU_SAP_PPU_GROUP_DESC,
SKU_SAP_PRVT_LABEL_ID AS SKU_SAP_PRVT_LABEL_ID,
SKU_SAP_PRVT_LABEL_DESC AS SKU_SAP_PRVT_LABEL_DESC,
SKU_SAP_PRVT_LABEL_TIER_ID AS SKU_SAP_PRVT_LABEL_TIER_ID,
SKU_SAP_PRVT_LABEL_TIER_DESC AS SKU_SAP_PRVT_LABEL_TIER_DESC,
SKU_SAP_PRVT_LABEL_PARENT_TIER_ID AS SKU_SAP_PRVT_LABEL_PARENT_TIER_ID,
SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC AS SKU_SAP_PRVT_LABEL_PARENT_TIER_DESC,
SKU_SAP_MAP_ID AS SKU_SAP_MAP_ID,
SKU_SAP_MAP_DESC AS SKU_SAP_MAP_DESC,
SKU_SAP_KOI_ID AS SKU_SAP_KOI_ID,
SKU_SAP_KOI_DESC AS SKU_SAP_KOI_DESC,
o_UPDATE_TSTMP AS UPDATE_TSTMP,
o_LOAD_TSTMP AS LOAD_TSTMP FROM UPD_SKU_SAP_ATTR_7""")