# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")


# COMMAND ----------
# DBTITLE 1, USR_STORE_ATTRIBUTES_PRE_0


df_0=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        STORE_NBR AS STORE_NBR,
        BOUTIQUE_FLAG AS BOUTIQUE_FLAG,
        VET_TYPE_ID AS VET_TYPE_ID,
        VET_TYPE_DESC AS VET_TYPE_DESC,
        MICRO_HOTEL_FLAG AS MICRO_HOTEL_FLAG,
        ONP_DIST_FLAG AS ONP_DIST_FLAG,
        PET_TRAINING_FLAG AS PET_TRAINING_FLAG,
        HOTEL_PROTOTYPE_FLAG AS HOTEL_PROTOTYPE_FLAG,
        HOTEL_TIER_ID AS HOTEL_TIER_ID,
        STORE_CENTER_TYPE_ID AS STORE_CENTER_TYPE_ID,
        STORE_CENTER_TYPE_DESC AS STORE_CENTER_TYPE_DESC,
        STORE_SIZE_TYPE_ID AS STORE_SIZE_TYPE_ID,
        STORE_SIZE_TYPE_DESC AS STORE_SIZE_TYPE_DESC,
        FISH_SYSTEM_TYPE_ID AS FISH_SYSTEM_TYPE_ID,
        FISH_SYSTEM_TYPE_DESC AS FISH_SYSTEM_TYPE_DESC,
        GROOMERY_FLAG AS GROOMERY_FLAG,
        STORE_PROGRAM_ID AS STORE_PROGRAM_ID,
        MICRO_SALON_FLAG AS MICRO_SALON_FLAG,
        NO_FORKLIFT_FLAG AS NO_FORKLIFT_FLAG,
        MARKET_LEADER_ID AS MARKET_LEADER_ID,
        MARKET_LEADER_DESC AS MARKET_LEADER_DESC,
        LOAD_TSTMP AS LOAD_TSTMP,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        USR_STORE_ATTRIBUTES_PRE""")

df_0.createOrReplaceTempView("USR_STORE_ATTRIBUTES_PRE_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_USR_STORE_ATTRIBUTES_PRE_1


df_1=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        STORE_NBR AS STORE_NBR,
        BOUTIQUE_FLAG AS BOUTIQUE_FLAG,
        VET_TYPE_ID AS VET_TYPE_ID,
        VET_TYPE_DESC AS VET_TYPE_DESC,
        MICRO_HOTEL_FLAG AS MICRO_HOTEL_FLAG,
        ONP_DIST_FLAG AS ONP_DIST_FLAG,
        PET_TRAINING_FLAG AS PET_TRAINING_FLAG,
        HOTEL_PROTOTYPE_FLAG AS HOTEL_PROTOTYPE_FLAG,
        HOTEL_TIER_ID AS HOTEL_TIER_ID,
        STORE_CENTER_TYPE_ID AS STORE_CENTER_TYPE_ID,
        STORE_CENTER_TYPE_DESC AS STORE_CENTER_TYPE_DESC,
        STORE_SIZE_TYPE_ID AS STORE_SIZE_TYPE_ID,
        STORE_SIZE_TYPE_DESC AS STORE_SIZE_TYPE_DESC,
        FISH_SYSTEM_TYPE_ID AS FISH_SYSTEM_TYPE_ID,
        FISH_SYSTEM_TYPE_DESC AS FISH_SYSTEM_TYPE_DESC,
        GROOMERY_FLAG AS GROOMERY_FLAG,
        STORE_PROGRAM_ID AS STORE_PROGRAM_ID,
        MICRO_SALON_FLAG AS MICRO_SALON_FLAG,
        NO_FORKLIFT_FLAG AS NO_FORKLIFT_FLAG,
        LOAD_TSTMP AS LOAD_TSTMP,
        MARKET_LEADER_ID AS MARKET_LEADER_ID,
        MARKET_LEADER_DESC AS MARKET_LEADER_DESC,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        USR_STORE_ATTRIBUTES_PRE_0""")

df_1.createOrReplaceTempView("SQ_Shortcut_to_USR_STORE_ATTRIBUTES_PRE_1")

# COMMAND ----------
# DBTITLE 1, EXP_ADDING_FILLER_ZEROS_2


df_2=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        STORE_NBR AS STORE_NBR,
        BOUTIQUE_FLAG AS BOUTIQUE_FLAG,
        VET_TYPE_ID AS VET_TYPE_ID,
        VET_TYPE_DESC AS VET_TYPE_DESC,
        MICRO_HOTEL_FLAG AS MICRO_HOTEL_FLAG,
        ONP_DIST_FLAG AS ONP_DIST_FLAG,
        PET_TRAINING_FLAG AS PET_TRAINING_FLAG,
        HOTEL_PROTOTYPE_FLAG AS HOTEL_PROTOTYPE_FLAG,
        HOTEL_TIER_ID AS HOTEL_TIER_ID,
        STORE_CENTER_TYPE_ID AS STORE_CENTER_TYPE_ID,
        STORE_CENTER_TYPE_DESC AS STORE_CENTER_TYPE_DESC,
        STORE_SIZE_TYPE_ID AS STORE_SIZE_TYPE_ID,
        STORE_SIZE_TYPE_DESC AS STORE_SIZE_TYPE_DESC,
        FISH_SYSTEM_TYPE_ID AS FISH_SYSTEM_TYPE_ID,
        FISH_SYSTEM_TYPE_DESC AS FISH_SYSTEM_TYPE_DESC,
        0 AS SSDW_FLAG,
        0 AS DOG_WALK_FLAG,
        GROOMERY_FLAG AS GROOMERY_FLAG,
        STORE_PROGRAM_ID AS STORE_PROGRAM_ID,
        MICRO_SALON_FLAG AS MICRO_SALON_FLAG,
        NO_FORKLIFT_FLAG AS NO_FORKLIFT_FLAG,
        LOAD_TSTMP AS LOAD_TSTMP,
        MARKET_LEADER_ID AS MARKET_LEADER_ID,
        MARKET_LEADER_DESC AS MARKET_LEADER_DESC,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_to_USR_STORE_ATTRIBUTES_PRE_1""")

df_2.createOrReplaceTempView("EXP_ADDING_FILLER_ZEROS_2")

# COMMAND ----------
# DBTITLE 1, USR_STORE_ATTRIBUTES_3


df_3=spark.sql("""
    SELECT
        STORE_NBR AS STORE_NBR,
        BOUTIQUE_FLAG AS BOUTIQUE_FLAG,
        VET_TYPE_ID AS VET_TYPE_ID,
        MICRO_HOTEL_FLAG AS MICRO_HOTEL_FLAG,
        ONP_DIST_FLAG AS ONP_DIST_FLAG,
        PET_TRAINING_FLAG AS PET_TRAINING_FLAG,
        HOTEL_PROTOTYPE_FLAG AS HOTEL_PROTOTYPE_FLAG,
        HOTEL_TIER_ID AS HOTEL_TIER_ID,
        STORE_CENTER_TYPE_ID AS STORE_CENTER_TYPE_ID,
        STORE_SIZE_TYPE_ID AS STORE_SIZE_TYPE_ID,
        FISH_SYSTEM_TYPE_ID AS FISH_SYSTEM_TYPE_ID,
        STORE_PROGRAM_ID AS STORE_PROGRAM_ID,
        MICRO_SALON_FLAG AS MICRO_SALON_FLAG,
        NO_FORKLIFT_FLAG AS NO_FORKLIFT_FLAG,
        MARKET_LEADER_ID AS MARKET_LEADER_ID,
        MARKET_LEADER_DESC AS MARKET_LEADER_DESC,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        USR_STORE_ATTRIBUTES""")

df_3.createOrReplaceTempView("USR_STORE_ATTRIBUTES_3")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_USR_STORE_ATTRIBUTES_4


df_4=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        STORE_NBR AS STORE_NBR,
        BOUTIQUE_FLAG AS BOUTIQUE_FLAG,
        VET_TYPE_ID AS VET_TYPE_ID,
        VET_TYPE_DESC AS VET_TYPE_DESC,
        MICRO_HOTEL_FLAG AS MICRO_HOTEL_FLAG,
        ONP_DIST_FLAG AS ONP_DIST_FLAG,
        PET_TRAINING_FLAG AS PET_TRAINING_FLAG,
        HOTEL_PROTOTYPE_FLAG AS HOTEL_PROTOTYPE_FLAG,
        HOTEL_TIER_ID AS HOTEL_TIER_ID,
        STORE_CENTER_TYPE_ID AS STORE_CENTER_TYPE_ID,
        STORE_CENTER_TYPE_DESC AS STORE_CENTER_TYPE_DESC,
        STORE_SIZE_TYPE_ID AS STORE_SIZE_TYPE_ID,
        STORE_SIZE_TYPE_DESC AS STORE_SIZE_TYPE_DESC,
        FISH_SYSTEM_TYPE_ID AS FISH_SYSTEM_TYPE_ID,
        FISH_SYSTEM_TYPE_DESC AS FISH_SYSTEM_TYPE_DESC,
        SSDW_FLAG AS SSDW_FLAG,
        DOG_WALK_FLAG AS DOG_WALK_FLAG,
        GROOMERY_FLAG AS GROOMERY_FLAG,
        STORE_PROGRAM_ID AS STORE_PROGRAM_ID,
        MICRO_SALON_FLAG AS MICRO_SALON_FLAG,
        NO_FORKLIFT_FLAG AS NO_FORKLIFT_FLAG,
        UPDATE_TSTMP AS UPDATE_TSTMP,
        LOAD_TSTMP AS LOAD_TSTMP,
        MARKET_LEADER_ID AS MARKET_LEADER_ID,
        MARKET_LEADER_DESC AS MARKET_LEADER_DESC,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        USR_STORE_ATTRIBUTES_3""")

df_4.createOrReplaceTempView("SQ_Shortcut_to_USR_STORE_ATTRIBUTES_4")

# COMMAND ----------
# DBTITLE 1, JNR_UPD_STRATEGY_5


df_5=spark.sql("""
    SELECT
        DETAIL.LOCATION_ID AS LOCATION_ID,
        DETAIL.STORE_NBR AS STORE_NBR,
        DETAIL.BOUTIQUE_FLAG AS BOUTIQUE_FLAG,
        DETAIL.VET_TYPE_ID AS VET_TYPE_ID1,
        DETAIL.VET_TYPE_DESC AS VET_TYPE_DESC1,
        DETAIL.MICRO_HOTEL_FLAG AS MICRO_HOTEL_FLAG,
        DETAIL.ONP_DIST_FLAG AS ONP_DIST_FLAG,
        DETAIL.PET_TRAINING_FLAG AS PET_TRAINING_FLAG,
        DETAIL.HOTEL_PROTOTYPE_FLAG AS HOTEL_PROTOTYPE_FLAG,
        DETAIL.HOTEL_TIER_ID AS HOTEL_TIER_ID,
        DETAIL.STORE_CENTER_TYPE_ID AS STORE_CENTER_TYPE_ID,
        DETAIL.STORE_CENTER_TYPE_DESC AS STORE_CENTER_TYPE_DESC,
        DETAIL.STORE_SIZE_TYPE_ID AS STORE_SIZE_TYPE_ID,
        DETAIL.STORE_SIZE_TYPE_DESC AS STORE_SIZE_TYPE_DESC,
        DETAIL.FISH_SYSTEM_TYPE_ID AS FISH_SYSTEM_TYPE_ID,
        DETAIL.FISH_SYSTEM_TYPE_DESC AS FISH_SYSTEM_TYPE_DESC,
        DETAIL.SSDW_FLAG AS SSDW_FLAG,
        DETAIL.DOG_WALK_FLAG AS DOG_WALK_FLAG,
        DETAIL.GROOMERY_FLAG AS GROOMERY_FLAG,
        DETAIL.STORE_PROGRAM_ID AS STORE_PROGRAM_ID,
        DETAIL.MICRO_SALON_FLAG AS MICRO_SALON_FLAG,
        DETAIL.NO_FORKLIFT_FLAG AS NO_FORKLIFT_FLAG,
        MASTER.LOCATION_ID AS LOCATION_ID1,
        MASTER.STORE_NBR AS STORE_NBR1,
        MASTER.BOUTIQUE_FLAG AS BOUTIQUE_FLAG1,
        MASTER.VET_TYPE_ID AS VET_TYPE_ID,
        MASTER.VET_TYPE_DESC AS VET_TYPE_DESC,
        MASTER.MICRO_HOTEL_FLAG AS MICRO_HOTEL_FLAG1,
        MASTER.ONP_DIST_FLAG AS ONP_DIST_FLAG1,
        MASTER.PET_TRAINING_FLAG AS PET_TRAINING_FLAG1,
        MASTER.HOTEL_PROTOTYPE_FLAG AS HOTEL_PROTOTYPE_FLAG1,
        MASTER.HOTEL_TIER_ID AS HOTEL_TIER_ID1,
        MASTER.STORE_CENTER_TYPE_ID AS STORE_CENTER_TYPE_ID1,
        MASTER.STORE_CENTER_TYPE_DESC AS STORE_CENTER_TYPE_DESC1,
        MASTER.STORE_SIZE_TYPE_ID AS STORE_SIZE_TYPE_ID1,
        MASTER.STORE_SIZE_TYPE_DESC AS STORE_SIZE_TYPE_DESC1,
        MASTER.FISH_SYSTEM_TYPE_ID AS FISH_SYSTEM_TYPE_ID1,
        MASTER.FISH_SYSTEM_TYPE_DESC AS FISH_SYSTEM_TYPE_DESC1,
        MASTER.SSDW_FLAG AS SSDW_FLAG1,
        MASTER.DOG_WALK_FLAG AS DOG_WALK_FLAG1,
        MASTER.GROOMERY_FLAG AS GROOMERY_FLAG1,
        MASTER.STORE_PROGRAM_ID AS STORE_PROGRAM_ID1,
        MASTER.MICRO_SALON_FLAG AS MICRO_SALON_FLAG1,
        MASTER.NO_FORKLIFT_FLAG AS NO_FORKLIFT_FLAG1,
        MASTER.UPDATE_TSTMP AS UPDATE_TSTMP,
        MASTER.LOAD_TSTMP AS LOAD_TSTMP,
        DETAIL.MARKET_LEADER_ID AS MARKET_LEADER_ID,
        DETAIL.MARKET_LEADER_DESC AS MARKET_LEADER_DESC,
        MASTER.MARKET_LEADER_ID AS MARKET_LEADER_ID1,
        MASTER.MARKET_LEADER_DESC AS MARKET_LEADER_DESC1,
        MASTER.Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SQ_Shortcut_to_USR_STORE_ATTRIBUTES_4 MASTER 
    LEFT JOIN
        EXP_ADDING_FILLER_ZEROS_2 DETAIL 
            ON MASTER.LOCATION_ID = DETAIL.LOCATION_ID""")

df_5.createOrReplaceTempView("JNR_UPD_STRATEGY_5")

# COMMAND ----------
# DBTITLE 1, EXP_UPD_STRATEGY_6


df_6=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        STORE_NBR AS STORE_NBR,
        BOUTIQUE_FLAG AS BOUTIQUE_FLAG,
        VET_TYPE_ID AS VET_TYPE_ID,
        VET_TYPE_DESC AS VET_TYPE_DESC,
        MICRO_HOTEL_FLAG AS MICRO_HOTEL_FLAG,
        ONP_DIST_FLAG AS ONP_DIST_FLAG,
        PET_TRAINING_FLAG AS PET_TRAINING_FLAG,
        HOTEL_PROTOTYPE_FLAG AS HOTEL_PROTOTYPE_FLAG,
        HOTEL_TIER_ID AS HOTEL_TIER_ID,
        STORE_CENTER_TYPE_ID AS STORE_CENTER_TYPE_ID,
        STORE_CENTER_TYPE_DESC AS STORE_CENTER_TYPE_DESC,
        STORE_SIZE_TYPE_ID AS STORE_SIZE_TYPE_ID,
        STORE_SIZE_TYPE_DESC AS STORE_SIZE_TYPE_DESC,
        FISH_SYSTEM_TYPE_ID AS FISH_SYSTEM_TYPE_ID,
        FISH_SYSTEM_TYPE_DESC AS FISH_SYSTEM_TYPE_DESC,
        IFF(ISNULL(SSDW_FLAG1),
        SSDW_FLAG,
        SSDW_FLAG1) AS o_SSDW_FLAG,
        IFF(ISNULL(DOG_WALK_FLAG1),
        DOG_WALK_FLAG,
        DOG_WALK_FLAG1) AS o_DOG_WALK_FLAG,
        GROOMERY_FLAG AS GROOMERY_FLAG,
        STORE_PROGRAM_ID AS STORE_PROGRAM_ID,
        MICRO_SALON_FLAG AS MICRO_SALON_FLAG,
        NO_FORKLIFT_FLAG AS NO_FORKLIFT_FLAG,
        current_timestamp AS UPDATE_TSTMP,
        IFF(ISNULL(LOAD_TSTMP),
        current_timestamp,
        LOAD_TSTMP) AS o_LOAD_TSTMP,
        IFF(NEW_RECORD = 1,
        DD_INSERT,
        IFF(MD5_UPD = 0,
        DD_UPDATE,
        DD_REJECT)) AS UPD_STRATEGY,
        MARKET_LEADER_ID AS MARKET_LEADER_ID,
        MARKET_LEADER_DESC AS MARKET_LEADER_DESC,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        JNR_UPD_STRATEGY_5""")

df_6.createOrReplaceTempView("EXP_UPD_STRATEGY_6")

# COMMAND ----------
# DBTITLE 1, FIL_NO_CHANGES_7


df_7=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        STORE_NBR AS STORE_NBR,
        BOUTIQUE_FLAG AS BOUTIQUE_FLAG,
        VET_TYPE_ID AS VET_TYPE_ID,
        VET_TYPE_DESC AS VET_TYPE_DESC,
        MICRO_HOTEL_FLAG AS MICRO_HOTEL_FLAG,
        ONP_DIST_FLAG AS ONP_DIST_FLAG,
        PET_TRAINING_FLAG AS PET_TRAINING_FLAG,
        HOTEL_PROTOTYPE_FLAG AS HOTEL_PROTOTYPE_FLAG,
        HOTEL_TIER_ID AS HOTEL_TIER_ID,
        STORE_CENTER_TYPE_ID AS STORE_CENTER_TYPE_ID,
        STORE_CENTER_TYPE_DESC AS STORE_CENTER_TYPE_DESC,
        STORE_SIZE_TYPE_ID AS STORE_SIZE_TYPE_ID,
        STORE_SIZE_TYPE_DESC AS STORE_SIZE_TYPE_DESC,
        FISH_SYSTEM_TYPE_ID AS FISH_SYSTEM_TYPE_ID,
        FISH_SYSTEM_TYPE_DESC AS FISH_SYSTEM_TYPE_DESC,
        o_SSDW_FLAG AS o_SSDW_FLAG,
        o_DOG_WALK_FLAG AS o_DOG_WALK_FLAG,
        GROOMERY_FLAG AS GROOMERY_FLAG,
        STORE_PROGRAM_ID AS STORE_PROGRAM_ID,
        MICRO_SALON_FLAG AS MICRO_SALON_FLAG,
        NO_FORKLIFT_FLAG AS NO_FORKLIFT_FLAG,
        UPDATE_TSTMP AS UPDATE_TSTMP,
        o_LOAD_TSTMP AS o_LOAD_TSTMP,
        UPD_STRATEGY AS UPD_STRATEGY,
        MARKET_LEADER_ID AS MARKET_LEADER_ID,
        MARKET_LEADER_DESC AS MARKET_LEADER_DESC,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        EXP_UPD_STRATEGY_6 
    WHERE
        UPD_STRATEGY <> DD_REJECT""")

df_7.createOrReplaceTempView("FIL_NO_CHANGES_7")

# COMMAND ----------
# DBTITLE 1, UPD_STRATEGY_8


df_8=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        STORE_NBR AS STORE_NBR,
        BOUTIQUE_FLAG AS BOUTIQUE_FLAG,
        VET_TYPE_ID AS VET_TYPE_ID,
        VET_TYPE_DESC AS VET_TYPE_DESC,
        MICRO_HOTEL_FLAG AS MICRO_HOTEL_FLAG,
        ONP_DIST_FLAG AS ONP_DIST_FLAG,
        PET_TRAINING_FLAG AS PET_TRAINING_FLAG,
        HOTEL_PROTOTYPE_FLAG AS HOTEL_PROTOTYPE_FLAG,
        HOTEL_TIER_ID AS HOTEL_TIER_ID,
        STORE_CENTER_TYPE_ID AS STORE_CENTER_TYPE_ID,
        STORE_CENTER_TYPE_DESC AS STORE_CENTER_TYPE_DESC,
        STORE_SIZE_TYPE_ID AS STORE_SIZE_TYPE_ID,
        STORE_SIZE_TYPE_DESC AS STORE_SIZE_TYPE_DESC,
        FISH_SYSTEM_TYPE_ID AS FISH_SYSTEM_TYPE_ID,
        FISH_SYSTEM_TYPE_DESC AS FISH_SYSTEM_TYPE_DESC,
        o_SSDW_FLAG AS o_SSDW_FLAG,
        o_DOG_WALK_FLAG AS o_DOG_WALK_FLAG,
        GROOMERY_FLAG AS GROOMERY_FLAG,
        STORE_PROGRAM_ID AS STORE_PROGRAM_ID,
        MICRO_SALON_FLAG AS MICRO_SALON_FLAG,
        NO_FORKLIFT_FLAG AS NO_FORKLIFT_FLAG,
        UPDATE_TSTMP AS UPDATE_TSTMP,
        o_LOAD_TSTMP AS o_LOAD_TSTMP,
        UPD_STRATEGY AS UPD_STRATEGY,
        MARKET_LEADER_ID AS MARKET_LEADER_ID,
        MARKET_LEADER_DESC AS MARKET_LEADER_DESC,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        FIL_NO_CHANGES_7""")

df_8.createOrReplaceTempView("UPD_STRATEGY_8")

# COMMAND ----------
# DBTITLE 1, USR_STORE_ATTRIBUTES


spark.sql("""INSERT INTO USR_STORE_ATTRIBUTES SELECT LOCATION_ID AS LOCATION_ID,
STORE_NBR AS STORE_NBR,
BOUTIQUE_FLAG AS BOUTIQUE_FLAG,
VET_TYPE_ID AS VET_TYPE_ID,
VET_TYPE_DESC AS VET_TYPE_DESC,
MICRO_HOTEL_FLAG AS MICRO_HOTEL_FLAG,
ONP_DIST_FLAG AS ONP_DIST_FLAG,
PET_TRAINING_FLAG AS PET_TRAINING_FLAG,
HOTEL_PROTOTYPE_FLAG AS HOTEL_PROTOTYPE_FLAG,
HOTEL_TIER_ID AS HOTEL_TIER_ID,
STORE_CENTER_TYPE_ID AS STORE_CENTER_TYPE_ID,
STORE_CENTER_TYPE_DESC AS STORE_CENTER_TYPE_DESC,
STORE_SIZE_TYPE_ID AS STORE_SIZE_TYPE_ID,
STORE_SIZE_TYPE_DESC AS STORE_SIZE_TYPE_DESC,
FISH_SYSTEM_TYPE_ID AS FISH_SYSTEM_TYPE_ID,
FISH_SYSTEM_TYPE_DESC AS FISH_SYSTEM_TYPE_DESC,
SSDW_FLAG AS SSDW_FLAG,
DOG_WALK_FLAG AS DOG_WALK_FLAG,
GROOMERY_FLAG AS GROOMERY_FLAG,
STORE_PROGRAM_ID AS STORE_PROGRAM_ID,
MICRO_SALON_FLAG AS MICRO_SALON_FLAG,
NO_FORKLIFT_FLAG AS NO_FORKLIFT_FLAG,
MARKET_LEADER_ID AS MARKET_LEADER_ID,
MARKET_LEADER_DESC AS MARKET_LEADER_DESC,
UPD_TSTMP AS UPDATE_TSTMP,
current_timestamp() AS LOAD_TSTMP FROM UPD_STRATEGY_8""")