# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")


# COMMAND ----------

# DBTITLE 1, VENDOR_MINIMUM_PRE_0

df_0=spark.sql("""
    SELECT
        VENDOR_ID AS VENDOR_ID,
        STORE_NBR AS STORE_NBR,
        SKU_NBR AS SKU_NBR,
        SEARCH_LEVEL AS SEARCH_LEVEL,
        DELETE_IND AS DELETE_IND,
        MIN_AMT AS MIN_AMT,
        MAX_AMT AS MAX_AMT,
        MIN_QTY AS MIN_QTY,
        MIN_QTY_UOM_CD AS MIN_QTY_UOM_CD,
        MAX_QTY AS MAX_QTY,
        MAX_QTY_UOM_CD AS MAX_QTY_UOM_CD,
        MIN_VOLUME_CFT AS MIN_VOLUME_CFT,
        MAX_VOLUME_CFT AS MAX_VOLUME_CFT,
        MIN_WEIGHT_LBS AS MIN_WEIGHT_LBS,
        MAX_WEIGHT_LBS AS MAX_WEIGHT_LBS,
        LOAD_DT AS LOAD_DT,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        VENDOR_MINIMUM_PRE""")

df_0.createOrReplaceTempView("VENDOR_MINIMUM_PRE_0")

# COMMAND ----------

# DBTITLE 1, ASQ_Shortcut_To_VENDOR_MINIMUM_PRE_1

df_1=spark.sql("""
    SELECT
        VMP.VENDOR_ID,
        SITE.LOCATION_ID,
        SKU.PRODUCT_ID,
        VMP.SEARCH_LEVEL,
        VMP.MIN_AMT,
        VMP.MAX_AMT,
        VMP.MIN_QTY,
        VMP.MIN_QTY_UOM_CD,
        VMP.MAX_QTY,
        VMP.MAX_QTY_UOM_CD,
        VMP.MIN_VOLUME_CFT,
        VMP.MAX_VOLUME_CFT,
        VMP.MIN_WEIGHT_LBS,
        VMP.MAX_WEIGHT_LBS,
        CURRENT_TIMESTAMP 
    FROM
        VENDOR_MINIMUM_PRE VMP,
        SKU_PROFILE SKU,
        SITE_PROFILE SITE 
    WHERE
        VMP.STORE_NBR = SITE.STORE_NBR 
        AND VMP.SKU_NBR = SKU.SKU_NBR""")

df_1.createOrReplaceTempView("ASQ_Shortcut_To_VENDOR_MINIMUM_PRE_1")

# COMMAND ----------

# DBTITLE 1, VENDOR_MINIMUM

spark.sql("""INSERT INTO VENDOR_MINIMUM SELECT VENDOR_ID AS VENDOR_ID,
LOCATION_ID AS LOCATION_ID,
PRODUCT_ID AS PRODUCT_ID,
SEARCH_LEVEL AS SEARCH_LEVEL,
MIN_AMT AS MIN_AMT,
MAX_AMT AS MAX_AMT,
MIN_QTY AS MIN_QTY,
MIN_QTY_UOM_CD AS MIN_QTY_UOM_CD,
MAX_QTY AS MAX_QTY,
MAX_QTY_UOM_CD AS MAX_QTY_UOM_CD,
MIN_VOLUME_CFT AS MIN_VOLUME_CFT,
MAX_VOLUME_CFT AS MAX_VOLUME_CFT,
MIN_WEIGHT_LBS AS MIN_WEIGHT_LBS,
MAX_WEIGHT_LBS AS MAX_WEIGHT_LBS,
LOAD_DT AS LOAD_DT FROM ASQ_Shortcut_To_VENDOR_MINIMUM_PRE_1""")
